-- Auto-gerado: leaf_bloc.name_bloc
BEGIN;

UPDATE public.leaf_bloc SET name_bloc = 'Alicerce de Execução' WHERE name_bloc = 'Alicerce de Execu????o';
UPDATE public.leaf_bloc SET name_bloc = 'Alocação Profissional Externa' WHERE name_bloc = 'Aloca????o Profissional Externa';
UPDATE public.leaf_bloc SET name_bloc = 'Alocação Profissional Interna' WHERE name_bloc = 'Aloca????o Profissional Interna';
UPDATE public.leaf_bloc SET name_bloc = 'Analítica de Aprendizagem' WHERE name_bloc = 'Anal??tica de Aprendizagem';
UPDATE public.leaf_bloc SET name_bloc = 'Analítica de Cenários' WHERE name_bloc = 'Anal??tica de Cen??rios';
UPDATE public.leaf_bloc SET name_bloc = 'Analítica de Desenvolvimento Humano' WHERE name_bloc = 'Anal??tica de Desenvolvimento Humano';
UPDATE public.leaf_bloc SET name_bloc = 'Analítica de Gestão e Governança' WHERE name_bloc = 'Anal??tica de Gest??o e Governan??a';
UPDATE public.leaf_bloc SET name_bloc = 'Análise de Contexto' WHERE name_bloc = 'An??lise de Contexto';
UPDATE public.leaf_bloc SET name_bloc = 'Análise de Necessidades de Aprendizagem' WHERE name_bloc = 'An??lise de Necessidades de Aprendizagem';
UPDATE public.leaf_bloc SET name_bloc = 'Aplicação e Admissão' WHERE name_bloc = 'Aplica????o e Admiss??o';
UPDATE public.leaf_bloc SET name_bloc = 'Apoio e Aplicação em Vagas de Trabalho' WHERE name_bloc = 'Apoio e Aplica????o em Vagas de Trabalho';
UPDATE public.leaf_bloc SET name_bloc = 'Apoio e Retenção de Aprendizes' WHERE name_bloc = 'Apoio e Reten????o de Aprendizes';
UPDATE public.leaf_bloc SET name_bloc = 'Arrecadação de Fundos e Doação' WHERE name_bloc = 'Arrecada????o de Fundos e Doa????o';
UPDATE public.leaf_bloc SET name_bloc = 'Associações Profissionais e Industriais' WHERE name_bloc = 'Associa????es Profissionais e Industriais';
UPDATE public.leaf_bloc SET name_bloc = 'Avaliação de Projetos de Aprendizagem' WHERE name_bloc = 'Avalia????o de Projetos de Aprendizagem';
UPDATE public.leaf_bloc SET name_bloc = 'Avaliação Formativa' WHERE name_bloc = 'Avalia????o Formativa';
UPDATE public.leaf_bloc SET name_bloc = 'Captação e Parcerias B2B' WHERE name_bloc = 'Capta????o e Parcerias B2B';
UPDATE public.leaf_bloc SET name_bloc = 'Cenário Prospectivo' WHERE name_bloc = 'Cen??rio Prospectivo';
UPDATE public.leaf_bloc SET name_bloc = 'Competências de Tecnologia' WHERE name_bloc = 'Compet??ncias de Tecnologia';
UPDATE public.leaf_bloc SET name_bloc = 'Conteúdo Imersivo e Simulado' WHERE name_bloc = 'Conte??do Imersivo e Simulado';
UPDATE public.leaf_bloc SET name_bloc = 'Criação de Conteúdo Digital' WHERE name_bloc = 'Cria????o de Conte??do Digital';
UPDATE public.leaf_bloc SET name_bloc = 'Declaração e Matriz de P/O' WHERE name_bloc = 'Declara????o e Matriz de P/O';
UPDATE public.leaf_bloc SET name_bloc = 'Educação Continuada' WHERE name_bloc = 'Educa????o Continuada';
UPDATE public.leaf_bloc SET name_bloc = 'Elaboração de Projetos de Aprendizagem' WHERE name_bloc = 'Elabora????o de Projetos de Aprendizagem';
UPDATE public.leaf_bloc SET name_bloc = 'Empregabilidade e Construção de Competências' WHERE name_bloc = 'Empregabilidade e Constru????o de Compet??ncias';
UPDATE public.leaf_bloc SET name_bloc = 'Estratégia de Produtos e Serviços Digitais' WHERE name_bloc = 'Estrat??gia de Produtos e Servi??os Digitais';
UPDATE public.leaf_bloc SET name_bloc = 'Estratégias de Promoção de Eventos Educacionais' WHERE name_bloc = 'Estrat??gias de Promo????o de Eventos Educacionais';
UPDATE public.leaf_bloc SET name_bloc = 'Experiências de Aprendizagem Digital' WHERE name_bloc = 'Experi??ncias de Aprendizagem Digital';
UPDATE public.leaf_bloc SET name_bloc = 'Feedback de Avaliação' WHERE name_bloc = 'Feedback de Avalia????o';
UPDATE public.leaf_bloc SET name_bloc = 'Gerenciamento da Integração de Conteúdo' WHERE name_bloc = 'Gerenciamento da Integra????o de Conte??do';
UPDATE public.leaf_bloc SET name_bloc = 'Gerenciamento de Comunicação e Campanhas' WHERE name_bloc = 'Gerenciamento de Comunica????o e Campanhas';
UPDATE public.leaf_bloc SET name_bloc = 'Gerenciamento de Identidade e Autenticação' WHERE name_bloc = 'Gerenciamento de Identidade e Autentica????o';
UPDATE public.leaf_bloc SET name_bloc = 'Gerenciamento de Mídias Sociais e Comunidades' WHERE name_bloc = 'Gerenciamento de M??dias Sociais e Comunidades';
UPDATE public.leaf_bloc SET name_bloc = 'Implementação de Projetos de Aprendizagem' WHERE name_bloc = 'Implementa????o de Projetos de Aprendizagem';
UPDATE public.leaf_bloc SET name_bloc = 'Intercâmbios e Estágios' WHERE name_bloc = 'Interc??mbios e Est??gios';
UPDATE public.leaf_bloc SET name_bloc = 'Interoperabilidade e Padrões Abertos' WHERE name_bloc = 'Interoperabilidade e Padr??es Abertos';
UPDATE public.leaf_bloc SET name_bloc = 'Licenciamento de OER* e Conteúdos' WHERE name_bloc = 'Licenciamento de OER* e Conte??dos';
UPDATE public.leaf_bloc SET name_bloc = 'Liderança Estratégica Digital' WHERE name_bloc = 'Lideran??a Estrat??gica Digital';
UPDATE public.leaf_bloc SET name_bloc = 'Missão Digital' WHERE name_bloc = 'Miss??o Digital';
UPDATE public.leaf_bloc SET name_bloc = 'Novos Modelos de Negócios' WHERE name_bloc = 'Novos Modelos de Neg??cios';
UPDATE public.leaf_bloc SET name_bloc = 'Onboarding e Orientação' WHERE name_bloc = 'Onboarding e Orienta????o';
UPDATE public.leaf_bloc SET name_bloc = 'Pacote de Inovação Corporativa' WHERE name_bloc = 'Pacote de Inova????o Corporativa';
UPDATE public.leaf_bloc SET name_bloc = 'Padrões de Acessibilidade' WHERE name_bloc = 'Padr??es de Acessibilidade';
UPDATE public.leaf_bloc SET name_bloc = 'Padrões de Ciência de Dados e Big Data' WHERE name_bloc = 'Padr??es de Ci??ncia de Dados e Big Data';
UPDATE public.leaf_bloc SET name_bloc = 'Padrões de Dados e Tecnologia' WHERE name_bloc = 'Padr??es de Dados e Tecnologia';
UPDATE public.leaf_bloc SET name_bloc = 'Padrões de Desenvolvimento Ágil' WHERE name_bloc = 'Padr??es de Desenvolvimento ??gil';
UPDATE public.leaf_bloc SET name_bloc = 'Parcerias e Colaboração na Indústria' WHERE name_bloc = 'Parcerias e Colabora????o na Ind??stria';
UPDATE public.leaf_bloc SET name_bloc = 'Plano de Dívida Técnica' WHERE name_bloc = 'Plano de D??vida T??cnica';
UPDATE public.leaf_bloc SET name_bloc = 'Portal de Integração dos Aprendizes' WHERE name_bloc = 'Portal de Integra????o dos Aprendizes';
UPDATE public.leaf_bloc SET name_bloc = 'Programas Híbridos e On-Line' WHERE name_bloc = 'Programas H??bridos e On-Line';
UPDATE public.leaf_bloc SET name_bloc = 'Projetos e Simulação no Espaço de Trabalho' WHERE name_bloc = 'Projetos e Simula????o no Espa??o de Trabalho';
UPDATE public.leaf_bloc SET name_bloc = 'Redes de Mentoria na Indústria' WHERE name_bloc = 'Redes de Mentoria na Ind??stria';
UPDATE public.leaf_bloc SET name_bloc = 'Relatórios de Analítica' WHERE name_bloc = 'Relat??rios de Anal??tica';
UPDATE public.leaf_bloc SET name_bloc = 'Saúde e Bem-estar Mental' WHERE name_bloc = 'Sa??de e Bem-estar Mental';
UPDATE public.leaf_bloc SET name_bloc = 'Segurança e Redundância' WHERE name_bloc = 'Seguran??a e Redund??ncia';
UPDATE public.leaf_bloc SET name_bloc = 'Seleção de Programas e Eventos Educacionais' WHERE name_bloc = 'Sele????o de Programas e Eventos Educacionais';
UPDATE public.leaf_bloc SET name_bloc = 'Serviço de Planejamento de Carreira' WHERE name_bloc = 'Servi??o de Planejamento de Carreira';
UPDATE public.leaf_bloc SET name_bloc = 'Sistemas de Governança' WHERE name_bloc = 'Sistemas de Governan??a';
UPDATE public.leaf_bloc SET name_bloc = 'Teoria de Negócios' WHERE name_bloc = 'Teoria de Neg??cios';
UPDATE public.leaf_bloc SET name_bloc = 'Times de Inovação' WHERE name_bloc = 'Times de Inova????o';
UPDATE public.leaf_bloc SET name_bloc = 'Validação da Solução' WHERE name_bloc = 'Valida????o da Solu????o';
UPDATE public.leaf_bloc SET name_bloc = 'Validação de Problemas' WHERE name_bloc = 'Valida????o de Problemas';
UPDATE public.leaf_bloc SET name_bloc = 'Validação de Prontidão Digital' WHERE name_bloc = 'Valida????o de Prontid??o Digital';
UPDATE public.leaf_bloc SET name_bloc = 'Validação do Negócio' WHERE name_bloc = 'Valida????o do Neg??cio';
UPDATE public.leaf_bloc SET name_bloc = 'Validação do Produto' WHERE name_bloc = 'Valida????o do Produto';

COMMIT;
