-- SPIDER-PROMPT-010 — JPA runtime persistence and activation history

CREATE TABLE IF NOT EXISTS tb_governance_activation_history (
  history_id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  governance_scope         varchar(64)  NOT NULL,
  activation_sequence      bigint       NOT NULL,
  active_snapshot_id       varchar(120) NOT NULL,
  previous_snapshot_id     varchar(120),
  activated_at             timestamptz  NOT NULL,
  activated_by_principal   varchar(200) NOT NULL,
  reason_code              varchar(80)  NOT NULL,
  CONSTRAINT uq_tb_governance_activation_history_scope_sequence
    UNIQUE (governance_scope, activation_sequence)
);

ALTER TABLE tb_execution_governance_fixation
  ADD COLUMN IF NOT EXISTS governance_mode varchar(40);

ALTER TABLE tb_execution_governance_fixation
  ADD COLUMN IF NOT EXISTS governance_scope varchar(64);

ALTER TABLE tb_execution_governance_fixation
  ADD COLUMN IF NOT EXISTS snapshot_id varchar(120);

ALTER TABLE tb_execution_governance_fixation
  ADD COLUMN IF NOT EXISTS bundle_code varchar(120);

ALTER TABLE tb_execution_governance_fixation
  ADD COLUMN IF NOT EXISTS bundle_version varchar(40);

ALTER TABLE tb_execution_governance_fixation
  ADD COLUMN IF NOT EXISTS bundle_digest varchar(128);

ALTER TABLE tb_execution_governance_fixation
  ADD COLUMN IF NOT EXISTS snapshot_digest varchar(128);

ALTER TABLE tb_execution_governance_fixation
  ADD COLUMN IF NOT EXISTS activation_sequence bigint;

UPDATE tb_execution_governance_fixation
SET governance_mode = 'CONTROL_PLANE'
WHERE governance_mode IS NULL;

UPDATE tb_execution_governance_fixation
SET governance_scope = 'DEFAULT'
WHERE governance_scope IS NULL;

UPDATE tb_execution_governance_fixation
SET snapshot_id = governance_snapshot_id
WHERE snapshot_id IS NULL;

UPDATE tb_execution_governance_fixation
SET bundle_digest = governance_bundle_digest
WHERE bundle_digest IS NULL;

UPDATE tb_execution_governance_fixation
SET activation_sequence = governance_activation_sequence
WHERE activation_sequence IS NULL;

-- Legacy columns remain for rollback compatibility, but cannot stay mandatory once JPA writes
-- the expanded representation.
ALTER TABLE tb_execution_governance_fixation
  ALTER COLUMN governance_snapshot_id DROP NOT NULL;

ALTER TABLE tb_execution_governance_fixation
  ALTER COLUMN governance_bundle_ref DROP NOT NULL;

ALTER TABLE tb_execution_governance_fixation
  ALTER COLUMN governance_bundle_digest DROP NOT NULL;

ALTER TABLE tb_execution_governance_fixation
  ALTER COLUMN governance_activation_sequence DROP NOT NULL;
