package br.com.banco.spider.application.console;

public enum OperationalConsoleAction {
  LIST_EXECUTIONS,
  VIEW_EXECUTION_SUMMARY,
  VIEW_EXECUTION_TIMELINE,
  VIEW_OPERATIONAL_EVENTS,
  VIEW_SAFE_PROJECTIONS,
  VIEW_GOVERNANCE_REFERENCE,
  SUBMIT_MOCK_SCENARIO,
  VIEW_IMPLEMENTATION_STATUS,
  VIEW_PRESENTATION_READINESS,
  VIEW_OPERATIONAL_HEALTH,
  VIEW_FAILURE_LAB,
  EXECUTE_MOCK_FAILURE_SCENARIO,
  VIEW_FAILURE_LAB_EVIDENCE,
  VIEW_WORKER_RUNTIME,
  DRAIN_WORKER,
  VIEW_CAPACITY
}
