services:
  db:
    image: postgres:18
    container_name: leaction_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: leaction_hub
    ports:
      - "5433:5432"
    volumes:
      - ecosystem_postgres_data:/var/lib/postgresql
      - ./shared/database/init.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ../infra/ecosystem-databases.sql:/docker-entrypoint-initdb.d/02-ecosystem-databases.sql

volumes:
  ecosystem_postgres_data: