export const COMPONENTS = [
  {
    id: 'canonical-http',
    name: 'Entrada canônica HTTP',
    type: 'controller',
    responsibility: 'Expõe GET/POST /v1/canonical/executions. Não escolhe rota de negócio nem fabrica transação no frontend.',
    not: 'Não autentica sozinha em produção — o default é deny-all.',
    lane: 'origins',
    inputs: ['cliente HTTP', 'header X-Spider-Credential-Ref'],
    outputs: ['SubmitCanonicalExecutionUseCase'],
    related: ['submit-canonical', 'canonical-ingress-auth'],
    contracts: ['POST /v1/canonical/executions', 'GET /v1/canonical/executions/{id}'],
    methods: [
      {
        type: 'controller',
        signature: 'submit(request, credentialRef)',
        purpose: 'Recebe o envelope canônico e delega ao use case.',
        result: 'ExecutionSummary ou erro canônico',
        effects: 'dispara engine se autorizado',
        errors: '401/403/422 conforme ingress e validação',
        source: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/canonical/CanonicalExecutionHttpController.java',
      },
    ],
    persistence: 'nenhuma direta',
    config: ['spider.canonical.http.enabled'],
    errors: 'Credencial ausente ou rota inexistente',
    status: 'profile',
    profile: 'local-demo',
    evidence: [
      { kind: 'controller', path: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/canonical/CanonicalExecutionHttpController.java', label: 'CanonicalExecutionHttpController' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/integration/inbound/http/canonical/LocalDemoCanonicalHttpAccessTest.java', label: 'acesso local-demo' },
    ],
    aliases: ['canonical executions'],
  },
  {
    id: 'submit-canonical',
    name: 'SubmitCanonicalExecutionUseCase',
    type: 'serviço de aplicação',
    responsibility: 'Autoriza, fixa contexto de callback quando houver e entrega o pedido à engine.',
    not: 'Não interpreta intenção de satélite.',
    lane: 'engine',
    inputs: ['CanonicalExecutionHttpController'],
    outputs: ['canonical-engine'],
    related: ['canonical-engine', 'canonical-http'],
    contracts: ['SubmitCanonicalExecutionUseCase.execute'],
    methods: [
      {
        type: 'serviço de aplicação',
        signature: 'execute(command)',
        purpose: 'Orquestra autorização + engine.',
        result: 'Mono com resultado canônico',
        effects: 'pode criar execução persistida via ports',
        errors: 'autorização negada',
        source: 'backend/src/main/java/br/com/banco/spider/application/canonical/SubmitCanonicalExecutionUseCase.java',
      },
    ],
    persistence: 'via ports da engine',
    config: ['spider.canonical.*'],
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/application/canonical/SubmitCanonicalExecutionUseCase.java', label: 'SubmitCanonicalExecutionUseCase' },
    ],
    aliases: ['submit execution'],
  },
  {
    id: 'canonical-engine',
    name: 'Canonical Execution Engine',
    type: 'domínio',
    responsibility: 'Valida, resolve rota, materializa plano, executa steps e transita estados até terminal ou WAITING_EXTERNAL.',
    not: 'Não é o Monitor nem um satélite.',
    lane: 'engine',
    inputs: ['submit-canonical', 'capability-catalog', 'execution-plan-catalog'],
    outputs: ['provider-adapter', 'mock-universal-adapter', 'wait-signal', 'callback-outbox', 'operational-events', 'persistence-ports'],
    related: ['execution-plan-catalog', 'wait-signal'],
    contracts: ['CanonicalExecutionEngine', 'ExecutionState'],
    methods: [
      {
        type: 'domínio',
        signature: 'execute(request)',
        purpose: 'Percorre o ciclo RECEIVED→…→SUCCEEDED/FAILED/WAITING_EXTERNAL.',
        result: 'estado e resultado canônico',
        effects: 'transições, attempts, eventos',
        errors: 'validação, rota, falha de step, timeout',
        source: 'backend/src/main/java/br/com/banco/spider/execution/engine/DefaultCanonicalExecutionEngine.java',
      },
    ],
    states: 'RECEIVED, VALIDATED, RESOLVED, PLANNED, RUNNING, WAITING_EXTERNAL, COMPENSATING, SUCCEEDED, PARTIALLY_SUCCEEDED, COMPENSATED, FAILED, TIMED_OUT, REJECTED, CANCELLED',
    persistence: 'tb_execution_* quando mode=jpa; senão stores em memória',
    config: ['spider.canonical.persistence.mode'],
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/execution/engine/DefaultCanonicalExecutionEngine.java', label: 'DefaultCanonicalExecutionEngine' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/execution/runtime/ExecutionStateMachineTest.java', label: 'ExecutionStateMachineTest' },
    ],
    aliases: ['Execution Engine', 'ExecutionState'],
  },
  {
    id: 'canonical-ingress-auth',
    name: 'Ingress canônico',
    type: 'segurança',
    responsibility: 'Autentica o originador HTTP. Default DenyAll; LocalDemo permite local-demo-console.',
    not: 'Não autoriza satélites (eles usam headers próprios).',
    lane: 'contracts',
    inputs: ['canonical-http', 'signal-http', 'monitor-query'],
    outputs: ['use cases'],
    related: ['canonical-http'],
    contracts: ['CanonicalIngressAuthenticationPort'],
    methods: [
      {
        type: 'porta',
        signature: 'authenticate(credentialRef)',
        purpose: 'Aceitar ou recusar o header de credencial.',
        result: 'identidade ou anônimo',
        effects: 'nenhum persistente',
        errors: '401',
        source: 'backend/src/main/java/br/com/banco/spider/application/security/LocalDemoCanonicalCredentials.java',
      },
    ],
    persistence: 'nenhuma',
    config: ['spider.console.local-demo.enabled'],
    status: 'profile',
    profile: 'deny-all no runtime default; allowlist no local-demo',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/application/security/LocalDemoCanonicalCredentials.java', label: 'LocalDemoCanonicalCredentials' },
    ],
    aliases: ['X-Spider-Credential-Ref', 'deny-all'],
  },
  {
    id: 'satellite-http',
    name: 'Satellite Interaction HTTP',
    type: 'controller',
    responsibility: 'Recebe POST /v1/satellites/interactions no perfil local-demo.',
    not: 'Não executa capability no satélite EXPERIENCE.',
    lane: 'origins',
    inputs: ['SegSense BFF', 'SpiderBank BFF'],
    outputs: ['satellite-registry'],
    related: ['satellite-registry'],
    contracts: ['SAT 1.0/1.1/1.2'],
    methods: [
      {
        type: 'controller',
        signature: 'interact(headers, body)',
        purpose: 'Autenticar satélite e delegar ao serviço.',
        result: 'decisão SAT ou erro',
        effects: 'eventos SATELLITE_*',
        errors: '401/400/403/409',
        source: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/satellite/SatelliteInteractionHttpController.java',
      },
    ],
    persistence: 'idempotência em memória do serviço',
    config: ['spider.satellite.enabled', 'spider.satellite.loopback-only'],
    status: 'profile',
    profile: 'local-demo',
    evidence: [
      { kind: 'controller', path: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/satellite/SatelliteInteractionHttpController.java', label: 'SatelliteInteractionHttpController' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/integration/inbound/http/satellite/SatelliteInteractionHttpTest.java', label: 'SatelliteInteractionHttpTest' },
    ],
    aliases: ['SAT-003'],
  },
  {
    id: 'satellite-registry',
    name: 'Satellite Contract e registry',
    type: 'serviço de aplicação',
    responsibility: 'Valida envelope, contexto governado, objetivo permitido e regras determinísticas. SegSense pode ir a READY+provider; SpiderBank de crédito devolve PLAN_IMPEDED no plano existente.',
    not: 'O BFF não escolhe Intent/plano. A jornada completa de crédito (provider mock) permanece indisponível.',
    lane: 'contracts',
    inputs: ['satellite-http'],
    outputs: ['capability-catalog', 'provider-adapter', 'operational-events'],
    related: ['capability-catalog', 'provider-adapter'],
    contracts: ['SatelliteContractV1', 'SatelliteRegistry', 'DemoSliceRules'],
    methods: [
      {
        type: 'serviço de aplicação',
        signature: 'interact(authenticatedSatelliteId, request)',
        purpose: 'Validar, decidir e, se READY, despachar provider.',
        result: 'READY, PLAN_IMPEDED, MISSING_CONTEXT, AMBIGUOUS, REJECTED…',
        effects: 'eventos; idempotência; sem provider no diagnóstico de crédito',
        errors: 'UNAUTHORIZED_SATELLITE, INVALID_PAYLOAD, IDEMPOTENCY_CONFLICT',
        source: 'backend/src/main/java/br/com/banco/spider/satellite/application/SatelliteInteractionService.java',
      },
    ],
    persistence: 'contexto em memória do serviço; events no store operacional',
    config: ['spider.satellite.registry.segsense', 'spider.satellite.registry.spiderbank'],
    status: 'profile',
    profile: 'local-demo. SpiderBank: SAT-003 de diagnóstico comprovado; Simulação continua unavailable.',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/satellite/application/SatelliteInteractionService.java', label: 'SatelliteInteractionService' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/satellite/SpiderBankSatelliteContractTest.java', label: 'SpiderBankSatelliteContractTest' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/satellite/SatelliteContractV1Test.java', label: 'regressão SegSense' },
    ],
    aliases: ['segsense', 'spiderbank', 'WORKING_CAPITAL_ASSESSMENT'],
  },
  {
    id: 'signal-http',
    name: 'Sinal HTTP',
    type: 'controller',
    responsibility: 'Recebe POST /v1/canonical/signals para retomar espera.',
    not: 'Não cria execução nova.',
    lane: 'origins',
    inputs: ['cliente de sinal'],
    outputs: ['wait-signal'],
    related: ['wait-signal'],
    contracts: ['POST /v1/canonical/signals'],
    methods: [
      {
        type: 'controller',
        signature: 'submit(signal, credentialRef)',
        purpose: 'Ingress de sinal externo.',
        result: 'aceite ou erro',
        effects: 'inbox ou apply',
        errors: 'SIGNAL_UNAUTHORIZED',
        source: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/canonical/CanonicalSignalHttpController.java',
      },
    ],
    persistence: 'tb_inbox_message ou store em memória',
    config: ['spider.signal-http.enabled'],
    status: 'profile',
    profile: 'local-demo',
    evidence: [
      { kind: 'controller', path: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/canonical/CanonicalSignalHttpController.java', label: 'CanonicalSignalHttpController' },
    ],
    aliases: ['signals'],
  },
  {
    id: 'context-http',
    name: 'Context Intelligence HTTP',
    type: 'controller',
    responsibility: 'Expõe intents, interpretações e execuções de contexto.',
    not: 'Não implica que IA foi usada.',
    lane: 'origins',
    inputs: ['cliente de contexto'],
    outputs: ['context-intelligence'],
    related: ['context-intelligence'],
    contracts: ['/v1/context/*'],
    methods: [
      {
        type: 'controller',
        signature: 'interpret / resolve / execute',
        purpose: 'Entrada HTTP da fatia de contexto.',
        result: 'intent/plano/execução',
        effects: 'pode submeter execução canônica',
        errors: 'flag desligada',
        source: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/context/ContextIntelligenceHttpController.java',
      },
    ],
    persistence: 'indireta via engine',
    config: ['spider.context.enabled'],
    status: 'profile',
    profile: 'default off; local-demo on',
    evidence: [
      { kind: 'controller', path: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/context/ContextIntelligenceHttpController.java', label: 'ContextIntelligenceHttpController' },
    ],
    aliases: ['context intelligence'],
  },
  {
    id: 'context-intelligence',
    name: 'Context Intelligence',
    type: 'serviço de aplicação',
    responsibility: 'Catálogo de intents, policy/router e planning determinístico. Pode acionar interpretação.',
    not: 'Não é agente conversacional.',
    lane: 'context',
    inputs: ['context-http', 'contextual-link'],
    outputs: ['context-ai', 'submit-canonical', 'execution-plan-catalog'],
    related: ['context-ai', 'execution-plan-catalog'],
    contracts: ['StaticBusinessIntentCatalog', 'StaticExecutionPlanCatalog'],
    methods: [
      {
        type: 'serviço de aplicação',
        signature: 'interpret / plan',
        purpose: 'Estruturar intenção e selecionar plano existente.',
        result: 'intent + planType (ex. WORKING_CAPITAL_DIAGNOSTIC_V1)',
        effects: 'opcionalmente submete execução',
        errors: 'ambiguidade / policy',
        source: 'backend/src/main/java/br/com/banco/spider/context/planning/StaticExecutionPlanCatalog.java',
      },
    ],
    persistence: 'nenhuma própria',
    config: ['spider.context.enabled'],
    status: 'partial',
    profile: 'Catálogos estáticos comprovados; UI de contexto só com flag.',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/context/planning/StaticExecutionPlanCatalog.java', label: 'StaticExecutionPlanCatalog' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/context/ContextExecutionPlanningTest.java', label: 'ContextExecutionPlanningTest' },
    ],
    aliases: ['SEEK_WORKING_CAPITAL', 'intent catalog'],
  },
  {
    id: 'context-ai',
    name: 'ContextInterpretationProvider',
    type: 'adapter',
    responsibility: 'Interpretação opcional (scripted ou Bedrock). Default-off.',
    not: 'Não é composer de resposta nem agente. Sem evidência, o Monitor registra aiUsage=NOT_USED.',
    lane: 'context',
    inputs: ['context-intelligence'],
    outputs: ['intent estruturado'],
    related: ['context-intelligence'],
    contracts: ['ContextInterpretationProvider'],
    methods: [
      {
        type: 'adapter',
        signature: 'interpret(text, options)',
        purpose: 'Devolver intent/entidades sem escolher executor.',
        result: 'interpretação estruturada',
        effects: 'nenhum persistente obrigatório',
        errors: 'provider indisponível',
        source: 'backend/src/main/java/br/com/banco/spider/integration/outbound/ai/ScriptedContextInterpretationProvider.java',
      },
    ],
    persistence: 'nenhuma',
    config: ['spider.context.ai.enabled', 'spider.context.ai.provider', 'spider.context.ai.scripted-enabled'],
    status: 'profile',
    profile: 'enabled=false no application.yml; local-demo pode usar scripted',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/integration/outbound/ai/ScriptedContextInterpretationProvider.java', label: 'ScriptedContextInterpretationProvider' },
      { kind: 'config', path: 'backend/src/main/resources/application.yml', label: 'AI default-off' },
    ],
    aliases: ['IA', 'Bedrock', 'scripted'],
  },
  {
    id: 'capability-catalog',
    name: 'Catálogo de capabilities',
    type: 'domínio',
    responsibility: 'Declara capabilities e disponibilidade. SIMULATE_WORKING_CAPITAL permanece NOT_AVAILABLE.',
    not: 'Não executa sistemas. Não marca crédito como AVAILABLE nesta entrega.',
    lane: 'catalog',
    inputs: ['satellite-registry', 'canonical-engine'],
    outputs: ['resolução de rota'],
    related: ['execution-plan-catalog', 'provider-adapter'],
    contracts: ['StaticBusinessCapabilityCatalog', 'BusinessCapability'],
    methods: [
      {
        type: 'domínio',
        signature: 'findById(capabilityId)',
        purpose: 'Consultar disponibilidade e rotas elegíveis.',
        result: 'AVAILABLE ou NOT_AVAILABLE',
        effects: 'nenhum',
        errors: 'ausente no catálogo',
        source: 'backend/src/main/java/br/com/banco/spider/context/capability/StaticBusinessCapabilityCatalog.java',
      },
    ],
    persistence: 'nenhuma',
    config: 'catálogo estático',
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/context/capability/StaticBusinessCapabilityCatalog.java', label: 'StaticBusinessCapabilityCatalog' },
    ],
    aliases: ['IDENTIFY_CUSTOMER', 'SIMULATE_WORKING_CAPITAL'],
  },
  {
    id: 'execution-plan-catalog',
    name: 'Catálogo de Execution Plan',
    type: 'domínio',
    responsibility: 'Compõe intents em steps obrigatórios. WORKING_CAPITAL_DIAGNOSTIC_V1 tem sete passos.',
    not: 'Não cria plano paralelo para evitar pré-requisitos.',
    lane: 'catalog',
    inputs: ['context-intelligence', 'satellite-registry'],
    outputs: ['canonical-engine'],
    related: ['capability-catalog'],
    contracts: ['StaticExecutionPlanCatalog'],
    methods: [
      {
        type: 'domínio',
        signature: 'findByIntent(intent)',
        purpose: 'Selecionar o template existente.',
        result: 'planType + steps',
        effects: 'nenhum',
        errors: 'intent sem plano',
        source: 'backend/src/main/java/br/com/banco/spider/context/planning/StaticExecutionPlanCatalog.java',
      },
    ],
    persistence: 'nenhuma no catálogo; plano materializado na execução',
    config: 'estático',
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/context/planning/StaticExecutionPlanCatalog.java', label: 'StaticExecutionPlanCatalog' },
    ],
    aliases: ['WORKING_CAPITAL_DIAGNOSTIC_V1', 'Execution Plan'],
  },
  {
    id: 'provider-adapter',
    name: 'HttpProviderCapabilityAdapter',
    type: 'adapter',
    responsibility: 'Chama o provider resolvido após READY. No local-demo, insurance-provider-mock.',
    not: 'Não chama :8096 nem credit-provider-mock. SpiderBank diagnóstico não despacha provider.',
    lane: 'adapters',
    inputs: ['satellite-registry', 'canonical-engine'],
    outputs: ['insurance-provider-mock'],
    related: ['satellite-registry'],
    contracts: ['ProviderCapabilityPort'],
    methods: [
      {
        type: 'adapter',
        signature: 'execute(ExecutionRequest)',
        purpose: 'Despachar capability ao base-url do provider.',
        result: 'ExecutionResult available/unavailable',
        effects: 'PROVIDER_RESULT_RECEIVED',
        errors: 'timeout / HTTP não 200',
        source: 'backend/src/main/java/br/com/banco/spider/integration/outbound/provider/HttpProviderCapabilityAdapter.java',
      },
    ],
    persistence: 'nenhuma',
    config: ['spider.satellite.providers.insurance-provider-mock.base-url', 'timeout'],
    status: 'profile',
    profile: 'mock local-demo',
    evidence: [
      { kind: 'adapter', path: 'backend/src/main/java/br/com/banco/spider/integration/outbound/provider/HttpProviderCapabilityAdapter.java', label: 'HttpProviderCapabilityAdapter' },
    ],
    aliases: ['provider', 'insurance-provider-mock'],
  },
  {
    id: 'mock-universal-adapter',
    name: 'Mock Universal Adapter',
    type: 'adapter',
    responsibility: 'Executa cenários canônicos de demonstração (retry, wait, fail, callback).',
    not: 'Não é sistema bancário real. Não integra crédito.',
    lane: 'adapters',
    inputs: ['canonical-engine'],
    outputs: ['resultado de cenário'],
    related: ['canonical-engine'],
    contracts: ['UniversalAdapterPort'],
    methods: [
      {
        type: 'adapter',
        signature: 'execute(binding, operation)',
        purpose: 'Simular o executor da rota mock.',
        result: 'sucesso/falha/wait conforme cenário',
        effects: 'attempts na engine',
        errors: 'cenário FAIL',
        source: 'backend/src/main/java/br/com/banco/spider/integration/mock/MockUniversalAdapter.java',
      },
    ],
    persistence: 'nenhuma própria',
    config: 'adapter mock enabled no YAML',
    status: 'profile',
    profile: 'mock / local-demo',
    evidence: [
      { kind: 'adapter', path: 'backend/src/main/java/br/com/banco/spider/integration/mock/MockUniversalAdapter.java', label: 'MockUniversalAdapter' },
    ],
    aliases: ['mock-universal'],
  },
  {
    id: 'wait-signal',
    name: 'Wait, inbox e resume',
    type: 'domínio',
    responsibility: 'Criar espera, guardar sinal e retomar execução.',
    not: 'Não é callback outbox.',
    lane: 'async',
    inputs: ['canonical-engine', 'signal-http', 'worker-runtime'],
    outputs: ['canonical-engine'],
    related: ['worker-runtime'],
    contracts: ['ExecutionWaitStorePort', 'InboxStorePort'],
    methods: [
      {
        type: 'domínio',
        signature: 'create wait / apply pending / expire',
        purpose: 'Ciclo WAITING → RESUMED/EXPIRED.',
        result: 'estado de wait',
        effects: 'tb_execution_wait / tb_inbox_message ou memória',
        errors: 'sinal não autorizado, expiry',
        source: 'backend/src/main/java/br/com/banco/spider/execution/wait/WaitExpiryProcessor.java',
      },
    ],
    states: 'WAITING, SIGNALLED, EXPIRING, RESUMING, RESUMED, EXPIRED',
    persistence: 'tb_execution_wait, tb_inbox_message',
    config: ['spider.worker-runtime.enabled'],
    status: 'implemented',
    evidence: [
      { kind: 'migration', path: 'database/migrations/V20260821c__tb_execution_wait_inbox.sql', label: 'wait/inbox SQL' },
    ],
    aliases: ['WAIT_EXPIRY', 'SIGNAL_APPLICATION'],
  },
  {
    id: 'callback-outbox',
    name: 'Callback outbox',
    type: 'domínio',
    responsibility: 'Criar e entregar callbacks de forma assíncrona.',
    not: 'Não é Reconciliation Workbench.',
    lane: 'async',
    inputs: ['canonical-engine', 'worker-runtime'],
    outputs: ['callback-reconciliation'],
    related: ['callback-reconciliation', 'worker-runtime'],
    contracts: ['CallbackOutboxStorePort', 'CallbackDeliveryPort'],
    methods: [
      {
        type: 'domínio',
        signature: 'process outbox batch',
        purpose: 'Entregar due list com lease.',
        result: 'DELIVERED/FAILED/retry',
        effects: 'tb_callback_outbox, tb_callback_delivery_attempt',
        errors: 'adapter indisponível',
        source: 'backend/src/main/java/br/com/banco/spider/execution/callback/CallbackOutboxProcessor.java',
      },
    ],
    persistence: 'tb_callback_outbox, tb_callback_delivery_attempt, tb_execution_callback_context',
    config: ['spider.callback.reconciliation'],
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/execution/callback/CallbackOutboxProcessor.java', label: 'CallbackOutboxProcessor' },
      { kind: 'migration', path: 'database/migrations/V20260821e__tb_callback_outbox.sql', label: 'V20260821e' },
    ],
    aliases: ['outbox'],
  },
  {
    id: 'callback-reconciliation',
    name: 'Reconciliação operacional de callback',
    type: 'serviço de aplicação',
    responsibility: 'Worker e use case interno processam due list (query de status / redelivery). ReconcileCallbackNowUseCase não tem controller HTTP e é deny-by-default.',
    not: 'Não é o Reconciliation Workbench (CAP-021 não iniciado).',
    lane: 'async',
    inputs: ['callback-outbox', 'worker-runtime'],
    outputs: ['outbox / revisão'],
    related: ['callback-outbox'],
    contracts: ['CallbackReconciliationProcessor', 'ReconcileCallbackNowUseCase'],
    methods: [
      {
        type: 'serviço de aplicação',
        signature: 'execute(Command actorRef, reasonCode, workerId, batchSize)',
        purpose: 'Autorizar callback.reconcile e processar até 100 itens due.',
        result: 'Outcome(decision, batch)',
        effects: 'tb_callback_reconciliation*',
        errors: 'DENIED sem permissão',
        source: 'backend/src/main/java/br/com/banco/spider/application/canonical/ReconcileCallbackNowUseCase.java',
      },
    ],
    persistence: 'tb_callback_reconciliation, tb_callback_reconciliation_attempt',
    config: ['spider.callback.reconciliation'],
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/application/canonical/ReconcileCallbackNowUseCase.java', label: 'ReconcileCallbackNowUseCase' },
      { kind: 'migration', path: 'database/migrations/V20260821f__tb_callback_reconciliation.sql', label: 'V20260821f' },
    ],
    aliases: ['ReconcileCallbackNowUseCase', 'CALLBACK_RECONCILIATION'],
  },
  {
    id: 'worker-runtime',
    name: 'Worker runtime',
    type: 'infraestrutura',
    responsibility: 'SmartLifecycle com catálogo fechado de WorkerType, lease e fencing.',
    not: 'Não substitui o Monitor.',
    lane: 'workers',
    inputs: ['schedules duráveis'],
    outputs: ['wait-signal', 'callback-outbox', 'callback-reconciliation'],
    related: ['capacity-admission'],
    contracts: ['WorkerRuntimeCoordinator', 'WorkerType'],
    methods: [
      {
        type: 'infraestrutura',
        signature: 'tick / claim / drain',
        purpose: 'Executar handlers SIGNAL, WAIT, CALLBACK_*, RECOVERY, envelope.',
        result: 'progresso de backlog',
        effects: 'tb_runtime_worker_instance / tb_runtime_schedule ou memória',
        errors: 'contention de fencing',
        source: 'backend/src/main/java/br/com/banco/spider/operational/workers/WorkerRuntimeCoordinator.java',
      },
    ],
    persistence: 'tb_runtime_worker_instance, tb_runtime_schedule',
    config: ['spider.worker-runtime.enabled', 'leaseDuration', 'max-concurrency'],
    status: 'profile',
    profile: 'default off; local-demo on',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/operational/workers/WorkerRuntimeCoordinator.java', label: 'WorkerRuntimeCoordinator' },
      { kind: 'migration', path: 'database/migrations/V20260825c__durable_worker_runtime.sql', label: 'V20260825c' },
    ],
    aliases: ['workers', 'lease'],
  },
  {
    id: 'capacity-admission',
    name: 'Capacidade e bulkheads',
    type: 'infraestrutura',
    responsibility: 'Admissão e isolamento de concorrência (Resilience4j).',
    not: 'Não é o catálogo de capabilities de negócio.',
    lane: 'workers',
    inputs: ['pedidos admitidos'],
    outputs: ['decisões de pressão'],
    related: ['worker-runtime'],
    contracts: ['CapacityAdmissionService'],
    methods: [
      {
        type: 'infraestrutura',
        signature: 'admit(operation)',
        purpose: 'Aceitar ou rejeitar carga.',
        result: 'admitido/rejeitado',
        effects: 'métricas de capacity',
        errors: 'bulkhead cheio',
        source: 'backend/src/main/java/br/com/banco/spider/operational/capacity/CapacityAdmissionService.java',
      },
    ],
    persistence: 'nenhuma de negócio',
    config: ['spider.capacity.enabled'],
    status: 'profile',
    profile: 'local-demo com enforcement',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/operational/capacity/CapacityAdmissionService.java', label: 'CapacityAdmissionService' },
    ],
    aliases: ['bulkhead', 'resilience4j'],
  },
  {
    id: 'replay-guard',
    name: 'Replay guard',
    type: 'segurança',
    responsibility: 'Reservar nonce/fingerprint para impedir replay.',
    not: 'Não autentica satélite.',
    lane: 'contracts',
    inputs: ['envelopes protegidos'],
    outputs: ['aceitação/rejeição'],
    related: ['wait-signal'],
    contracts: ['ReplayGuardPort'],
    methods: [
      {
        type: 'segurança',
        signature: 'reserve(scope, nonce, fingerprint)',
        purpose: 'Garantir unicidade do envelope.',
        result: 'reservado ou conflito',
        effects: 'tb_security_replay_guard',
        errors: 'replay',
        source: 'backend/src/main/java/br/com/banco/spider/security/integrity/IntegrityProfileDefinition.java',
      },
    ],
    persistence: 'tb_security_replay_guard',
    config: 'perfis de integridade',
    status: 'implemented',
    evidence: [
      { kind: 'migration', path: 'database/migrations/V20260821g__tb_security_replay_guard.sql', label: 'V20260821g' },
    ],
    aliases: ['nonce', 'HMAC'],
  },
  {
    id: 'persistence-ports',
    name: 'Ports de persistência',
    type: 'persistência',
    responsibility: 'Interfaces de store com adapters memory (default) e JPA (mode=jpa).',
    not: 'Flyway não aplica as migrations automaticamente.',
    lane: 'persistence',
    inputs: ['canonical-engine', 'operational-events', 'worker-runtime'],
    outputs: ['PostgreSQL / H2 / memória'],
    related: ['canonical-engine'],
    contracts: ['ExecutionControlStorePort e correlatas'],
    methods: [
      {
        type: 'porta',
        signature: 'save / find / claim',
        purpose: 'Abstrair memória vs JPA.',
        result: 'agregados persistidos',
        effects: 'tabelas quando JPA',
        errors: 'validação Hibernate no default Postgres',
        source: 'backend/src/main/java/br/com/banco/spider/execution/persistence/port/ExecutionControlStorePort.java',
      },
    ],
    persistence: 'ver esquema PostgreSQL',
    config: ['spider.canonical.persistence.mode'],
    status: 'partial',
    profile: 'mode=memory no default e no local-demo; adapters JPA existem',
    evidence: [
      { kind: 'interface', path: 'backend/src/main/java/br/com/banco/spider/execution/persistence/port/ExecutionControlStorePort.java', label: 'ExecutionControlStorePort' },
      { kind: 'config', path: 'backend/src/main/resources/application.yml', label: 'persistence.mode' },
    ],
    aliases: ['JPA', 'InMemory', 'PostgreSQL'],
  },
  {
    id: 'operational-events',
    name: 'Operational Event Store',
    type: 'persistência',
    responsibility: 'Persistir eventos com redaction. Telemetry pode estar off (no-op).',
    not: 'Não é log de secrets. Não reconstitui payload de negócio.',
    lane: 'observe',
    inputs: ['engine', 'satélite', 'workers'],
    outputs: ['monitor-query'],
    related: ['monitor-query'],
    contracts: ['OperationalEventStorePort', 'OperationalEventType'],
    methods: [
      {
        type: 'persistência',
        signature: 'append / findRecent',
        purpose: 'Guardar fatos operacionais.',
        result: 'eventos',
        effects: 'tb_operational_event ou memória',
        errors: 'store indisponível → Monitor available=false',
        source: 'backend/src/main/java/br/com/banco/spider/operational/events/OperationalEventType.java',
      },
    ],
    persistence: 'tb_operational_event',
    config: ['spider.telemetry.enabled'],
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/operational/events/OperationalEventType.java', label: 'OperationalEventType' },
      { kind: 'migration', path: 'database/migrations/V20260825__tb_operational_event.sql', label: 'V20260825' },
    ],
    aliases: ['telemetry', 'eventos'],
  },
  {
    id: 'monitor-query',
    name: 'Monitor (read model)',
    type: 'read model',
    responsibility: 'Projetar recorte de eventos, execuções e readiness da Simulação. Identidades vêm só do backend.',
    not: 'Não fabrica transação no frontend. Card SpiderBank permanece unavailable.',
    lane: 'observe',
    inputs: ['operational-events'],
    outputs: ['frontend Monitor / Simulação'],
    related: ['operational-events'],
    contracts: ['GET /v1/console/monitor/events', 'GET /v1/console/monitor/simulation'],
    methods: [
      {
        type: 'read model',
        signature: 'monitorEvents() / simulationReadiness()',
        purpose: 'Ler recorte (24h, até 2000) e satélites.',
        result: 'items + truncated; satellites[].available',
        effects: 'somente leitura',
        errors: 'store down',
        source: 'backend/src/main/java/br/com/banco/spider/application/console/OperationalConsoleQueryService.java',
      },
    ],
    persistence: 'leitura do event store / execuções',
    config: ['spider.console.http.enabled'],
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/application/console/OperationalConsoleQueryService.java', label: 'OperationalConsoleQueryService' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/application/console/MonitorEventsTest.java', label: 'MonitorEventsTest' },
    ],
    aliases: ['Monitor', 'Simulação', 'read model'],
  },
  {
    id: 'contextual-link',
    name: 'Gateway contextual legado',
    type: 'controller',
    responsibility: 'GET /go redireciona para /spiderbank?ctx=. Endpoints /v1/demo/spiderbank/* permanecem.',
    not: 'Não substitui SAT-003. Não é o frontend do satélite SpiderBank em :5190.',
    lane: 'origins',
    inputs: ['páginas parceiras'],
    outputs: ['superfície /spiderbank do Monitor'],
    related: ['context-intelligence'],
    contracts: ['GET /go', 'GET /v1/demo/spiderbank/entry', 'POST /v1/demo/spiderbank/understand'],
    methods: [
      {
        type: 'controller',
        signature: 'go / entry / understand',
        purpose: 'Aquisição editorial e entry legado.',
        result: 'redirect ou projeção',
        effects: 'contexto opaco',
        errors: 'ctx inválido',
        source: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/contextuallink/ContextualLinkGatewayController.java',
      },
    ],
    persistence: 'sessão de link conforme serviço',
    config: ['spider.demo.spiderbank-entry-url'],
    status: 'implemented',
    evidence: [
      { kind: 'controller', path: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/contextuallink/ContextualLinkGatewayController.java', label: 'ContextualLinkGatewayController' },
    ],
    aliases: ['/go', 'CampoAberto'],
  },
];
