export const ENVIRONMENT = {
  note:
    'Versões requeridas vêm de pom.xml, BOM, package.json/lockfile e imagens. Versões observadas foram lidas neste ambiente de validação em 2026-09-18. Valores de senha, tokens e URLs com credencial não são documentados.',
  backend: [
    { id: 'java', name: 'Java', required: '21', observed: '21.0.12 (Microsoft OpenJDK)', source: 'backend/pom.xml <java.version>; comando java -version', role: 'linguagem do Control Plane' },
    { id: 'maven', name: 'Apache Maven', required: '3.9.x via .tools (sem Maven Wrapper)', observed: '3.9.16 em spider/.tools/apache-maven-3.9.16', source: 'spider/.tools/apache-maven-3.9.16; ausência de .mvn/wrapper', role: 'build do backend' },
    { id: 'spring-boot', name: 'Spring Boot', required: '3.4.2', observed: '3.4.2 (parent)', source: 'backend/pom.xml spring-boot-starter-parent', role: 'runtime reativo + JPA + actuator' },
    { id: 'webflux', name: 'spring-boot-starter-webflux', required: 'BOM 3.4.2', observed: 'via parent', source: 'backend/pom.xml', role: 'HTTP reativo' },
    { id: 'jpa', name: 'spring-boot-starter-data-jpa', required: 'BOM 3.4.2', observed: 'via parent', source: 'backend/pom.xml', role: 'mapeamento JPA quando persistence.mode=jpa' },
    { id: 'postgres-driver', name: 'PostgreSQL JDBC', required: 'BOM 3.4.2', observed: 'via parent, scope runtime', source: 'backend/pom.xml artifact postgresql', role: 'driver JDBC' },
    { id: 'h2', name: 'H2', required: 'BOM 3.4.2', observed: 'via parent, scope runtime', source: 'backend/pom.xml', role: 'somente perfil local-demo (mem MODE=PostgreSQL)' },
    { id: 'validation', name: 'spring-boot-starter-validation', required: 'BOM 3.4.2', observed: 'via parent', source: 'backend/pom.xml', role: 'validação de entrada' },
    { id: 'actuator', name: 'spring-boot-starter-actuator', required: 'BOM 3.4.2', observed: 'via parent', source: 'backend/pom.xml', role: 'health/info/metrics' },
    { id: 'resilience4j', name: 'Resilience4j', required: '2.2.0', observed: '2.2.0', source: 'backend/pom.xml resilience4j-spring-boot3 / resilience4j-reactor', role: 'circuit/bulkhead no capacity' },
    { id: 'bedrock', name: 'AWS Bedrock Runtime SDK', required: '2.30.38', observed: '2.30.38', source: 'backend/pom.xml aws.sdk.version', role: 'provider de interpretação; só se spider.context.ai.enabled' },
    { id: 'jjwt', name: 'JJWT', required: '0.12.6', observed: '0.12.6', source: 'backend/pom.xml jjwt.version', role: 'JWS' },
    { id: 'springdoc', name: 'springdoc-openapi webflux', required: '2.8.4', observed: '2.8.4', source: 'backend/pom.xml springdoc.version', role: '/api-docs e swagger-ui' },
    { id: 'json-schema', name: 'networknt json-schema-validator', required: '1.5.4', observed: '1.5.4', source: 'backend/pom.xml', role: 'validação de contratos SAT/canônicos' },
    { id: 'lombok', name: 'Lombok', required: 'BOM 3.4.2', observed: 'via parent, optional', source: 'backend/pom.xml', role: 'geração de código de compilação' },
    { id: 'flyway', name: 'Flyway', required: 'não é dependência', observed: 'não amarrado ao Spring', source: 'backend/pom.xml (ausente); database/migrations/README.md', role: 'migrations SQL manuais / init.sql' },
    { id: 'test-spring', name: 'spring-boot-starter-test', required: 'BOM 3.4.2', observed: 'via parent, scope test', source: 'backend/pom.xml', role: 'testes de backend' },
    { id: 'reactor-test', name: 'reactor-test', required: 'BOM 3.4.2', observed: 'via parent, scope test', source: 'backend/pom.xml', role: 'testes reativos' },
  ],
  frontend: [
    { id: 'node', name: 'Node.js', required: 'Vite 6: ^18 || ^20 || >=22 (não há engines em package.json)', observed: 'v24.14.0', source: 'frontend/package-lock.json engines do vite; comando node -v', role: 'runtime do Monitor' },
    { id: 'npm', name: 'npm', required: 'lockfileVersion 3', observed: '11.9.0', source: 'frontend/package-lock.json; comando npm -v', role: 'instalação' },
    { id: 'react', name: 'React', required: '^19.0.0 (package.json)', observed: '19.2.8', source: 'frontend/package.json; frontend/package-lock.json node_modules/react', role: 'UI do Monitor' },
    { id: 'react-dom', name: 'react-dom', required: '^19.0.0', observed: '19.2.8', source: 'frontend/package-lock.json', role: 'renderer' },
    { id: 'vite', name: 'Vite', required: '^6.1.0', observed: '6.4.3', source: 'frontend/package.json; package-lock.json node_modules/vite', role: 'dev server :5180 e build' },
    { id: 'vitest', name: 'Vitest', required: '^3.0.5', observed: '3.2.7', source: 'frontend/package-lock.json node_modules/vitest', role: 'testes do frontend' },
    { id: 'testing-library', name: 'Testing Library React', required: '^16.2.0', observed: '16.2.0 (range)', source: 'frontend/package.json', role: 'testes de UI' },
    { id: 'jest-dom', name: '@testing-library/jest-dom', required: '^6.6.3', observed: '6.6.3 (range)', source: 'frontend/package.json', role: 'asserções DOM' },
    { id: 'jsdom', name: 'jsdom', required: '^26.0.0', observed: 'range ^26.0.0', source: 'frontend/package.json', role: 'ambiente de teste' },
    { id: 'eslint', name: 'ESLint', required: '10.9.1', observed: '10.9.1', source: 'frontend/package.json pin', role: 'lint src e scripts' },
    { id: 'playwright', name: 'Playwright', required: '^1.62.1', observed: 'range ^1.62.1', source: 'frontend/package.json', role: 'capturas/e2e opcionais; não é runtime do Monitor' },
  ],
  infra: [
    { id: 'postgres-image', name: 'PostgreSQL (compose)', required: 'postgres:16-alpine', observed: 'imagem declarada; instância não inspecionada nesta documentação', source: 'docker-compose.yml', role: 'store técnico; init via database/init.sql' },
    { id: 'postgres-app', name: 'JDBC alvo default', required: 'localhost:5432 / spider_orchestrator', observed: 'configurado em application.yml', source: 'backend/src/main/resources/application.yml spring.datasource.url', role: 'quando o app não está em local-demo' },
    { id: 'engine-port', name: 'Engine HTTP', required: '8080', observed: '8080', source: 'application.yml server.port', role: 'Control Plane' },
    { id: 'monitor-port', name: 'Monitor (Vite)', required: '5180', observed: '5180', source: 'frontend/vite.config.js server.port', role: 'frontend da Spider' },
    { id: 'actuator-health', name: 'Actuator health', required: '/actuator/health,info,metrics', observed: 'expostos', source: 'application.yml management.endpoints', role: 'prontidão do processo, não prova de jornada' },
    { id: 'swagger', name: 'OpenAPI', required: '/api-docs e /swagger-ui.html', observed: 'configurado', source: 'application.yml springdoc', role: 'descoberta local' },
  ],
  ports: [
    { port: '8080', service: 'Spider engine', profile: 'todos os perfis do backend', source: 'application.yml' },
    { port: '5180', service: 'Monitor Vite', profile: 'desenvolvimento frontend', source: 'vite.config.js' },
    { port: '5432', service: 'PostgreSQL compose', profile: 'infra local; não usado pelo process local-demo (H2)', source: 'docker-compose.yml' },
    { port: '5178', service: 'SegSense frontend', profile: 'satélite; não é a Spider', source: 'segsense (fora do runtime default da engine)' },
    { port: '8088', service: 'SegSense BFF', profile: 'satélite', source: 'segsense' },
    { port: '8095', service: 'mock de seguro', profile: 'mock / teste', source: 'segsense-provider-mock' },
    { port: '5190', service: 'SpiderBank frontend', profile: 'satélite; jornada completa ainda pendente', source: 'spider-bank' },
    { port: '8090', service: 'SpiderBank BFF', profile: 'satélite', source: 'spider-bank' },
    { port: '8081', service: 'proxy Vite /originador', profile: 'dev frontend', source: 'vite.config.js' },
  ],
  variables: [
    { name: 'SPRING_PROFILES_ACTIVE', purpose: 'Ativa local-demo ou outros perfis. Sem valor, vale application.yml.' },
    { name: 'SPIDER_CONTEXT_AI_ENABLED', purpose: 'Liga o provider de interpretação. application.yml default false; no profile local-demo o fallback do placeholder é true.' },
    { name: 'SPIDER_CONTEXT_AI_PROVIDER', purpose: 'scripted ou bedrock. Não implica agente.' },
    { name: 'SPIDER_CONTEXT_AI_MODEL', purpose: 'Identificador do modelo Bedrock quando o provider for bedrock.' },
    { name: 'SPIDER_CONTEXT_AI_SCRIPTED_ENABLED', purpose: 'Permite o provider scripted de demo.' },
    { name: 'AWS_REGION', purpose: 'Região Bedrock, se o provider bedrock estiver ligado.' },
    { name: 'AWS_DEFAULT_REGION', purpose: 'Fallback de região AWS.' },
    { name: 'SPRING_DATASOURCE_URL', purpose: 'Sobrescreve o JDBC. Valor com credencial não é documentado.' },
    { name: 'SPRING_DATASOURCE_USERNAME', purpose: 'Usuário JDBC. Valor omitido.' },
    { name: 'SPRING_DATASOURCE_PASSWORD', purpose: 'Senha JDBC. Nome apenas; valor omitido.' },
    { name: 'POSTGRES_DB', purpose: 'Nome do banco no compose. Valor de senha do compose não é documentado.' },
    { name: 'POSTGRES_USER', purpose: 'Usuário do compose.' },
    { name: 'POSTGRES_PASSWORD', purpose: 'Senha do compose. Nome apenas; valor omitido.' },
  ],
  profiles: [
    {
      id: 'default',
      name: 'Default (application.yml)',
      status: 'implemented',
      summary: 'Engine :8080, persistência canônica em memória, JDBC Postgres configurado com ddl-auto=validate, flags de console/telemetria/IA/HTTP canônico em false, ingress DenyAll.',
      source: 'backend/src/main/resources/application.yml',
    },
    {
      id: 'local-demo',
      name: 'local-demo',
      status: 'profile',
      summary: 'H2 mem MODE=PostgreSQL create-drop; console, SAT HTTP, signal HTTP, workers e capacity ligados. Stores canônicos continuam em memória. IA: placeholder do profile defaulta para ligado — não é o default de produção.',
      source: 'backend/src/main/resources/application-local-demo.yml',
    },
    {
      id: 'test',
      name: 'Teste (JUnit / SpringBootTest)',
      status: 'implemented',
      summary: 'Suíte Maven do backend. Não altera o Monitor. Fixtures e mocks de adapter/satélite ficam neste recorte.',
      source: 'backend/src/test/java',
    },
    {
      id: 'production',
      name: 'Produção',
      status: 'unverified',
      summary: 'Não há application-prod.yml neste repositório. O que existe é o default endurecido (flags off, DenyAll). Prontidão operacional de um ambiente publicado não foi inspecionada.',
      source: 'ausência de perfil de produção versionado',
    },
    {
      id: 'mocks',
      name: 'Mocks e fixtures',
      status: 'profile',
      summary: 'MockUniversalAdapter, mock de seguro :8095, Satélites de demo e Failure Lab. Não compõem topologia de produção.',
      source: 'spider.adapter.mock / satélites / segsense-provider-mock',
    },
  ],
  scripts: [
    { name: 'scripts/start-local.ps1', purpose: 'Sobe compose Postgres e imprime comandos para API/mocks/frontend.' },
    { name: 'scripts/start-presentation.ps1', purpose: 'Start de apresentação local-demo.' },
    { name: 'frontend/vite.config.js', purpose: 'Dev server do Monitor e proxy /v1 → :8080.' },
    { name: 'segsense/scripts/start-mvp-demo.ps1', purpose: 'Start da stack SegSense+mock ao redor da Spider. Incompatibilidade confirmada com Windows PowerShell 5.1 permanece sem correção; usar PowerShell 7+ para essa demo. Não é o start do Monitor.' },
  ],
  limitations: [
    'Flyway não está no classpath; schema Docker vem de database/init.sql no first boot do volume.',
    'Persistência canônica default é memória; JPA só com spider.canonical.persistence.mode=jpa.',
    'tb_step_attempt existe no SQL e não tem entidade JPA.',
    'Nenhuma FOREIGN KEY SQL foi declarada.',
    'local-demo usa H2 e não prova o PostgreSQL de compose.',
    'SpiderBank: SAT-003 de diagnóstico comprovado; card de Simulação permanece unavailable.',
    'IA default-off em application.yml; o profile local-demo altera o fallback do env.',
    'start-mvp-demo.ps1 (SegSense) não é compatível com Windows PowerShell 5.1 enquanto não for corrigido.',
    'Não há Maven Wrapper; o build local conhecido usa spider/.tools/apache-maven-3.9.16.',
  ],
};
