export const PROTOCOLS = [
  {
    id: 'canonical-http',
    name: 'Entrada canônica HTTP/JSON',
    category: 'contrato de aplicação',
    from: ['console-local-demo', 'clientes HTTP'],
    to: ['canonical-http', 'submit-canonical'],
    direction: 'externo → Spider',
    purpose: 'Submeter, listar e consultar execuções canônicas 1.0.',
    media: 'application/json',
    auth: 'X-Spider-Credential-Ref. Default deny-all; allowlist local-demo-console no perfil local-demo.',
    version: 'Canonical 1.0',
    identity: 'executionId, correlationId, Idempotency-Key',
    timeoutRetry: 'Idempotência por chave; retry de step é política da engine, não do cliente HTTP.',
    failures: '401 sem credencial; 422/REJECTED quando a rota não resolve; erros canônicos no envelope.',
    status: 'profile',
    profile: 'HTTP habilitado quando spider.canonical.http.enabled=true (local-demo).',
    evidence: [
      { kind: 'controller', path: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/canonical/CanonicalExecutionHttpController.java', label: 'CanonicalExecutionHttpController' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/integration/inbound/http/canonical/LocalDemoCanonicalHttpAccessTest.java', label: 'LocalDemoCanonicalHttpAccessTest' },
    ],
    aliases: ['POST /v1/canonical/executions', 'canonical execution'],
  },
  {
    id: 'external-signal',
    name: 'Sinal externo',
    category: 'contrato de aplicação',
    from: ['sistemas externos', 'console de simulação'],
    to: ['signal-http', 'wait-signal'],
    direction: 'externo → Spider',
    purpose: 'Retomar execução em WAITING_EXTERNAL via inbox ou apply inline.',
    media: 'application/json',
    auth: 'X-Spider-Credential-Ref + autorização de signal. Default deny-all.',
    version: 'mesmo envelope canônico',
    identity: 'executionId, wait/signal refs, correlationId',
    timeoutRetry: 'Inbox com lease e tentativas; worker SIGNAL_APPLICATION.',
    failures: 'SIGNAL_UNAUTHORIZED quando o perfil do sinal não confere; persistência durable ou apply imediato conforme config.',
    status: 'profile',
    profile: 'spider.signal-http.enabled no local-demo.',
    evidence: [
      { kind: 'controller', path: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/canonical/CanonicalSignalHttpController.java', label: 'CanonicalSignalHttpController' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/execution/signal/ExternalSignalResumeIntegrationTest.java', label: 'ExternalSignalResumeIntegrationTest' },
    ],
    aliases: ['POST /v1/canonical/signals'],
  },
  {
    id: 'satellite-contract',
    name: 'Satellite Contract',
    category: 'contrato de aplicação',
    from: ['satellite-http'],
    to: ['satellite-registry', 'provider-adapter'],
    direction: 'Experience Satellite → Spider → (provider quando READY)',
    purpose: 'Interação governada de satélite EXPERIENCE: identidade, finalidade, contexto, objetivo, decisão e impedimentos.',
    media: 'application/json; schemas 1.0, 1.1 e 1.2',
    auth: 'X-Spider-Satellite-Id + X-Spider-Satellite-Secret. Loopback-only no local-demo.',
    version: '1.0, 1.1 e 1.2 (SatelliteContractV1.supports)',
    identity: 'satelliteId, correlationId, idempotencyKey, messageId, contextRef',
    timeoutRetry: 'Idempotência por satélite+chave; conflito 409 se o corpo divergir.',
    failures: '401 credencial; 400 contexto/payload; 403 finalidade/papel; PLAN_IMPEDED ou READY sem fabricar execução canônica no frontend.',
    status: 'profile',
    profile: 'Controller @Profile("local-demo"); registry segsense + spiderbank.',
    evidence: [
      { kind: 'contract', path: 'backend/src/main/resources/contracts/satellite/1.0/satellite-interaction-request.schema.json', label: 'schema SAT 1.0' },
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/satellite/application/SatelliteInteractionService.java', label: 'SatelliteInteractionService' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/satellite/SatelliteContractV1Test.java', label: 'SatelliteContractV1Test' },
    ],
    aliases: ['SAT-003', 'POST /v1/satellites/interactions', 'SATELLITE_GOVERNED'],
  },
  {
    id: 'context-http',
    name: 'Context Intelligence HTTP',
    category: 'contrato de aplicação',
    from: ['clientes de contexto'],
    to: ['context-intelligence'],
    direction: 'externo → Spider',
    purpose: 'Listar intents, interpretar texto, resolver intent e materializar plano/execução de contexto.',
    media: 'application/json',
    auth: 'X-Spider-Credential-Ref quando o ingress canônico está ativo.',
    version: 'API /v1/context/*',
    identity: 'correlation e executionId quando a interpretação submete execução',
    timeoutRetry: 'Não documentado como retry de cliente; AI tem provider isolado.',
    failures: 'Flag spider.context.enabled; AI default-off.',
    status: 'profile',
    profile: 'spider.context.enabled=false no default; true no local-demo.',
    evidence: [
      { kind: 'controller', path: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/context/ContextIntelligenceHttpController.java', label: 'ContextIntelligenceHttpController' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/integration/inbound/http/context/ContextIntelligenceHttpTest.java', label: 'ContextIntelligenceHttpTest' },
    ],
    aliases: ['/v1/context/intents', '/v1/context/interpretations'],
  },
  {
    id: 'context-ai',
    name: 'Interpretação de contexto (AI opcional)',
    category: 'contrato interno',
    from: ['context-intelligence'],
    to: ['context-ai'],
    direction: 'Spider → provider de interpretação',
    purpose: 'Normalizar texto em intent/entidades. Não é agente nem composer de resposta.',
    media: 'interface Java ContextInterpretationProvider; Bedrock runtime quando selecionado',
    auth: 'Credenciais AWS apenas se provider=bedrock (não documentar valores).',
    version: 'scripted ou bedrock via configuração',
    identity: 'sem identidade de cliente; saída é interpretação estruturada',
    timeoutRetry: 'Isolado atrás da porta; default desligado.',
    failures: 'Sem evidência de uso, o Monitor não afirma que houve IA.',
    status: 'profile',
    profile: 'spider.context.ai.enabled=false no default. local-demo pode usar scripted.',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/integration/outbound/ai/ScriptedContextInterpretationProvider.java', label: 'ScriptedContextInterpretationProvider' },
      { kind: 'config', path: 'backend/src/main/resources/application.yml', label: 'spider.context.ai.enabled' },
    ],
    aliases: ['Bedrock', 'scripted', 'ContextInterpretationProvider'],
  },
  {
    id: 'provider-http',
    name: 'Provider HTTP (capability)',
    category: 'transporte',
    from: ['provider-adapter'],
    to: ['insurance-provider-mock'],
    direction: 'Spider → provider',
    purpose: 'Executar capability resolvida após o Satellite Contract ficar READY.',
    media: 'HTTP/JSON',
    auth: 'segredo do provider no servidor (nome da propriedade apenas)',
    version: 'contrato de execução do adapter atual (insurance-provider-mock)',
    identity: 'requestId preq-*, correlationId, decisionId',
    timeoutRetry: 'timeout do registry (PT3S no local-demo para o mock de seguro)',
    failures: 'PROVIDER_UNAVAILABLE se o executor não responde; adapter atual aceita insurance-provider-mock.',
    status: 'profile',
    profile: 'local-demo / mock. Crédito não está integrado neste adapter.',
    evidence: [
      { kind: 'adapter', path: 'backend/src/main/java/br/com/banco/spider/satellite/application/port/ProviderCapabilityPort.java', label: 'ProviderCapabilityPort' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/integration/inbound/http/satellite/SatelliteInteractionHttpTest.java', label: 'SatelliteInteractionHttpTest' },
    ],
    aliases: ['insurance-provider-mock', 'HttpProviderCapabilityAdapter'],
  },
  {
    id: 'mock-adapter',
    name: 'Mock Universal Adapter',
    category: 'transporte',
    from: ['canonical-engine'],
    to: ['mock-universal-adapter'],
    direction: 'engine → test double',
    purpose: 'Executar rotas canônicas de demonstração (RETRY_THEN_SUCCESS, WAIT, etc.).',
    media: 'chamada in-process (não é rede)',
    auth: 'não aplicável',
    version: 'cenários do catálogo de rotas mock',
    identity: 'executionId / step',
    timeoutRetry: 'política do cenário (retry, wait, fail)',
    failures: 'cenários negativos e 500 simulados',
    status: 'profile',
    profile: 'mock / local-demo. Não é topologia de produção.',
    evidence: [
      { kind: 'adapter', path: 'backend/src/main/java/br/com/banco/spider/integration/mock/MockUniversalAdapter.java', label: 'MockUniversalAdapter' },
    ],
    aliases: ['mock-universal', 'RETRY_THEN_SUCCESS'],
  },
  {
    id: 'callback-outbox',
    name: 'Callback outbox',
    category: 'evento',
    from: ['canonical-engine'],
    to: ['callback-outbox'],
    direction: 'engine → outbox → delivery',
    purpose: 'Registrar e entregar callbacks de forma assíncrona.',
    media: 'persistência + HTTP do adapter de callback',
    auth: 'CallbackAuthorizationPort (deny-all ou originator matched)',
    version: 'schema tb_callback_outbox',
    identity: 'outbox_id, execution_id, logical_callback_id',
    timeoutRetry: 'next_attempt_at, lease_owner, lease_until; worker CALLBACK_DELIVERY',
    failures: 'tentativas em tb_callback_delivery_attempt; não é Reconciliation Workbench',
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/execution/callback/CallbackOutboxProcessor.java', label: 'CallbackOutboxProcessor' },
      { kind: 'migration', path: 'database/migrations/V20260821e__tb_callback_outbox.sql', label: 'V20260821e' },
    ],
    aliases: ['outbox', 'CALLBACK_DELIVERY'],
  },
  {
    id: 'callback-reconciliation',
    name: 'Reconciliação operacional de callback',
    category: 'worker',
    from: ['callback-outbox'],
    to: ['callback-reconciliation'],
    direction: 'worker → processor',
    purpose: 'Processar due list de reconciliação (query de status, redelivery, revisão). Não é um workbench de produto.',
    media: 'stores + processor interno',
    auth: 'ReconcileCallbackNowUseCase exige callback.reconcile; sem controller HTTP',
    version: 'tb_callback_reconciliation*',
    identity: 'reconciliation_id, outbox_id',
    timeoutRetry: 'worker CALLBACK_RECONCILIATION + lease',
    failures: 'batch limitado (≤100 no use case ops)',
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/application/canonical/ReconcileCallbackNowUseCase.java', label: 'ReconcileCallbackNowUseCase' },
      { kind: 'migration', path: 'database/migrations/V20260821f__tb_callback_reconciliation.sql', label: 'V20260821f' },
    ],
    aliases: ['CALLBACK_RECONCILIATION', 'ReconcileCallbackNowUseCase'],
  },
  {
    id: 'wait-inbox',
    name: 'Wait e inbox de sinal',
    category: 'persistência',
    from: ['canonical-engine'],
    to: ['wait-signal'],
    direction: 'engine ↔ inbox',
    purpose: 'Persistir espera externa e mensagens de sinal até apply/expiry.',
    media: 'tabelas tb_execution_wait / tb_inbox_message ou stores em memória',
    auth: 'integridade de envelope protegido quando o perfil exige',
    version: 'migrations V20260821c, j, k',
    identity: 'wait_id, source_ref+message_id',
    timeoutRetry: 'expires_at; worker WAIT_EXPIRY; lease no inbox',
    failures: 'EXPIRED / RECONCILIATION_REQUIRED no domínio de wait',
    status: 'implemented',
    evidence: [
      { kind: 'migration', path: 'database/migrations/V20260821c__tb_execution_wait_inbox.sql', label: 'V20260821c' },
    ],
    aliases: ['WAITING_EXTERNAL', 'inbox'],
  },
  {
    id: 'worker-lease',
    name: 'Lease e fencing de workers',
    category: 'worker',
    from: ['worker-runtime'],
    to: ['wait-signal', 'callback-outbox', 'callback-reconciliation'],
    direction: 'coordenador → handlers',
    purpose: 'Tick, claim CAS de schedule, heartbeat e drain com fencing token.',
    media: 'in-process + tb_runtime_* quando JPA',
    auth: 'console drain autenticado',
    version: 'WorkerType fechado',
    identity: 'worker_id, schedule_code, fencing token',
    timeoutRetry: 'lease default PT30S (PT10S no local-demo)',
    failures: 'contention/stale instance; Failure Lab cobre crash/drain',
    status: 'profile',
    profile: 'spider.worker-runtime.enabled=false no default; true no local-demo.',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/operational/workers/WorkerRuntimeCoordinator.java', label: 'WorkerRuntimeCoordinator' },
      { kind: 'migration', path: 'database/migrations/V20260825c__durable_worker_runtime.sql', label: 'V20260825c' },
    ],
    aliases: ['DurableSchedule', 'fencing'],
  },
  {
    id: 'operational-events',
    name: 'Operational Events',
    category: 'evento',
    from: ['canonical-engine', 'satellite-registry', 'worker-runtime'],
    to: ['operational-events', 'monitor-query'],
    direction: 'componentes → store → Monitor',
    purpose: 'Registrar fatos operacionais com redaction. Não reconstitui payload de negócio.',
    media: 'store in-memory ou tb_operational_event (metadata_json text)',
    auth: 'emissão interna; leitura pelo console autenticado',
    version: 'OperationalEventType',
    identity: 'eventId, correlationId, executionId/messageId',
    timeoutRetry: 'não é fila de entrega ao cliente',
    failures: 'publisher no-op se telemetry off; recorte do Monitor limitado',
    status: 'implemented',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/operational/events/OperationalEventType.java', label: 'OperationalEventType' },
      { kind: 'migration', path: 'database/migrations/V20260825__tb_operational_event.sql', label: 'V20260825' },
    ],
    aliases: ['SATELLITE_RESPONSE_RETURNED', 'telemetry'],
  },
  {
    id: 'monitor-http',
    name: 'Leitura do Monitor',
    category: 'contrato de aplicação',
    from: ['monitor-query'],
    to: ['frontend-monitor'],
    direction: 'Spider → frontend do Monitor',
    purpose: 'Expor recorte de eventos, execuções e readiness da Simulação.',
    media: 'HTTP/JSON via proxy Vite /v1 → :8080',
    auth: 'X-Spider-Credential-Ref = local-demo-console no frontend local',
    version: 'read model do console',
    identity: 'eventId, executionId, originSatellite — só identidades do backend',
    timeoutRetry: 'polling do stream no frontend',
    failures: 'available=false se o store não responde; recorte truncado',
    status: 'profile',
    profile: 'spider.console.http.enabled no local-demo.',
    evidence: [
      { kind: 'implementation', path: 'backend/src/main/java/br/com/banco/spider/application/console/OperationalConsoleQueryService.java', label: 'OperationalConsoleQueryService' },
      { kind: 'test', path: 'backend/src/test/java/br/com/banco/spider/application/console/MonitorEventsTest.java', label: 'MonitorEventsTest' },
    ],
    aliases: ['/v1/console/monitor/events', '/v1/console/monitor/simulation'],
  },
  {
    id: 'jpa-jdbc',
    name: 'JDBC/JPA PostgreSQL',
    category: 'persistência',
    from: ['persistence-ports'],
    to: ['postgres'],
    direction: 'adapters → banco',
    purpose: 'Mapear entidades canônicas, events, workers e governança quando mode=jpa.',
    media: 'JDBC PostgreSQL; H2 MODE=PostgreSQL no local-demo',
    auth: 'usuário do datasource (valor não documentado)',
    version: 'schema em database/migrations e database/init.sql; Flyway não amarrado',
    identity: 'PKs varchar/uuid conforme tabela',
    timeoutRetry: 'Hikari connection-timeout',
    failures: 'ddl-auto validate no default; create-drop no H2 local-demo',
    status: 'partial',
    profile: 'Default canonical persistence.mode=memory. Adapters JPA existem sob mode=jpa.',
    evidence: [
      { kind: 'config', path: 'backend/src/main/resources/application.yml', label: 'spring.datasource / persistence.mode' },
      { kind: 'migration', path: 'database/migrations/README.md', label: 'migrations README' },
    ],
    aliases: ['Hibernate', 'Hikari', 'H2'],
  },
  {
    id: 'internal-port',
    name: 'Contrato interno (porta Java)',
    category: 'contrato interno',
    from: ['vários componentes'],
    to: ['vários componentes'],
    direction: 'in-process',
    purpose: 'Interfaces *Port e catálogos. Não é protocolo de rede.',
    media: 'chamada Java / Reactor Mono',
    auth: 'não aplicável como transporte',
    version: 'código da interface',
    identity: 'definida pelo caso de uso',
    timeoutRetry: 'depende do adapter',
    failures: 'depende do adapter',
    status: 'implemented',
    evidence: [
      { kind: 'interface', path: 'backend/src/main/java/br/com/banco/spider/execution/persistence/port/ExecutionControlStorePort.java', label: 'ExecutionControlStorePort' },
    ],
    aliases: ['Port', 'adapter'],
  },
  {
    id: 'contextual-link',
    name: 'Gateway contextual legado',
    category: 'transporte',
    from: ['páginas parceiras'],
    to: ['contextual-link'],
    direction: 'browser → /go → satélite legado',
    purpose: 'Redirecionar clique editorial para /spiderbank?ctx= sem expor contexto cru.',
    media: 'HTTP redirect',
    auth: 'não substitui SAT-003',
    version: 'legado; preservado',
    identity: 'ctx opaco',
    timeoutRetry: 'não aplicável',
    failures: 'não é a integração SAT-003 do SpiderBank',
    status: 'implemented',
    evidence: [
      { kind: 'controller', path: 'backend/src/main/java/br/com/banco/spider/integration/inbound/http/contextuallink/ContextualLinkGatewayController.java', label: 'GET /go' },
    ],
    aliases: ['/go', '/v1/demo/spiderbank/entry'],
  },
];
