export const SCHEMA_GROUPS = [
  { id: 'legacy', title: 'Legado de produto', tables: ['tb_product_routes', 'tb_audit_trace'] },
  { id: 'execution', title: 'Execução canônica', tables: ['tb_execution_control', 'tb_execution_plan', 'tb_execution_transition', 'tb_execution_result', 'tb_idempotency_record', 'tb_execution_step', 'tb_step_attempt'] },
  { id: 'wait', title: 'Wait, inbox e envelope', tables: ['tb_execution_wait', 'tb_inbox_message', 'tb_protected_signal_envelope'] },
  { id: 'callback', title: 'Callback operacional', tables: ['tb_execution_callback_context', 'tb_callback_outbox', 'tb_callback_delivery_attempt', 'tb_callback_reconciliation', 'tb_callback_reconciliation_attempt'] },
  { id: 'security', title: 'Segurança', tables: ['tb_security_replay_guard'] },
  { id: 'governance', title: 'Governança', tables: ['tb_governance_artifact', 'tb_governance_bundle', 'tb_governance_bundle_artifact', 'tb_governance_validation_report', 'tb_governance_snapshot', 'tb_governance_activation', 'tb_governance_activation_history', 'tb_governance_audit_event', 'tb_execution_governance_fixation'] },
  { id: 'ops', title: 'Eventos e workers', tables: ['tb_operational_event', 'tb_runtime_worker_instance', 'tb_runtime_schedule'] },
];

export const SCHEMA_NOTE =
  'Fonte: migrations em database/migrations e mapeamento JPA. Não é inspeção de um PostgreSQL em execução. Nenhuma FOREIGN KEY foi declarada no SQL; cardinalidades abaixo são inferidas pelos UNIQUE/PKs e pelo uso no código.';

export const SCHEMA_RUNTIME = {
  docker: 'database/init.sql no first boot do volume postgres:16-alpine',
  flyway: 'Não amarrado ao Spring Boot.',
  defaultApp: 'canonical persistence.mode=memory; spring.jpa.ddl-auto=validate contra Postgres se JPA for usado.',
  localDemo: 'H2 mem MODE=PostgreSQL, ddl-auto=create-drop; stores canônicos continuam em memória.',
};

export const TABLES = [
  {
    id: 'tb_product_routes',
    purpose: 'Rotas de produto legado (código + versão).',
    migration: 'database/migrations/V20260805__tb_product_routes_audit_trace.sql',
    pk: ['id uuid'],
    unique: ['(product_code, version)'],
    fk: [],
    indexes: ['product_code WHERE enabled'],
    jsonb: ['definition_json'],
    columns: [
      { name: 'id', type: 'uuid' },
      { name: 'product_code', type: 'varchar(100)' },
      { name: 'version', type: 'integer' },
      { name: 'definition_json', type: 'jsonb' },
      { name: 'enabled', type: 'boolean' },
    ],
    readers: ['OrchestratorController legado'],
    writers: ['bootstrap / JPA ProductRoute'],
    cardinality: '1 rota : N traces por product_code (inferido, sem FK)',
  },
  {
    id: 'tb_audit_trace',
    purpose: 'Trace legado de orquestração de produto.',
    migration: 'database/migrations/V20260805__tb_product_routes_audit_trace.sql',
    pk: ['id uuid'],
    unique: [],
    fk: [],
    indexes: ['correlation_id', 'started_at DESC'],
    jsonb: ['metadata'],
    columns: [
      { name: 'correlation_id', type: 'uuid' },
      { name: 'idempotency_key', type: 'varchar(200)' },
      { name: 'status', type: 'varchar(40)' },
      { name: 'metadata', type: 'jsonb' },
    ],
    readers: ['GET /api/v1/traces/recent'],
    writers: ['fluxo legado'],
    cardinality: 'N traces por product_code (sem FK)',
  },
  {
    id: 'tb_execution_control',
    purpose: 'Cabeçalho da execução canônica: estado, correlação, rota.',
    migration: 'database/migrations/V20260821__tb_canonical_execution_persistence.sql',
    alteredBy: ['database/migrations/V20260821d__tb_execution_control_owner.sql'],
    pk: ['execution_id'],
    unique: [],
    fk: [],
    indexes: ['(state, last_updated_at)', 'correlation_id', 'owner_principal_ref parcial'],
    jsonb: [],
    columns: [
      { name: 'execution_id', type: 'varchar(120)' },
      { name: 'context_id', type: 'varchar(120)' },
      { name: 'correlation_id', type: 'varchar(200)' },
      { name: 'state', type: 'varchar(40)' },
      { name: 'owner_principal_ref', type: 'varchar(200)' },
    ],
    readers: ['Get/List canonical', 'Monitor'],
    writers: ['canonical-engine via ports'],
    cardinality: '1 control : 0..1 plan / result (UNIQUE no filho)',
  },
  {
    id: 'tb_execution_plan',
    purpose: 'Plano materializado da execução (representação canônica em text).',
    migration: 'database/migrations/V20260821__tb_canonical_execution_persistence.sql',
    pk: ['plan_id'],
    unique: ['execution_id'],
    fk: [],
    indexes: [],
    jsonb: [],
    jsonText: ['canonical_plan_representation'],
    columns: [
      { name: 'plan_id', type: 'varchar(120)' },
      { name: 'execution_id', type: 'varchar(120)' },
      { name: 'canonical_plan_representation', type: 'text' },
    ],
    readers: ['read model de execução'],
    writers: ['canonical-engine'],
    cardinality: '1:1 com execution_control (UNIQUE execution_id)',
  },
  {
    id: 'tb_execution_transition',
    purpose: 'Histórico de transições de estado.',
    migration: 'database/migrations/V20260821__tb_canonical_execution_persistence.sql',
    pk: ['transition_id'],
    unique: ['(execution_id, sequence_no)'],
    fk: [],
    indexes: ['execution_id'],
    jsonb: [],
    columns: [
      { name: 'execution_id', type: 'varchar(120)' },
      { name: 'previous_state', type: 'varchar(40)' },
      { name: 'new_state', type: 'varchar(40)' },
      { name: 'reason_code', type: 'varchar(80)' },
    ],
    readers: ['timeline do Monitor'],
    writers: ['canonical-engine'],
    cardinality: '1 execution : N transitions',
  },
  {
    id: 'tb_execution_result',
    purpose: 'Resultado canônico persistido.',
    migration: 'database/migrations/V20260821__tb_canonical_execution_persistence.sql',
    pk: ['result_ref'],
    unique: ['execution_id'],
    fk: [],
    indexes: [],
    jsonText: ['result_representation'],
    columns: [
      { name: 'result_ref', type: 'varchar(120)' },
      { name: 'execution_id', type: 'varchar(120)' },
      { name: 'technical_status', type: 'varchar(40)' },
    ],
    readers: ['GET execução'],
    writers: ['canonical-engine'],
    cardinality: '1:1 com execution',
  },
  {
    id: 'tb_idempotency_record',
    purpose: 'Reserva de idempotência canônica (hashes).',
    migration: 'database/migrations/V20260821__tb_canonical_execution_persistence.sql',
    pk: ['idempotency_record_id'],
    unique: ['(scope_hash, idempotency_key_hash)'],
    fk: [],
    indexes: ['execution_id'],
    jsonb: [],
    columns: [
      { name: 'scope_hash', type: 'varchar(128)' },
      { name: 'idempotency_key_hash', type: 'varchar(128)' },
      { name: 'execution_id', type: 'varchar(120)' },
    ],
    readers: ['IdempotencyStorePort'],
    writers: ['submit canônico'],
    cardinality: 'N records : 1 execution',
  },
  {
    id: 'tb_execution_step',
    purpose: 'Steps do plano materializado.',
    migration: 'database/migrations/V20260821b__tb_execution_step_attempt.sql',
    pk: ['(execution_id, step_id)'],
    unique: [],
    fk: [],
    indexes: ['state'],
    jsonText: ['evidence_refs_json'],
    columns: [
      { name: 'execution_id', type: 'varchar(120)' },
      { name: 'step_id', type: 'varchar' },
      { name: 'state', type: 'varchar' },
    ],
    readers: ['read model de steps'],
    writers: ['canonical-engine'],
    cardinality: '1 execution : N steps',
  },
  {
    id: 'tb_step_attempt',
    purpose: 'Tentativas de um step. Existe no SQL; store em memória no runtime default. Sem entidade JPA.',
    migration: 'database/migrations/V20260821b__tb_execution_step_attempt.sql',
    pk: ['attempt_id'],
    unique: ['(execution_id, step_id, attempt_number)'],
    fk: [],
    indexes: ['(execution_id, step_id)'],
    jsonb: [],
    columns: [
      { name: 'attempt_id', type: 'varchar' },
      { name: 'attempt_number', type: 'integer' },
    ],
    readers: ['InMemoryStepAttemptStore'],
    writers: ['canonical-engine'],
    cardinality: '1 step : N attempts',
    status: 'partial',
  },
  {
    id: 'tb_execution_wait',
    purpose: 'Espera externa de uma execução.',
    migration: 'database/migrations/V20260821c__tb_execution_wait_inbox.sql',
    pk: ['wait_id'],
    unique: ['active wait parcial'],
    fk: [],
    indexes: ['expires', 'execution+step', 'token fingerprint'],
    jsonb: [],
    columns: [
      { name: 'wait_id', type: 'varchar' },
      { name: 'execution_id', type: 'varchar' },
      { name: 'state', type: 'varchar' },
    ],
    readers: ['WaitExpiryProcessor'],
    writers: ['WaitCreationService'],
    cardinality: '1 execution : 0..N waits',
  },
  {
    id: 'tb_inbox_message',
    purpose: 'Inbox durável de sinais.',
    migration: 'database/migrations/V20260821c__tb_execution_wait_inbox.sql',
    pk: ['(source_ref, message_id)'],
    unique: [],
    fk: [],
    indexes: ['processing', 'apply_due', 'lease'],
    jsonb: [],
    columns: [
      { name: 'source_ref', type: 'varchar' },
      { name: 'message_id', type: 'varchar' },
      { name: 'wait_id', type: 'varchar' },
    ],
    readers: ['SIGNAL_APPLICATION worker'],
    writers: ['ExternalSignalIngress'],
    cardinality: 'N messages : 0..1 wait',
  },
  {
    id: 'tb_execution_callback_context',
    purpose: 'Contexto de callback por execução.',
    migration: 'database/migrations/V20260821e__tb_callback_outbox.sql',
    pk: ['execution_id'],
    unique: [],
    fk: [],
    indexes: [],
    jsonb: [],
    columns: [
      { name: 'execution_id', type: 'varchar(120)' },
      { name: 'confirmation_mode', type: 'varchar' },
    ],
    readers: ['callback processors'],
    writers: ['SubmitCanonical + engine'],
    cardinality: '1:1 com execution',
  },
  {
    id: 'tb_callback_outbox',
    purpose: 'Fila de entrega de callback com lease.',
    migration: 'database/migrations/V20260821e__tb_callback_outbox.sql',
    pk: ['outbox_id'],
    unique: ['logical_callback_id', 'execution_id'],
    fk: [],
    indexes: ['(state, next_attempt_at)'],
    jsonb: [],
    columns: [
      { name: 'outbox_id', type: 'varchar' },
      { name: 'execution_id', type: 'varchar' },
      { name: 'lease_owner', type: 'varchar' },
    ],
    readers: ['CallbackOutboxProcessor'],
    writers: ['CallbackOutboxCreationService'],
    cardinality: '1 execution : 0..1 outbox (UNIQUE)',
  },
  {
    id: 'tb_callback_delivery_attempt',
    purpose: 'Tentativas de entrega do outbox.',
    migration: 'database/migrations/V20260821e__tb_callback_outbox.sql',
    pk: ['delivery_id'],
    unique: ['(outbox_id, attempt_number)'],
    fk: [],
    indexes: ['outbox_id'],
    jsonb: [],
    columns: [
      { name: 'delivery_id', type: 'varchar' },
      { name: 'outbox_id', type: 'varchar' },
      { name: 'attempt_number', type: 'integer' },
    ],
    readers: ['delivery processor'],
    writers: ['CallbackOutboxProcessor'],
    cardinality: '1 outbox : N attempts',
  },
  {
    id: 'tb_callback_reconciliation',
    purpose: 'Caso operacional de reconciliação de callback — não é workbench de produto.',
    migration: 'database/migrations/V20260821f__tb_callback_reconciliation.sql',
    pk: ['reconciliation_id'],
    unique: ['outbox_id'],
    fk: [],
    indexes: ['due', 'lease', 'execution'],
    jsonb: [],
    columns: [
      { name: 'reconciliation_id', type: 'varchar' },
      { name: 'outbox_id', type: 'varchar' },
    ],
    readers: ['CallbackReconciliationProcessor'],
    writers: ['CallbackReconciliationCreationService'],
    cardinality: '1 outbox : 0..1 reconciliation',
  },
  {
    id: 'tb_callback_reconciliation_attempt',
    purpose: 'Tentativas do caso de reconciliação operacional.',
    migration: 'database/migrations/V20260821f__tb_callback_reconciliation.sql',
    pk: ['attempt id'],
    unique: ['(reconciliation_id, attempt_number)'],
    fk: [],
    indexes: ['reconciliation+started'],
    jsonb: [],
    columns: [
      { name: 'reconciliation_id', type: 'varchar' },
      { name: 'attempt_number', type: 'integer' },
    ],
    readers: ['processor'],
    writers: ['processor'],
    cardinality: '1 reconciliation : N attempts',
  },
  {
    id: 'tb_security_replay_guard',
    purpose: 'Reserva anti-replay (nonce/fingerprint).',
    migration: 'database/migrations/V20260821g__tb_security_replay_guard.sql',
    pk: ['reservation_id'],
    unique: ['(replay_scope_hash, nonce_hash, fingerprint_version)'],
    fk: [],
    indexes: ['expiry+status'],
    jsonb: [],
    columns: [
      { name: 'reservation_id', type: 'varchar' },
      { name: 'nonce_hash', type: 'varchar' },
    ],
    readers: ['ReplayGuardPort'],
    writers: ['ReplayGuardPort'],
    cardinality: 'N reservas independentes',
  },
  {
    id: 'tb_governance_artifact',
    purpose: 'Artefato do control plane de governança.',
    migration: 'database/migrations/V20260821h__tb_governance_control_plane.sql',
    pk: ['artifact_id'],
    unique: ['ref de artefato'],
    fk: [],
    indexes: [],
    jsonb: [],
    columns: [{ name: 'artifact_id', type: 'varchar' }],
    readers: ['governance services'],
    writers: ['governance bootstrap'],
    cardinality: '1 artifact : N bundle_artifact',
  },
  {
    id: 'tb_governance_bundle',
    purpose: 'Bundle de governança.',
    migration: 'database/migrations/V20260821h__tb_governance_control_plane.sql',
    pk: ['bundle_id'],
    unique: ['bundle ref'],
    fk: [],
    indexes: [],
    jsonb: [],
    columns: [{ name: 'bundle_id', type: 'varchar' }],
    readers: ['governance'],
    writers: ['governance'],
    cardinality: '1 bundle : N artifacts',
  },
  {
    id: 'tb_governance_bundle_artifact',
    purpose: 'Associação bundle↔artifact. Sem PRIMARY KEY SQL; UNIQUE composto. JPA usa IdClass.',
    migration: 'database/migrations/V20260821h__tb_governance_control_plane.sql',
    pk: ['UNIQUE (bundle_id, artifact_type, artifact_code, artifact_version) — sem PK SQL'],
    unique: ['ordinal composto'],
    fk: [],
    indexes: [],
    jsonb: [],
    columns: [
      { name: 'bundle_id', type: 'varchar' },
      { name: 'ordinal_pos', type: 'integer' },
    ],
    readers: ['governance'],
    writers: ['governance'],
    cardinality: 'N:N inferido',
    status: 'partial',
  },
  {
    id: 'tb_governance_validation_report',
    purpose: 'Relatório de validação do bundle.',
    migration: 'database/migrations/V20260821h__tb_governance_control_plane.sql',
    pk: ['report_id'],
    unique: [],
    fk: [],
    indexes: [],
    jsonText: ['findings_json'],
    columns: [{ name: 'report_id', type: 'varchar' }],
    readers: ['governance'],
    writers: ['governance'],
    cardinality: 'N reports por bundle (inferido)',
  },
  {
    id: 'tb_governance_snapshot',
    purpose: 'Snapshot consolidado.',
    migration: 'database/migrations/V20260821h__tb_governance_control_plane.sql',
    pk: ['snapshot_id'],
    unique: ['(bundle_ref, bundle_digest)'],
    fk: [],
    indexes: [],
    jsonText: ['snapshot_json'],
    columns: [{ name: 'snapshot_id', type: 'varchar' }],
    readers: ['SnapshotBackedAdapterBindingResolver'],
    writers: ['governance'],
    cardinality: 'N snapshots por bundle',
  },
  {
    id: 'tb_governance_activation',
    purpose: 'Ativação vigente por escopo.',
    migration: 'database/migrations/V20260821h__tb_governance_control_plane.sql',
    pk: ['governance_scope'],
    unique: [],
    fk: [],
    indexes: [],
    jsonb: [],
    columns: [{ name: 'governance_scope', type: 'varchar' }],
    readers: ['activation services'],
    writers: ['activation services'],
    cardinality: '1 vigente por scope',
  },
  {
    id: 'tb_governance_activation_history',
    purpose: 'Histórico de ativações.',
    migration: 'database/migrations/V20260821i__tb_governance_control_plane_runtime.sql',
    pk: ['history_id bigint identity'],
    unique: ['(governance_scope, activation_sequence)'],
    fk: [],
    indexes: [],
    jsonb: [],
    columns: [
      { name: 'history_id', type: 'bigint' },
      { name: 'governance_scope', type: 'varchar' },
    ],
    readers: ['governance runtime'],
    writers: ['governance runtime'],
    cardinality: '1 scope : N history',
  },
  {
    id: 'tb_governance_audit_event',
    purpose: 'Auditoria do control plane de governança.',
    migration: 'database/migrations/V20260821h__tb_governance_control_plane.sql',
    pk: ['event_id'],
    unique: [],
    fk: [],
    indexes: [],
    jsonb: [],
    columns: [{ name: 'event_id', type: 'varchar' }],
    readers: ['governance'],
    writers: ['governance'],
    cardinality: 'N eventos',
  },
  {
    id: 'tb_execution_governance_fixation',
    purpose: 'Fixação de governança por execução.',
    migration: 'database/migrations/V20260821h__tb_governance_control_plane.sql',
    pk: ['execution_id'],
    unique: [],
    fk: [],
    indexes: [],
    jsonb: [],
    columns: [{ name: 'execution_id', type: 'varchar(120)' }],
    readers: ['engine / governance'],
    writers: ['SubmitCanonicalExecutionUseCase'],
    cardinality: '1:1 com execution',
  },
  {
    id: 'tb_protected_signal_envelope',
    purpose: 'Envelope protegido de sinal (ciphertext em TEXT).',
    migration: 'database/migrations/V20260821k__token_protected_envelope.sql',
    pk: ['protected_envelope_id'],
    unique: ['inbox_logical_key'],
    fk: [],
    indexes: ['state'],
    jsonb: [],
    columns: [
      { name: 'protected_envelope_id', type: 'varchar' },
      { name: 'inbox_logical_key', type: 'varchar' },
    ],
    readers: ['ProtectedEnvelopeMaintenance worker'],
    writers: ['signal ingress protegido'],
    cardinality: '1 envelope : 1 inbox key',
  },
  {
    id: 'tb_operational_event',
    purpose: 'Eventos operacionais do Monitor.',
    migration: 'database/migrations/V20260825__tb_operational_event.sql',
    pk: ['event_id'],
    unique: [],
    fk: [],
    indexes: ['(execution_id, occurred_at, event_id)', 'event_type', 'category'],
    jsonText: ['metadata_json'],
    columns: [
      { name: 'event_id', type: 'varchar' },
      { name: 'event_type', type: 'varchar' },
      { name: 'correlation_id', type: 'varchar' },
      { name: 'metadata_json', type: 'text' },
    ],
    readers: ['monitor-query'],
    writers: ['SafeOperationalEventPublisher'],
    cardinality: 'N events : 0..1 execution',
  },
  {
    id: 'tb_runtime_worker_instance',
    purpose: 'Instâncias de worker com heartbeat.',
    migration: 'database/migrations/V20260825c__durable_worker_runtime.sql',
    pk: ['worker_id'],
    unique: [],
    fk: [],
    indexes: ['status/type/heartbeat'],
    jsonb: [],
    columns: [
      { name: 'worker_id', type: 'varchar' },
      { name: 'worker_type', type: 'varchar' },
    ],
    readers: ['WorkerRuntimeQueryService'],
    writers: ['WorkerRuntimeCoordinator'],
    cardinality: 'N instances; sem FK para schedule',
  },
  {
    id: 'tb_runtime_schedule',
    purpose: 'Schedules duráveis com claim/fencing.',
    migration: 'database/migrations/V20260825c__durable_worker_runtime.sql',
    pk: ['schedule_code'],
    unique: [],
    fk: [],
    indexes: ['eligible', 'owner', 'worker_type'],
    jsonb: [],
    columns: [
      { name: 'schedule_code', type: 'varchar' },
      { name: 'worker_type', type: 'varchar' },
    ],
    readers: ['WorkerScheduleRunner'],
    writers: ['DurableScheduleStore'],
    cardinality: 'N schedules; sem FK SQL para worker',
  },
];
