"""Vocabulário e conjuntos fechados da entrada fiscal."""

from decimal import Decimal

ALGORITHM_NAME = "fiscal_inbound"
ALGORITHM_VERSION = "1"
CURRENCY = "BRL"
ZERO = Decimal("0")
QUANTITY_EXPONENT = Decimal("0.000001")
FACTOR_EXPONENT = Decimal("0.0000000001")
MONEY_EXPONENT = Decimal("0.000001")

STATUS_DRAFT = "draft"
STATUS_CAPTURED = "captured"
STATUS_AWAITING_XML = "awaiting_xml"
STATUS_AWAITING_MATCH = "awaiting_match"
STATUS_AWAITING_CHECK = "awaiting_check"
STATUS_PARTIALLY_RECEIVED = "partially_received"
STATUS_RECEIVED = "received"
STATUS_DIVERGENT = "divergent"
STATUS_CANCELLED = "cancelled"
STATUS_REFUSED = "refused"
STATUS_SUPERSEDED = "superseded"

DOCUMENT_STATUSES = (
    STATUS_DRAFT,
    STATUS_CAPTURED,
    STATUS_AWAITING_XML,
    STATUS_AWAITING_MATCH,
    STATUS_AWAITING_CHECK,
    STATUS_PARTIALLY_RECEIVED,
    STATUS_RECEIVED,
    STATUS_DIVERGENT,
    STATUS_CANCELLED,
    STATUS_REFUSED,
    STATUS_SUPERSEDED,
)
TERMINAL_STATUSES = frozenset({STATUS_CANCELLED, STATUS_REFUSED, STATUS_SUPERSEDED})
OPEN_STATUSES = frozenset(set(DOCUMENT_STATUSES) - TERMINAL_STATUSES - {STATUS_RECEIVED})

ORIGIN_ACCESS_KEY = "access_key"
ORIGIN_XML = "xml"
ORIGIN_SCAN = "scan"
ORIGIN_MANUAL = "manual"
ORIGIN_DISTRIBUTION = "distribution"
CAPTURE_ORIGINS = (
    ORIGIN_ACCESS_KEY,
    ORIGIN_XML,
    ORIGIN_SCAN,
    ORIGIN_MANUAL,
    ORIGIN_DISTRIBUTION,
)

TRANSITIONS: dict[str, frozenset[str]] = {
    STATUS_DRAFT: frozenset({STATUS_CAPTURED, STATUS_AWAITING_XML, STATUS_CANCELLED}),
    STATUS_CAPTURED: frozenset(
        {
            STATUS_AWAITING_XML,
            STATUS_AWAITING_MATCH,
            STATUS_CANCELLED,
            STATUS_REFUSED,
            STATUS_SUPERSEDED,
        }
    ),
    STATUS_AWAITING_XML: frozenset(
        {STATUS_CAPTURED, STATUS_AWAITING_MATCH, STATUS_CANCELLED, STATUS_REFUSED}
    ),
    STATUS_AWAITING_MATCH: frozenset(
        {STATUS_AWAITING_CHECK, STATUS_DIVERGENT, STATUS_CANCELLED, STATUS_REFUSED}
    ),
    STATUS_AWAITING_CHECK: frozenset(
        {
            STATUS_PARTIALLY_RECEIVED,
            STATUS_RECEIVED,
            STATUS_DIVERGENT,
            STATUS_CANCELLED,
            STATUS_REFUSED,
        }
    ),
    STATUS_PARTIALLY_RECEIVED: frozenset(
        {STATUS_RECEIVED, STATUS_DIVERGENT, STATUS_CANCELLED}
    ),
    STATUS_DIVERGENT: frozenset(
        {STATUS_AWAITING_CHECK, STATUS_RECEIVED, STATUS_CANCELLED, STATUS_REFUSED}
    ),
    STATUS_RECEIVED: frozenset({STATUS_SUPERSEDED}),
    STATUS_CANCELLED: frozenset(),
    STATUS_REFUSED: frozenset(),
    STATUS_SUPERSEDED: frozenset(),
}

MATCH_UNMATCHED = "unmatched"
MATCH_SUGGESTED = "suggested"
MATCH_MATCHED = "matched"
MATCH_IGNORED = "ignored"
MATCH_STATUSES = (MATCH_UNMATCHED, MATCH_SUGGESTED, MATCH_MATCHED, MATCH_IGNORED)

DECISION_SUGGESTED = "suggested"
DECISION_CONFIRMED = "confirmed"
DECISION_REJECTED = "rejected"
MATCH_DECISIONS = (DECISION_SUGGESTED, DECISION_CONFIRMED, DECISION_REJECTED)

TARGET_INGREDIENT = "ingredient"
TARGET_PRODUCT = "product"
TARGET_TYPES = (TARGET_INGREDIENT, TARGET_PRODUCT)

STRATEGY_SUPPLIER_LINK = "supplier_link"
STRATEGY_GTIN_LINK = "gtin_link"
STRATEGY_SUPPLIER_SKU = "supplier_sku"
STRATEGY_CODE = "code"
STRATEGY_DESCRIPTION = "description"
STRATEGY_MANUAL = "manual"
MATCH_STRATEGIES = (
    STRATEGY_SUPPLIER_LINK,
    STRATEGY_GTIN_LINK,
    STRATEGY_SUPPLIER_SKU,
    STRATEGY_CODE,
    STRATEGY_DESCRIPTION,
    STRATEGY_MANUAL,
)
DESCRIPTION_MIN_SCORE = Decimal("0.5")

ATTACHMENT_XML = "xml"
ATTACHMENT_PDF = "pdf"
ATTACHMENT_IMAGE = "image"
ATTACHMENT_OTHER = "other"
ATTACHMENT_KINDS = (ATTACHMENT_XML, ATTACHMENT_PDF, ATTACHMENT_IMAGE, ATTACHMENT_OTHER)

MIME_XML = "application/xml"
MIME_XML_TEXT = "text/xml"
MIME_PDF = "application/pdf"
MIME_JPEG = "image/jpeg"
MIME_PNG = "image/png"
ALLOWED_MIME_TYPES = frozenset({MIME_XML, MIME_XML_TEXT, MIME_PDF, MIME_JPEG, MIME_PNG})
MIME_TO_KIND = {
    MIME_XML: ATTACHMENT_XML,
    MIME_XML_TEXT: ATTACHMENT_XML,
    MIME_PDF: ATTACHMENT_PDF,
    MIME_JPEG: ATTACHMENT_IMAGE,
    MIME_PNG: ATTACHMENT_IMAGE,
}
MAX_ATTACHMENT_BYTES = 8 * 1024 * 1024

BASIS_GROSS_AMOUNT = "gross_amount"
BASIS_QUANTITY = "quantity"
ALLOCATION_BASES = (BASIS_GROSS_AMOUNT, BASIS_QUANTITY)

CERT_NOT_CONFIGURED = "not_configured"
CERT_VALIDATING = "validating"
CERT_ACTIVE = "active"
CERT_EXPIRED = "expired"
CERT_REVOKED = "revoked"
CERT_ERROR = "error"
CERTIFICATE_STATUSES = (
    CERT_NOT_CONFIGURED,
    CERT_VALIDATING,
    CERT_ACTIVE,
    CERT_EXPIRED,
    CERT_REVOKED,
    CERT_ERROR,
)

ENV_HOMOLOGATION = "homologation"
ENV_PRODUCTION = "production"
FISCAL_ENVIRONMENTS = (ENV_HOMOLOGATION, ENV_PRODUCTION)

EXTRACTION_STATUSES = ("pending", "completed", "failed")

RECEIPT_SOURCE_ORDER = "order"
RECEIPT_SOURCE_FISCAL = "fiscal"

# Origens de captura expostas à UI (adendo: manual, XML, scan, Fazenda).
CAPTURE_ORIGINS_UI = (ORIGIN_MANUAL, ORIGIN_XML, ORIGIN_SCAN, ORIGIN_DISTRIBUTION)

DEMO_LABEL = "DEMONSTRACAO"
# Identificadores inequívocos fictícios — nunca CNPJ/chave reais.
DEMO_RECIPIENT_TAX_ID = "00000000000191"
DEMO_EMITTER_TAX_ID = "00000000000272"
DEMO_ACCESS_KEY_PREFIX = "9999"  # chaves sintéticas começam com 9999

FISCAL_LIVE_FLAG = "PANNE_FISCAL_LIVE"
OCR_LIVE_FLAG = "PANNE_OCR_LIVE"
DISTRIBUTION_RATE_LIMIT_PER_MINUTE = 30
DISTRIBUTION_BACKOFF_SECONDS = (1, 2, 5, 15, 60)
MAX_ITEMS_PER_DOCUMENT = 500
MAX_XML_DEPTH = 64

EVENT_CAPTURED = "fiscal.document.captured"
EVENT_XML_IMPORTED = "fiscal.document.xml_imported"
EVENT_SCAN_ATTACHED = "fiscal.document.scan_attached"
EVENT_MATCH_SUGGESTED = "fiscal.document.match_suggested"
EVENT_MATCH_CONFIRMED = "fiscal.document.match_confirmed"
EVENT_PHYSICAL_RECORDED = "fiscal.document.physical_recorded"
EVENT_CONFIRMED = "fiscal.document.confirmed"
EVENT_CANCELLED = "fiscal.document.cancelled"
EVENT_REFUSED = "fiscal.document.refused"
