const photos=['https://images.unsplash.com/photo-1670843837159-ddae2ec115d4?auto=format&fit=crop&w=1600&q=85','https://images.unsplash.com/photo-1767542562849-fb66d57f8da3?auto=format&fit=crop&w=1200&q=85','https://images.unsplash.com/photo-1767065887079-2df64aae8ace?auto=format&fit=crop&w=1200&q=85'];
const masses=[['Sourdough clássico','Fermentação de 24h, miolo macio e acidez equilibrada.','A ESSÊNCIA DA CASA'],['Integral','Sabor profundo de cereais, com miolo mais denso e acolhedor.','RÚSTICO E NUTRITIVO'],['Multigrãos','Uma mistura de sementes para textura em cada fatia.','TEXTURA QUE SURPREENDE']];
const ingredients=['Nozes','Damasco','Azeitonas','Alecrim'];const forms=[['Rústico de cesto','Crosta marcante, desenho de farinha e fatias generosas.'],['Pão de forma','Topo abaulado e fatias regulares para os seus rituais.']];
let step=0,mass=0,extras=new Set(),shape=0,date='',time='',finished=false;
const earliest=new Date();earliest.setDate(earliest.getDate()+2);earliest.setHours(0,0,0,0);let month=new Date(earliest.getFullYear(),earliest.getMonth(),1);
const content=document.querySelector('#step-content'),next=document.querySelector('#next'),back=document.querySelector('#back');
const dateKey=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;
const prettyDate=()=>date?new Date(date+'T12:00:00').toLocaleDateString('pt-BR',{weekday:'long',day:'numeric',month:'long'}):'';
function option(title,desc,selected,attr,tag=''){return `<button class="option ${selected?'selected':''}" aria-pressed="${selected}" ${attr}><span class="radio" aria-hidden="true"></span><span><h3>${title}</h3>${desc?`<p>${desc}</p>`:''}${tag?`<span class="tag">${tag}</span>`:''}</span></button>`}
function render(focus=false){document.querySelector('.steps').innerHTML=['A essência','Seu toque','A forma','O encontro'].map((s,i)=>`<div class="step ${i===step?'current':i<step?'done':''}" ${i===step?'aria-current="step"':''}><i>${i<step?'✓':i+1}</i><span>${s}</span></div>`).join('');
document.querySelector('#preview-image').src=photos[mass===0?0:mass===1?1:2];document.querySelector('#preview-title').innerHTML=step===0?'Simples na essência.<br>Extraordinário no sabor.':masses[mass][0];document.querySelector('#preview-kicker').textContent=step===0?'O começo de uma boa história':'A sua próxima fornada';document.querySelector('#summary').textContent=step===0?'Farinha, água, sal e um levain cheio de vida.':`${masses[mass][0]} · ${extras.size?[...extras].join(', '):'Sem inclusões'}${step>=2?' · '+forms[shape][0]:''}${date?' · '+prettyDate():''}${time?' · '+time:''}`;
back.style.visibility=step===0?'hidden':'visible';back.hidden=finished;next.hidden=finished;next.disabled=false;document.querySelector('#step-label').textContent=`${step+1} de 4 passos`;
if(finished){content.innerHTML=`<div class="success"><div class="success-mark">✓</div><p class="step-eyebrow">SUA COMBINAÇÃO ESTÁ PRONTA</p><h2>Uma boa história para assar.</h2><p class="desc">Você criou um pão com o seu toque. Guarde esta inspiração para a próxima fornada.</p><div class="receipt"><strong>${masses[mass][0]}</strong><br>${extras.size?[...extras].join(' + '):'Sem inclusões'}<br>${forms[shape][0]}<br>${prettyDate()} · ${time}</div><p class="demo">Esta é uma simulação. Nenhum pedido foi enviado, cobrado ou agendado. Os horários são ilustrativos.</p><button id="restart" class="text-button">Criar outra combinação →</button></div>`;document.querySelector('#restart').onclick=()=>{step=0;mass=0;extras.clear();shape=0;date='';time='';finished=false;render(true)};return}
const headings=['Comece pela essência.','Um toque que é só seu.','A forma também conta.','O tempo de um bom encontro.'];const descriptions=['Escolha a massa que vai dar vida ao seu pão.','Escolha os sabores — ou deixe a massa brilhar sozinha.','Cada formato traz um jeito diferente de partir e compartilhar.','Imagine sua próxima fornada. Escolha uma data e um horário.'];content.innerHTML=`<p class="step-eyebrow">PASSO 0${step+1}</p><h2>${headings[step]}</h2><p class="desc">${descriptions[step]}</p>`;
if(step===0){content.innerHTML+=`<div class="options">${masses.map((m,i)=>option(m[0],m[1],mass===i,`data-mass="${i}"`,mass===i?m[2]:'')).join('')}</div>`;content.querySelectorAll('[data-mass]').forEach(b=>b.onclick=()=>{mass=+b.dataset.mass;render()});next.innerHTML='Escolher os sabores <span>→</span>'}
if(step===1){content.innerHTML+=`<div class="ingredient-grid">${ingredients.map((v,i)=>option(v,['Crocância delicada','Doçura e maciez','Sabor salgado','Aroma do jardim'][i],extras.has(v),`data-extra="${v}"`)).join('')}</div><div class="tip" aria-live="polite"><strong>Dica do padeiro</strong><br>${extras.has('Alecrim')&&extras.has('Damasco')?'O alecrim tem aroma intenso. Use pouco para deixar a doçura do damasco aparecer.':extras.size>2?'Muitos sabores na mesma massa? Experimente escolher dois para sentir cada ingrediente.':extras.has('Nozes')?'Nozes e damasco fazem uma dupla de textura e doçura.':extras.has('Alecrim')?'Alecrim e azeitonas combinam com uma fatia ainda morna.':'Até dois ingredientes costumam criar uma combinação equilibrada.'}</div><p class="demo">Contém glúten. Nozes são oleaginosas. Informações sobre alergênicos precisam ser confirmadas pela padaria.</p>`;content.querySelectorAll('[data-extra]').forEach(b=>b.onclick=()=>{extras.has(b.dataset.extra)?extras.delete(b.dataset.extra):extras.add(b.dataset.extra);render()});next.innerHTML='Escolher a forma <span>→</span>'}
if(step===2){content.innerHTML+=`<div class="options">${forms.map((v,i)=>option(v[0],v[1],shape===i,`data-shape="${i}"`)).join('')}</div><div class="tip">${shape===0?'O cesto dá apoio à massa e deixa as espirais de farinha na crosta. Um pão para compartilhar no centro da mesa.':'A forma sustenta o crescimento da massa. O resultado são fatias práticas para torradas e sanduíches.'}</div>`;content.querySelectorAll('[data-shape]').forEach(b=>b.onclick=()=>{shape=+b.dataset.shape;render()});next.innerHTML='Combinar o encontro <span>→</span>'}
if(step===3){const last=new Date(month.getFullYear(),month.getMonth()+1,0).getDate();let days='';for(let i=0;i<month.getDay();i++)days+='<span></span>';for(let d=1;d<=last;d++){const value=new Date(month.getFullYear(),month.getMonth(),d),key=dateKey(value);days+=`<button class="day ${date===key?'selected':''}" data-date="${key}" ${value<earliest?'disabled':''} aria-pressed="${date===key}" aria-label="${value.toLocaleDateString('pt-BR',{day:'numeric',month:'long',year:'numeric'})}">${d}</button>`}content.innerHTML+=`<div class="calendar-head"><button id="prev-month" aria-label="Mês anterior" ${month<=new Date(earliest.getFullYear(),earliest.getMonth(),1)?'disabled':''}>‹</button><strong>${month.toLocaleDateString('pt-BR',{month:'long',year:'numeric'})}</strong><button id="next-month" aria-label="Próximo mês">›</button></div><div class="calendar">${['D','S','T','Q','Q','S','S'].map(d=>`<span>${d}</span>`).join('')}${days}</div><div class="times" aria-label="Horário de recebimento">${['8h–10h','10h–12h','14h–16h'].map(t=>`<button class="time ${t===time?'selected':''}" aria-pressed="${t===time}" data-time="${t}">${t}</button>`).join('')}</div><p class="demo">Calendário demonstrativo, com pelo menos dois dias para o preparo. Disponibilidade e entrega ainda não estão conectadas à padaria.</p>`;document.querySelector('#prev-month').onclick=()=>{month.setMonth(month.getMonth()-1);render()};document.querySelector('#next-month').onclick=()=>{month.setMonth(month.getMonth()+1);render()};content.querySelectorAll('[data-date]').forEach(b=>b.onclick=()=>{date=b.dataset.date;render()});content.querySelectorAll('[data-time]').forEach(b=>b.onclick=()=>{time=b.dataset.time;render()});next.disabled=!date||!time;next.innerHTML='Concluir minha criação <span>→</span>'}
if(focus)content.focus();}
next.onclick=()=>{if(step<3)step++;else if(date&&time)finished=true;render(true)};back.onclick=()=>{if(step>0)step--;render(true)};
const stories=[['O RITUAL DA MANHÃ','Uma fatia. Um café. Uma pausa.','Pão de fermentação natural, manteiga e um começo sem pressa.'],['DA CROSTA AO MIOLO','O encanto dos pequenos detalhes.','Sementes, texturas e sabores que transformam uma fatia.'],['FEITO COM AS MÃOS','Cada corte, uma assinatura.','A beleza de uma fornada que nunca sai igual à outra.']];
document.querySelector('#gallery').innerHTML=stories.map((s,i)=>`<article class="story"><img src="${photos[i]}" loading="lazy" alt="${['Pão rústico sobre tábua de madeira','Detalhe de pão com grãos e sementes','Pão artesanal com desenho na crosta'][i]}"><small>${s[0]}</small><h3>${s[1]}</h3><p>${s[2]}</p></article>`).join('');
const articles=[['Levain: um ingrediente vivo','O levain é uma cultura de farinha e água que abriga leveduras e bactérias. Com alimento e tempo, ele fermenta a massa e participa da construção de aroma, sabor e textura.','Alimentar o levain significa renovar parte da cultura com farinha e água. O ritmo muda com a temperatura, o tipo de farinha e a proporção usada. Observe o crescimento, as bolhas e o aroma para conhecer o seu.','Para começar, siga uma receita com quantidades e horários definidos, usando um recipiente limpo. Aprender a ler os sinais da cultura é mais útil do que correr contra o relógio.'],['A delicadeza de uma boa dobra','As dobras ajudam a organizar a estrutura da massa durante a fermentação. O gesto é simples: levantar uma lateral com delicadeza e dobrá-la sobre o centro.','Com as mãos levemente úmidas, repita o gesto nas outras laterais. Evite rasgar a massa. Depois, cubra e deixe descansar conforme a receita, para que ela relaxe antes da próxima série.','A massa muda a cada descanso. Mais coesão e elasticidade são sinais para observar; o número de dobras depende da farinha, da hidratação e do processo escolhido.'],['Como guardar seu pão','Espere o pão esfriar antes de guardá-lo. O vapor preso em uma embalagem pode deixar a crosta úmida. No dia a dia, um local seco e protegido ajuda a preservar a qualidade.','Para guardar por mais tempo, corte em fatias e congele em uma embalagem bem fechada. Assim, você retira apenas o que vai comer e aquece direto na torradeira ou no forno.','A geladeira costuma acelerar o ressecamento do miolo. Se aparecer mofo, descarte o pão inteiro: retirar apenas a parte visível não é suficiente.']];
const dialog=document.querySelector('#reading');document.querySelectorAll('[data-article]').forEach(b=>b.onclick=()=>{const a=articles[+b.dataset.article];document.querySelector('#reading-body').innerHTML=`<p class="eyebrow">BIBLIOTECA DO PADEIRO</p><h2>${a[0]}</h2>${a.slice(1).map(p=>`<p>${p}</p>`).join('')}`;dialog.showModal()});dialog.querySelector('.close').onclick=()=>dialog.close();dialog.onclick=e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}};
render();
