actionfinance.demo-auth.enabled=false
actionfinance.oidc.enabled=true
actionfinance.session.cookie-secure=false
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=never
spring.session.jdbc.table-name=actionfinance.SPRING_SESSION
spring.session.timeout=30m
server.servlet.session.timeout=30m
server.servlet.session.cookie.secure=false
spring.web.resources.add-mappings=false
