"""Dicionário canônico de métricas. Fórmulas soberanas ficam nos domínios de origem."""

from dataclasses import dataclass

from app.modules.reporting_analytics.constants import METRICS_VERSION


@dataclass(frozen=True)
class MetricSpec:
    code: str
    name: str
    description: str
    version: str
    unit: str
    numerator: str
    denominator: str
    filters: tuple[str, ...]
    include: str
    exclude: str
    absence: str
    precision: int
    drill_down: str
    origins: tuple[str, ...]


COMMON_FILTERS = (
    "period",
    "timezone",
    "establishment_id",
    "technical_product_id",
    "formulation_version_id",
    "status",
)


def _metric(**kwargs) -> MetricSpec:
    return MetricSpec(version=METRICS_VERSION, **kwargs)


METRICS: dict[str, MetricSpec] = {
    "orders_by_status": _metric(
        code="orders_by_status",
        name="Ordens por estado",
        description="Contagem de ordens sem colapsar estados.",
        unit="count",
        numerator="ordens no estado",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="ordens cujo âncora temporal cai em [início, fim)",
        exclude="ordens de outra organização",
        absence="estado sem ordem é ausência, não zero implícito de volume",
        precision=0,
        drill_down="production_order",
        origins=("production_order",),
    ),
    "planned_quantity": _metric(
        code="planned_quantity",
        name="Quantidade planejada",
        description="Soma de target_quantity apenas em unidade compatível.",
        unit="mixed",
        numerator="target_quantity",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="ordens do período com a mesma unidade de modo",
        exclude="modos incompatíveis no mesmo agregado",
        absence="sem ordem ou unidade mista: indisponível",
        precision=6,
        drill_down="production_order",
        origins=("production_order",),
    ),
    "actual_quantity": _metric(
        code="actual_quantity",
        name="Quantidade realizada",
        description="Unidades vendáveis ou massa pós-forno quando medidas.",
        unit="mixed",
        numerator="good_units ou post_bake_mass",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="medições de rendimento do período",
        exclude="medições revertidas",
        absence="ordem sem rendimento não vira zero",
        precision=6,
        drill_down="production_yield_measurement",
        origins=("production_yield_measurement",),
    ),
    "normal_completion_rate": _metric(
        code="normal_completion_rate",
        name="Taxa de conclusão normal",
        description="Concluídas / (concluídas + encerradas parcialmente).",
        unit="percent",
        numerator="ordens completed",
        denominator="completed + short_closed",
        filters=COMMON_FILTERS,
        include="ordens encerradas no período",
        exclude="canceladas e em aberto",
        absence="denominador vazio: indisponível",
        precision=4,
        drill_down="production_order",
        origins=("production_order",),
    ),
    "short_close_rate": _metric(
        code="short_close_rate",
        name="Taxa de encerramento parcial",
        description="short_closed / (completed + short_closed).",
        unit="percent",
        numerator="ordens short_closed",
        denominator="completed + short_closed",
        filters=COMMON_FILTERS,
        include="ordens encerradas no período",
        exclude="canceladas e em aberto",
        absence="denominador vazio: indisponível",
        precision=4,
        drill_down="production_order",
        origins=("production_order",),
    ),
    "quantity_adherence": _metric(
        code="quantity_adherence",
        name="Aderência de quantidade",
        description="Realizado elegível / planejado da mesma unidade.",
        unit="percent",
        numerator="quantidade realizada com rendimento",
        denominator="quantidade planejada das mesmas ordens",
        filters=COMMON_FILTERS,
        include="ordens com rendimento e unidade compatível",
        exclude="ordens sem rendimento no denominador ponderado",
        absence="sem par planejado/realizado: indisponível",
        precision=4,
        drill_down="production_order",
        origins=("production_order", "production_yield_measurement"),
    ),
    "net_consumption": _metric(
        code="net_consumption",
        name="Consumo líquido",
        description="consume − return, com waste e correction à parte.",
        unit="mass",
        numerator="consume − return na unidade canônica",
        denominator="não aplicável",
        filters=COMMON_FILTERS + ("ingredient_id",),
        include="fatos de consumo no período",
        exclude="unidades incompatíveis no mesmo agregado",
        absence="sem fato: indisponível",
        precision=6,
        drill_down="production_material_consumption",
        origins=("production_material_consumption", "production_order_material"),
    ),
    "consumption_variance": _metric(
        code="consumption_variance",
        name="Variação de consumo",
        description="(líquido − planejado) / planejado quando o planejado existe.",
        unit="percent",
        numerator="consumo líquido − planejado",
        denominator="quantidade planejada bruta",
        filters=COMMON_FILTERS + ("ingredient_id",),
        include="pares com unidade compatível",
        exclude="planejado ausente",
        absence="sem planejado: indisponível, não 0%",
        precision=4,
        drill_down="production_order_material",
        origins=("production_order_material", "production_material_consumption"),
    ),
    "yield_actual": _metric(
        code="yield_actual",
        name="Rendimento realizado",
        description="massa pós-forno / massa pré-forno quando ambas existem.",
        unit="percent",
        numerator="post_bake_mass",
        denominator="pre_bake_mass",
        filters=COMMON_FILTERS,
        include="bateladas com o par pré e pós",
        exclude="pares incompletos do denominador",
        absence="par incompleto: cobertura, não zero",
        precision=4,
        drill_down="production_yield_measurement",
        origins=("production_yield_measurement",),
    ),
    "loss_actual": _metric(
        code="loss_actual",
        name="Perda realizada",
        description="1 − rendimento quando o rendimento existe.",
        unit="percent",
        numerator="pré − pós",
        denominator="pre_bake_mass",
        filters=COMMON_FILTERS,
        include="mesmo conjunto do rendimento",
        exclude="pares incompletos",
        absence="sem par: indisponível",
        precision=4,
        drill_down="production_yield_measurement",
        origins=("production_yield_measurement",),
    ),
    "cost_variance": _metric(
        code="cost_variance",
        name="Variação de custo",
        description="realizado − previsto no mesmo recorte e moeda BRL.",
        unit="BRL",
        numerator="total realizado completo",
        denominator="não aplicável à taxa; comparação usa pares",
        filters=COMMON_FILTERS + ("cost_category",),
        include="cálculos complete do período",
        exclude="parcial, insufficient_data e moeda ≠ BRL",
        absence="sem par: indisponível; parcial não vira zero",
        precision=6,
        drill_down="costing_calculation",
        origins=("costing_calculation", "costing_component"),
    ),
    "cost_per_sellable_unit": _metric(
        code="cost_per_sellable_unit",
        name="Custo por unidade vendável",
        description="Reusa sellable_unit_amount do cálculo 021 quando presente.",
        unit="BRL/unit",
        numerator="total do cálculo",
        denominator="quantidade vendável persistida",
        filters=COMMON_FILTERS,
        include="cálculos com sellable_unit_amount",
        exclude="cálculos sem rendimento vendável",
        absence="sem sellable: indisponível",
        precision=6,
        drill_down="costing_calculation",
        origins=("costing_calculation",),
    ),
    "markup_percent": _metric(
        code="markup_percent",
        name="Markup",
        description="Fórmula soberana do CURSOR-021: (preço/custo − 1) × 100.",
        unit="percent",
        numerator="preço − custo",
        denominator="custo-base",
        filters=COMMON_FILTERS + ("price_channel",),
        include="preço praticado com custo associado",
        exclude="simulação parcial sem confirmação no detalhe",
        absence="sem custo ou preço: indisponível",
        precision=4,
        drill_down="practiced_price",
        origins=("practiced_price", "pricing_simulation", "costing_calculation"),
    ),
    "gross_margin": _metric(
        code="gross_margin",
        name="Margem bruta",
        description="Fórmula soberana 021: (preço − custo) / preço.",
        unit="percent",
        numerator="preço − custo para margem bruta",
        denominator="preço",
        filters=COMMON_FILTERS + ("price_channel",),
        include="preço > 0 com custo",
        exclude="preço nulo",
        absence="indisponível, não 0%",
        precision=4,
        drill_down="practiced_price",
        origins=("practiced_price", "costing_calculation"),
    ),
    "contribution_margin": _metric(
        code="contribution_margin",
        name="Margem de contribuição",
        description="Fórmula soberana 021: (preço − variáveis) / preço.",
        unit="percent",
        numerator="preço − produto variável − venda variável",
        denominator="preço",
        filters=COMMON_FILTERS + ("price_channel",),
        include="simulação ou preço com variáveis conhecidas",
        exclude="variáveis ausentes",
        absence="indisponível",
        precision=4,
        drill_down="pricing_simulation",
        origins=("pricing_simulation",),
    ),
    "price_coverage": _metric(
        code="price_coverage",
        name="Cobertura de preço",
        description="Itens com preço vigente / universo de ingredientes ativos.",
        unit="percent",
        numerator="ingredientes com preço observado vigente",
        denominator="ingredientes ativos da organização",
        filters=("period", "timezone", "ingredient_id", "supplier_id"),
        include="identidades ativas",
        exclude="inativas",
        absence="universo vazio: indisponível",
        precision=4,
        drill_down="ingredient",
        origins=("ingredient", "supplier_item_price"),
    ),
    "yield_coverage": _metric(
        code="yield_coverage",
        name="Cobertura de rendimento",
        description="Ordens encerradas com par pré/pós ou unidades / universo encerrado.",
        unit="percent",
        numerator="ordens encerradas com rendimento",
        denominator="ordens completed + short_closed",
        filters=COMMON_FILTERS,
        include="encerradas no período",
        exclude="abertas e canceladas",
        absence="sem encerradas: indisponível",
        precision=4,
        drill_down="production_order",
        origins=("production_order", "production_yield_measurement"),
    ),
    "nutrition_coverage": _metric(
        code="nutrition_coverage",
        name="Cobertura nutricional",
        description="Versões publicadas com nutrientes obrigatórios presentes.",
        unit="percent",
        numerator="versões publicadas com proteína valorada",
        denominator="versões publicadas",
        filters=("period",),
        include="ingredient_version published",
        exclude="rascunho e retired",
        absence="sem publicadas: indisponível",
        precision=4,
        drill_down="ingredient_version",
        origins=("ingredient_version", "ingredient_nutrient"),
    ),
    "compliance_coverage": _metric(
        code="compliance_coverage",
        name="Cobertura da avaliação de conformidade",
        description="Dossiês com avaliação / dossiês do período. Não é certificado.",
        unit="percent",
        numerator="dossiês com labeling_assessment",
        denominator="dossiês do recorte",
        filters=COMMON_FILTERS + ("compliance_status",),
        include="dossiês da organização",
        exclude="nada tratado como selo",
        absence="sem dossiê: indisponível",
        precision=4,
        drill_down="labeling_dossier",
        origins=("labeling_dossier", "labeling_assessment"),
    ),
    "data_coverage": _metric(
        code="data_coverage",
        name="Cobertura geral de dados",
        description="Média ponderada das coberturas disponíveis, nunca soma de percentuais.",
        unit="percent",
        numerator="soma dos numeradores das coberturas presentes",
        denominator="soma dos denominadores das coberturas presentes",
        filters=("period",),
        include="coberturas com denominador",
        exclude="coberturas indisponíveis",
        absence="nenhuma cobertura: indisponível",
        precision=4,
        drill_down="reporting_coverage_item",
        origins=("ingredient", "production_order", "labeling_dossier", "costing_calculation"),
    ),
    "physical_on_hand": _metric(
        code="physical_on_hand",
        name="Saldo físico",
        description="Soma das movimentações efetivas por item, local e lote.",
        unit="mixed",
        numerator="physical_quantity",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="saldos projetados do ledger",
        exclude="reservas e pedidos em trânsito",
        absence="sem lote ou movimento: ausência, não zero presumido",
        precision=6,
        drill_down="inventory_balance",
        origins=("inventory_movement", "inventory_balance"),
    ),
    "available_quantity": _metric(
        code="available_quantity",
        name="Disponível",
        description="Saldo físico menos reservas ativas.",
        unit="mixed",
        numerator="physical_quantity - reserved_quantity",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="projeção reconciliável com o ledger",
        exclude="em trânsito",
        absence="sem saldo projetado: ausência",
        precision=6,
        drill_down="inventory_balance",
        origins=("inventory_balance", "inventory_reservation"),
    ),
    "reserved_quantity": _metric(
        code="reserved_quantity",
        name="Reservado",
        description="Quantidade comprometida com ordens, ainda fisicamente presente.",
        unit="mixed",
        numerator="reserved_quantity",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="reservas ativas",
        exclude="reservas liberadas ou consumidas",
        absence="sem reserva: ausência",
        precision=6,
        drill_down="inventory_reservation",
        origins=("inventory_reservation",),
    ),
    "in_transit_quantity": _metric(
        code="in_transit_quantity",
        name="Em trânsito",
        description="Pedido emitido e ainda não recebido. Não compõe saldo físico.",
        unit="mixed",
        numerator="quantidade emitida menos recebida",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="pedidos issued ou partially_received",
        exclude="rascunho e cancelado",
        absence="sem pedido emitido: ausência",
        precision=6,
        drill_down="procurement_order",
        origins=("procurement_order", "procurement_receipt"),
    ),
    "expiring_lots": _metric(
        code="expiring_lots",
        name="Lotes com validade próxima",
        description="Lotes disponíveis com validade no horizonte de alerta da política.",
        unit="count",
        numerator="lotes no horizonte",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="expires_on informada",
        exclude="validade ausente nunca é inferida",
        absence="sem validade informada: ausência",
        precision=0,
        drill_down="inventory_lot",
        origins=("inventory_lot",),
    ),
    "blocked_lots": _metric(
        code="blocked_lots",
        name="Lotes bloqueados",
        description="Lotes em quarentena, bloqueio, vencidos ou encerrados.",
        unit="count",
        numerator="lotes bloqueados",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="status distinto de available",
        exclude="available",
        absence="sem lote bloqueado: ausência",
        precision=0,
        drill_down="inventory_lot",
        origins=("inventory_lot",),
    ),
    "count_variance": _metric(
        code="count_variance",
        name="Divergência de inventário",
        description="Diferença entre contagem e esperado no corte. Sem edição de saldo.",
        unit="mixed",
        numerator="contado - esperado",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="sessões fechadas do período",
        exclude="saldo editado diretamente",
        absence="sem inventário: ausência",
        precision=6,
        drill_down="inventory_count_session",
        origins=("inventory_count_entry", "inventory_count_scope"),
    ),
    "replenishment_need": _metric(
        code="replenishment_need",
        name="Necessidade de reposição",
        description="Itens cuja sugestão determinística é maior que zero.",
        unit="count",
        numerator="itens com suggested_quantity > 0",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="última sugestão da organização",
        exclude="compra automática",
        absence="sem sugestão gerada: ausência",
        precision=0,
        drill_down="inventory_replenishment_item",
        origins=("inventory_replenishment_item",),
    ),
    "inventory_data_quality": _metric(
        code="inventory_data_quality",
        name="Qualidade dos dados de estoque",
        description="Itens sem ponto de reposição, lote sem validade quando exigida, ou postagem pendente.",
        unit="count",
        numerator="pendências acionáveis",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="lacunas explícitas",
        exclude="zero presumido",
        absence="sem pendência: ausência de fato",
        precision=0,
        drill_down="inventory_item",
        origins=("inventory_item", "inventory_lot", "inventory_consumption_posting"),
    ),
    "blocking_occurrences": _metric(
        code="blocking_occurrences",
        name="Ocorrências bloqueantes",
        description="Contagem de ocorrências abertas bloqueantes. Sem ranking de ator.",
        unit="count",
        numerator="ocorrências open bloqueantes",
        denominator="não aplicável",
        filters=COMMON_FILTERS,
        include="production_occurrence no período",
        exclude="resolvidas",
        absence="sem ocorrência: ausência de fato, o cartão informa cobertura",
        precision=0,
        drill_down="production_occurrence",
        origins=("production_occurrence",),
    ),
}
