package br.com.banco.spider.operational.health;

public enum HealthDimensionCode {
  EXECUTION_FLOW,
  EXECUTION_LATENCY,
  ASYNC_WAIT,
  CALLBACK_DELIVERY,
  SIGNAL_INGRESS,
  TELEMETRY_COVERAGE,
  WORKER_RUNTIME,
  SCHEDULING,
  BACKLOG,
  LEASE_SAFETY,
  CAPACITY,
  BACKPRESSURE,
  BULKHEAD_SAFETY,
  CIRCUIT_HEALTH
}
