package br.com.banco.spider.governance;

public enum GovernanceArtifactType {
  ROUTE_DEFINITION,
  RETRY_POLICY,
  WAIT_POLICY,
  CALLBACK_DEFINITION,
  CALLBACK_DELIVERY_POLICY,
  CALLBACK_RECONCILIATION_POLICY,
  INTEGRITY_PROFILE,
  ADAPTER_BINDING_DESCRIPTOR,
  CALLBACK_BINDING_DESCRIPTOR,
  STATUS_QUERY_BINDING_DESCRIPTOR,
  EXTERNAL_SIGNAL_DEFINITION,
  DATA_PROTECTION_PROFILE
}
