"""Autorização interna por permissão explícita. Grupos do IdP não são canônicos."""

from dataclasses import dataclass
from uuid import UUID

PERMISSION_IDENTITY_READ_ME = "identity.read_me"
PERMISSION_ORGANIZATION_READ = "organization.read"
PERMISSION_MEMBERSHIP_READ = "membership.read"
PERMISSION_MEMBERSHIP_ROLE_MANAGE = "membership.role.manage"
PERMISSION_COMPLIANCE_REVIEW = "compliance.review"
PERMISSION_PRODUCTION_PLAN_READ = "production.plan.read"
PERMISSION_PRODUCTION_PLAN_MANAGE = "production.plan.manage"
PERMISSION_PRODUCTION_ORDER_READ = "production.order.read"
PERMISSION_PRODUCTION_ORDER_MANAGE = "production.order.manage"
PERMISSION_PRODUCTION_ORDER_RELEASE = "production.order.release"
PERMISSION_PRODUCTION_ORDER_CANCEL = "production.order.cancel"
PERMISSION_PRODUCTION_BATCH_MANAGE = "production.batch.manage"
PERMISSION_PRODUCTION_BOARD_READ = "production.board.read"
PERMISSION_PRODUCTION_WEIGHING_RECORD = "production.weighing.record"
PERMISSION_PRODUCTION_WEIGHING_VERIFY = "production.weighing.verify"
PERMISSION_PRODUCTION_CONSUMPTION_RECORD = "production.consumption.record"
PERMISSION_PRODUCTION_STEP_EXECUTE = "production.step.execute"
PERMISSION_PRODUCTION_OCCURRENCE_RECORD = "production.occurrence.record"
PERMISSION_PRODUCTION_OCCURRENCE_RESOLVE = "production.occurrence.resolve"
PERMISSION_PRODUCTION_BATCH_COMPLETE = "production.batch.complete"
PERMISSION_PRODUCTION_ORDER_COMPLETE = "production.order.complete"
PERMISSION_PRODUCTION_ORDER_SHORT_CLOSE = "production.order.short_close"
PERMISSION_PRODUCTION_SHEET_ISSUE = "production.sheet.issue"
PERMISSION_PRODUCTION_TRACEABILITY_READ = "production.traceability.read"
PERMISSION_PRODUCTION_ORDER_POLICY_ADOPT = "production.order.policy_adopt"
PERMISSION_INGREDIENT_READ = "ingredient.read"
PERMISSION_INGREDIENT_CREATE = "ingredient.create"
PERMISSION_INGREDIENT_UPDATE_DRAFT = "ingredient.update_draft"
PERMISSION_INGREDIENT_PUBLISH = "ingredient.publish"
PERMISSION_INGREDIENT_RETIRE = "ingredient.retire"
PERMISSION_SUPPLIER_READ = "supplier.read"
PERMISSION_SUPPLIER_MANAGE = "supplier.manage"
PERMISSION_SUPPLIER_PRICE_RECORD = "supplier.price.record"
PERMISSION_RECIPE_READ = "recipe.read"
PERMISSION_RECIPE_CREATE = "recipe.create"
PERMISSION_RECIPE_UPDATE_DRAFT = "recipe.update_draft"
PERMISSION_RECIPE_VERSION_CREATE = "recipe.version.create"
PERMISSION_RECIPE_SCALE = "recipe.scale"
PERMISSION_RECIPE_TRIAL_MANAGE = "recipe.trial.manage"
PERMISSION_RECIPE_REVIEW = "recipe.review"
PERMISSION_RECIPE_APPROVE = "recipe.approve"
PERMISSION_RECIPE_PUBLISH = "recipe.publish"
PERMISSION_RECIPE_RETIRE = "recipe.retire"
PERMISSION_RECIPE_REFERENCE_MANAGE = "recipe.reference.manage"
PERMISSION_RECIPE_TECHNICAL_SHEET_READ = "recipe.technical_sheet.read"
PERMISSION_RECIPE_AI_PROPOSE = "recipe.ai.propose"
PERMISSION_RECIPE_AI_REVIEW = "recipe.ai.review"
PERMISSION_RECIPE_AI_MATERIALIZE = "recipe.ai.materialize"
PERMISSION_PRODUCT_READ = "product.read"
PERMISSION_PRODUCT_CREATE = "product.create"
PERMISSION_PRODUCT_UPDATE = "product.update"
PERMISSION_PRODUCT_ACTIVATE = "product.activate"
PERMISSION_PRODUCT_FAMILY_MANAGE = "product.family.manage"
PERMISSION_LABELING_READ = "labeling.read"
PERMISSION_LABELING_DOSSIER_CREATE = "labeling.dossier.create"
PERMISSION_LABELING_EVALUATE = "labeling.evaluate"
PERMISSION_LABELING_CANDIDATE_EDIT = "labeling.candidate.edit"
PERMISSION_LABELING_REVIEW = "labeling.review"
PERMISSION_LABELING_RENDER = "labeling.render"
PERMISSION_LABELING_INVALIDATE = "labeling.invalidate"
PERMISSION_REGULATORY_SOURCE_READ = "regulatory.source.read"
PERMISSION_COSTING_READ = "costing.read"
PERMISSION_COSTING_POLICY_MANAGE = "costing.policy.manage"
PERMISSION_COSTING_ASSUMPTION_MANAGE = "costing.assumption.manage"
PERMISSION_COSTING_CALCULATE_PLANNED = "costing.calculate.planned"
PERMISSION_COSTING_CALCULATE_ACTUAL = "costing.calculate.actual"
PERMISSION_PRICING_SIMULATION_MANAGE = "pricing.simulation.manage"
PERMISSION_PRICING_REVIEW = "pricing.review"
PERMISSION_PRICING_PUBLISH = "pricing.publish"
PERMISSION_PRICING_POLICY_MANAGE = "pricing.policy.manage"
PERMISSION_PRICING_AUDIT_READ = "pricing.audit.read"
PERMISSION_REPORTING_DASHBOARD_READ = "reporting.dashboard.read"
PERMISSION_REPORTING_PRODUCTION_READ = "reporting.production.read"
PERMISSION_REPORTING_TRACEABILITY_READ = "reporting.traceability.read"
PERMISSION_REPORTING_COSTING_READ = "reporting.costing.read"
PERMISSION_REPORTING_PRICING_READ = "reporting.pricing.read"
PERMISSION_REPORTING_COMPLIANCE_READ = "reporting.compliance.read"
PERMISSION_REPORTING_DATA_QUALITY_READ = "reporting.data_quality.read"
PERMISSION_REPORTING_SNAPSHOT_CREATE = "reporting.snapshot.create"
PERMISSION_REPORTING_EXPORT = "reporting.export"
PERMISSION_REPORTING_SAVED_VIEW_MANAGE = "reporting.saved_view.manage"
PERMISSION_REPORTING_INVENTORY_READ = "reporting.inventory.read"
PERMISSION_INVENTORY_READ = "inventory.read"
PERMISSION_INVENTORY_POLICY_MANAGE = "inventory.policy.manage"
PERMISSION_INVENTORY_ITEM_MANAGE = "inventory.item.manage"
PERMISSION_INVENTORY_LOT_MANAGE = "inventory.lot.manage"
PERMISSION_INVENTORY_RESERVE = "inventory.reserve"
PERMISSION_INVENTORY_SEPARATE = "inventory.separate"
PERMISSION_INVENTORY_MOVE = "inventory.move"
PERMISSION_INVENTORY_ADJUST = "inventory.adjust"
PERMISSION_INVENTORY_COUNT = "inventory.count"
PERMISSION_INVENTORY_COUNT_APPROVE = "inventory.count.approve"
PERMISSION_INVENTORY_EXPIRED_OVERRIDE = "inventory.expired.override"
PERMISSION_PROCUREMENT_READ = "procurement.read"
PERMISSION_PROCUREMENT_REQUISITION_CREATE = "procurement.requisition.create"
PERMISSION_PROCUREMENT_REQUISITION_APPROVE = "procurement.requisition.approve"
PERMISSION_PROCUREMENT_QUOTATION_MANAGE = "procurement.quotation.manage"
PERMISSION_PROCUREMENT_ORDER_MANAGE = "procurement.order.manage"
PERMISSION_PROCUREMENT_ORDER_APPROVE = "procurement.order.approve"
PERMISSION_PROCUREMENT_RECEIVE = "procurement.receive"
PERMISSION_PROCUREMENT_RETURN = "procurement.return"
PERMISSION_FISCAL_DOCUMENT_READ = "fiscal.document.read"
PERMISSION_FISCAL_DOCUMENT_CAPTURE = "fiscal.document.capture"
PERMISSION_FISCAL_DOCUMENT_MATCH = "fiscal.document.match"
PERMISSION_FISCAL_DOCUMENT_CHECK = "fiscal.document.check"
PERMISSION_FISCAL_DOCUMENT_CONFIRM = "fiscal.document.confirm"
PERMISSION_FISCAL_PRICE_READ = "fiscal.price.read"
PERMISSION_FISCAL_INTEGRATION_MANAGE = "fiscal.integration.manage"

FOUNDATION_PERMISSIONS = (
    (PERMISSION_IDENTITY_READ_ME, "Ler o próprio perfil autenticado"),
    (PERMISSION_ORGANIZATION_READ, "Ler a organização da associação ativa"),
    (PERMISSION_MEMBERSHIP_READ, "Ler associações ativas do próprio usuário"),
    (PERMISSION_COMPLIANCE_REVIEW, "Revisar avaliações de conformidade"),
)
API_PERMISSION_DEFINITIONS = (
    (PERMISSION_MEMBERSHIP_ROLE_MANAGE, "Conceder e revogar papéis da associação"),
    (PERMISSION_PRODUCTION_ORDER_POLICY_ADOPT, "Adotar política em ordem liberada sem fatos"),
)
INGREDIENT_PERMISSION_DEFINITIONS = (
    (PERMISSION_INGREDIENT_READ, "Ler ingredientes e catálogos globais visíveis"),
    (PERMISSION_INGREDIENT_CREATE, "Criar identidade e primeira versão em rascunho"),
    (PERMISSION_INGREDIENT_UPDATE_DRAFT, "Editar rascunho de ingrediente"),
    (PERMISSION_INGREDIENT_PUBLISH, "Publicar versão de ingrediente"),
    (PERMISSION_INGREDIENT_RETIRE, "Aposentar versão publicada ou inativar identidade"),
    (PERMISSION_SUPPLIER_READ, "Ler fornecedores, itens e histórico de compra"),
    (PERMISSION_SUPPLIER_MANAGE, "Manter fornecedores e itens"),
    (PERMISSION_SUPPLIER_PRICE_RECORD, "Registrar valor de compra observado"),
)
RECIPE_PERMISSION_DEFINITIONS = (
    (PERMISSION_RECIPE_READ, "Ler receitas e versões da organização"),
    (PERMISSION_RECIPE_CREATE, "Criar receita, produto técnico e primeira versão"),
    (PERMISSION_RECIPE_UPDATE_DRAFT, "Editar rascunho de receita"),
    (PERMISSION_RECIPE_VERSION_CREATE, "Criar nova versão de receita"),
    (PERMISSION_RECIPE_SCALE, "Simular e gravar escala e nutrição técnica"),
    (PERMISSION_RECIPE_TRIAL_MANAGE, "Planejar, executar e concluir ensaios"),
    (PERMISSION_RECIPE_REVIEW, "Enviar versão para revisão"),
    (PERMISSION_RECIPE_APPROVE, "Aprovar, rejeitar ou revogar versão"),
    (PERMISSION_RECIPE_PUBLISH, "Publicar versão aprovada"),
    (PERMISSION_RECIPE_RETIRE, "Aposentar versão publicada"),
    (PERMISSION_RECIPE_REFERENCE_MANAGE, "Associar referências visíveis à receita"),
    (PERMISSION_RECIPE_TECHNICAL_SHEET_READ, "Ler ficha técnica derivada da versão"),
    (PERMISSION_RECIPE_AI_PROPOSE, "Gerar proposta assistida de receita"),
    (PERMISSION_RECIPE_AI_REVIEW, "Revisar proposta assistida de receita"),
    (PERMISSION_RECIPE_AI_MATERIALIZE, "Materializar proposta assistida em rascunho"),
)
PRODUCT_PERMISSION_DEFINITIONS = (
    (PERMISSION_PRODUCT_READ, "Ler produtos da organização"),
    (PERMISSION_PRODUCT_CREATE, "Criar produto independente de receita"),
    (PERMISSION_PRODUCT_UPDATE, "Editar produto"),
    (PERMISSION_PRODUCT_ACTIVATE, "Ativar ou inativar produto"),
    (PERMISSION_PRODUCT_FAMILY_MANAGE, "Gerir famílias de produto"),
)
LABELING_PERMISSION_DEFINITIONS = (
    (PERMISSION_LABELING_READ, "Ler dossiês e candidatos de rotulagem"),
    (PERMISSION_LABELING_DOSSIER_CREATE, "Criar dossiê de rotulagem"),
    (PERMISSION_LABELING_EVALUATE, "Executar avaliação determinística de rotulagem"),
    (PERMISSION_LABELING_CANDIDATE_EDIT, "Editar campos controlados do candidato"),
    (PERMISSION_LABELING_REVIEW, "Revisar candidato de rotulagem"),
    (PERMISSION_LABELING_RENDER, "Visualizar e imprimir candidato"),
    (PERMISSION_LABELING_INVALIDATE, "Invalidar versão candidata"),
    (PERMISSION_REGULATORY_SOURCE_READ, "Ler fontes normativas da biblioteca"),
)
COSTING_PERMISSION_DEFINITIONS = (
    (PERMISSION_COSTING_READ, "Ler custos e preços da organização"),
    (PERMISSION_COSTING_POLICY_MANAGE, "Criar e publicar política de custeio"),
    (PERMISSION_COSTING_ASSUMPTION_MANAGE, "Registrar premissas e tarifas versionadas"),
    (PERMISSION_COSTING_CALCULATE_PLANNED, "Calcular custo previsto ou padrão"),
    (PERMISSION_COSTING_CALCULATE_ACTUAL, "Calcular custo realizado"),
    (PERMISSION_PRICING_SIMULATION_MANAGE, "Simular markup e margens (temporário)"),
    (PERMISSION_PRICING_REVIEW, "Revisar preço / salvar cenário praticado em rascunho"),
    (PERMISSION_PRICING_PUBLISH, "Aplicar/publicar preço praticado"),
    (PERMISSION_PRICING_POLICY_MANAGE, "Gerir políticas de markup e margem"),
    (PERMISSION_PRICING_AUDIT_READ, "Consultar auditoria econômica"),
)
REPORTING_PERMISSION_DEFINITIONS = (
    (PERMISSION_REPORTING_DASHBOARD_READ, "Ler a visão executiva de relatórios"),
    (PERMISSION_REPORTING_PRODUCTION_READ, "Ler relatórios de produção, consumo e perdas"),
    (PERMISSION_REPORTING_TRACEABILITY_READ, "Ler relatórios de rastreabilidade e auditoria"),
    (PERMISSION_REPORTING_COSTING_READ, "Ler relatórios de custos de produção"),
    (PERMISSION_REPORTING_PRICING_READ, "Ler relatórios de formação de preços"),
    (PERMISSION_REPORTING_COMPLIANCE_READ, "Ler relatórios de conformidade e rotulagem"),
    (PERMISSION_REPORTING_DATA_QUALITY_READ, "Ler relatórios de qualidade dos dados"),
    (PERMISSION_REPORTING_SNAPSHOT_CREATE, "Criar snapshot reproduzível de relatório"),
    (PERMISSION_REPORTING_EXPORT, "Exportar CSV ou impressão autorizada"),
    (PERMISSION_REPORTING_SAVED_VIEW_MANAGE, "Salvar e gerir visualizações de painel"),
    (PERMISSION_REPORTING_INVENTORY_READ, "Ler relatórios de estoque e compras"),
)
INVENTORY_PERMISSION_DEFINITIONS = (
    (PERMISSION_INVENTORY_READ, "Ler locais, itens, lotes, saldos e movimentações"),
    (PERMISSION_INVENTORY_POLICY_MANAGE, "Publicar política versionada de estoque"),
    (PERMISSION_INVENTORY_ITEM_MANAGE, "Manter locais e itens estocáveis"),
    (PERMISSION_INVENTORY_LOT_MANAGE, "Bloquear, liberar e quarentenar lotes"),
    (PERMISSION_INVENTORY_RESERVE, "Reservar material para ordem"),
    (PERMISSION_INVENTORY_SEPARATE, "Separar lotes para ordem ou batelada"),
    (PERMISSION_INVENTORY_MOVE, "Lançar movimentação operacional"),
    (PERMISSION_INVENTORY_ADJUST, "Lançar ajuste auditável de estoque"),
    (PERMISSION_INVENTORY_COUNT, "Contar inventário físico"),
    (PERMISSION_INVENTORY_COUNT_APPROVE, "Aprovar inventário e gerar ajustes"),
    (PERMISSION_INVENTORY_EXPIRED_OVERRIDE, "Consumir lote vencido ou bloqueado com justificativa"),
)
PROCUREMENT_PERMISSION_DEFINITIONS = (
    (PERMISSION_PROCUREMENT_READ, "Ler requisições, cotações, pedidos e recebimentos"),
    (PERMISSION_PROCUREMENT_REQUISITION_CREATE, "Criar requisição de compra"),
    (PERMISSION_PROCUREMENT_REQUISITION_APPROVE, "Aprovar ou rejeitar requisição"),
    (PERMISSION_PROCUREMENT_QUOTATION_MANAGE, "Registrar cotações recebidas"),
    (PERMISSION_PROCUREMENT_ORDER_MANAGE, "Manter pedido interno de compra"),
    (PERMISSION_PROCUREMENT_ORDER_APPROVE, "Aprovar e emitir pedido interno"),
    (PERMISSION_PROCUREMENT_RECEIVE, "Receber pedido e criar lote"),
    (PERMISSION_PROCUREMENT_RETURN, "Devolver material ao fornecedor"),
)
FISCAL_PERMISSION_DEFINITIONS = (
    (PERMISSION_FISCAL_DOCUMENT_READ, "Ler documentos fiscais de entrada e seus itens"),
    (PERMISSION_FISCAL_DOCUMENT_CAPTURE, "Capturar documento fiscal por chave, XML, imagem ou manual"),
    (PERMISSION_FISCAL_DOCUMENT_MATCH, "Amarrar item fiscal a ingrediente ou produto"),
    (PERMISSION_FISCAL_DOCUMENT_CHECK, "Registrar conferência física do documento fiscal"),
    (PERMISSION_FISCAL_DOCUMENT_CONFIRM, "Confirmar entrada fiscal e lançar estoque"),
    (PERMISSION_FISCAL_PRICE_READ, "Ler valores e custos do documento fiscal"),
    (PERMISSION_FISCAL_INTEGRATION_MANAGE, "Manter integração fiscal e certificado do estabelecimento"),
)
PRODUCTION_PERMISSION_DEFINITIONS = (
    (PERMISSION_PRODUCTION_PLAN_READ, "Ler planos de produção"),
    (PERMISSION_PRODUCTION_PLAN_MANAGE, "Criar e programar planos de produção"),
    (PERMISSION_PRODUCTION_ORDER_READ, "Ler ordens de produção"),
    (PERMISSION_PRODUCTION_ORDER_MANAGE, "Criar e programar ordens de produção"),
    (PERMISSION_PRODUCTION_ORDER_RELEASE, "Liberar ordem com snapshot"),
    (PERMISSION_PRODUCTION_ORDER_CANCEL, "Cancelar ordem de produção"),
    (PERMISSION_PRODUCTION_BATCH_MANAGE, "Criar e dividir bateladas"),
    (PERMISSION_PRODUCTION_BOARD_READ, "Ler o quadro de produção"),
)
PRODUCTION_EXECUTION_PERMISSION_DEFINITIONS = (
    (PERMISSION_PRODUCTION_WEIGHING_RECORD, "Registrar pesagem de produção"),
    (PERMISSION_PRODUCTION_WEIGHING_VERIFY, "Conferir pesagem de produção"),
    (PERMISSION_PRODUCTION_CONSUMPTION_RECORD, "Registrar consumo real de material"),
    (PERMISSION_PRODUCTION_STEP_EXECUTE, "Executar etapa de produção"),
    (PERMISSION_PRODUCTION_OCCURRENCE_RECORD, "Registrar ocorrência de produção"),
    (PERMISSION_PRODUCTION_OCCURRENCE_RESOLVE, "Resolver ocorrência de produção"),
    (PERMISSION_PRODUCTION_BATCH_COMPLETE, "Concluir batelada de produção"),
    (PERMISSION_PRODUCTION_ORDER_COMPLETE, "Concluir ordem de produção"),
    (PERMISSION_PRODUCTION_ORDER_SHORT_CLOSE, "Encerrar ordem abaixo do planejado"),
    (PERMISSION_PRODUCTION_SHEET_ISSUE, "Emitir registro auditável da ficha"),
    (PERMISSION_PRODUCTION_TRACEABILITY_READ, "Ler rastreabilidade de produção"),
)
PERMISSIONS = (
    FOUNDATION_PERMISSIONS
    + PRODUCTION_PERMISSION_DEFINITIONS
    + PRODUCTION_EXECUTION_PERMISSION_DEFINITIONS
    + API_PERMISSION_DEFINITIONS
    + INGREDIENT_PERMISSION_DEFINITIONS
    + RECIPE_PERMISSION_DEFINITIONS
    + PRODUCT_PERMISSION_DEFINITIONS
    + LABELING_PERMISSION_DEFINITIONS
    + COSTING_PERMISSION_DEFINITIONS
    + REPORTING_PERMISSION_DEFINITIONS
    + INVENTORY_PERMISSION_DEFINITIONS
    + PROCUREMENT_PERMISSION_DEFINITIONS
    + FISCAL_PERMISSION_DEFINITIONS
)
API_PERMISSIONS = (
    PERMISSION_MEMBERSHIP_ROLE_MANAGE,
    PERMISSION_PRODUCTION_ORDER_POLICY_ADOPT,
)
INGREDIENT_PERMISSIONS = (
    PERMISSION_INGREDIENT_READ,
    PERMISSION_INGREDIENT_CREATE,
    PERMISSION_INGREDIENT_UPDATE_DRAFT,
    PERMISSION_INGREDIENT_PUBLISH,
    PERMISSION_INGREDIENT_RETIRE,
    PERMISSION_SUPPLIER_READ,
    PERMISSION_SUPPLIER_MANAGE,
    PERMISSION_SUPPLIER_PRICE_RECORD,
)
RECIPE_PERMISSIONS = (
    PERMISSION_RECIPE_READ,
    PERMISSION_RECIPE_CREATE,
    PERMISSION_RECIPE_UPDATE_DRAFT,
    PERMISSION_RECIPE_VERSION_CREATE,
    PERMISSION_RECIPE_SCALE,
    PERMISSION_RECIPE_TRIAL_MANAGE,
    PERMISSION_RECIPE_REVIEW,
    PERMISSION_RECIPE_APPROVE,
    PERMISSION_RECIPE_PUBLISH,
    PERMISSION_RECIPE_RETIRE,
    PERMISSION_RECIPE_REFERENCE_MANAGE,
    PERMISSION_RECIPE_TECHNICAL_SHEET_READ,
    PERMISSION_RECIPE_AI_PROPOSE,
    PERMISSION_RECIPE_AI_REVIEW,
    PERMISSION_RECIPE_AI_MATERIALIZE,
)
PRODUCT_PERMISSIONS = (
    PERMISSION_PRODUCT_READ,
    PERMISSION_PRODUCT_CREATE,
    PERMISSION_PRODUCT_UPDATE,
    PERMISSION_PRODUCT_ACTIVATE,
    PERMISSION_PRODUCT_FAMILY_MANAGE,
)
LABELING_PERMISSIONS = (
    PERMISSION_LABELING_READ,
    PERMISSION_LABELING_DOSSIER_CREATE,
    PERMISSION_LABELING_EVALUATE,
    PERMISSION_LABELING_CANDIDATE_EDIT,
    PERMISSION_LABELING_REVIEW,
    PERMISSION_LABELING_RENDER,
    PERMISSION_LABELING_INVALIDATE,
    PERMISSION_REGULATORY_SOURCE_READ,
)
COSTING_PERMISSIONS = (
    PERMISSION_COSTING_READ,
    PERMISSION_COSTING_POLICY_MANAGE,
    PERMISSION_COSTING_ASSUMPTION_MANAGE,
    PERMISSION_COSTING_CALCULATE_PLANNED,
    PERMISSION_COSTING_CALCULATE_ACTUAL,
    PERMISSION_PRICING_SIMULATION_MANAGE,
    PERMISSION_PRICING_REVIEW,
    PERMISSION_PRICING_PUBLISH,
    PERMISSION_PRICING_POLICY_MANAGE,
    PERMISSION_PRICING_AUDIT_READ,
)
REPORTING_PERMISSIONS = (
    PERMISSION_REPORTING_DASHBOARD_READ,
    PERMISSION_REPORTING_PRODUCTION_READ,
    PERMISSION_REPORTING_TRACEABILITY_READ,
    PERMISSION_REPORTING_COSTING_READ,
    PERMISSION_REPORTING_PRICING_READ,
    PERMISSION_REPORTING_COMPLIANCE_READ,
    PERMISSION_REPORTING_DATA_QUALITY_READ,
    PERMISSION_REPORTING_SNAPSHOT_CREATE,
    PERMISSION_REPORTING_EXPORT,
    PERMISSION_REPORTING_SAVED_VIEW_MANAGE,
    PERMISSION_REPORTING_INVENTORY_READ,
)
INVENTORY_PERMISSIONS = (
    PERMISSION_INVENTORY_READ,
    PERMISSION_INVENTORY_POLICY_MANAGE,
    PERMISSION_INVENTORY_ITEM_MANAGE,
    PERMISSION_INVENTORY_LOT_MANAGE,
    PERMISSION_INVENTORY_RESERVE,
    PERMISSION_INVENTORY_SEPARATE,
    PERMISSION_INVENTORY_MOVE,
    PERMISSION_INVENTORY_ADJUST,
    PERMISSION_INVENTORY_COUNT,
    PERMISSION_INVENTORY_COUNT_APPROVE,
    PERMISSION_INVENTORY_EXPIRED_OVERRIDE,
)
PROCUREMENT_PERMISSIONS = (
    PERMISSION_PROCUREMENT_READ,
    PERMISSION_PROCUREMENT_REQUISITION_CREATE,
    PERMISSION_PROCUREMENT_REQUISITION_APPROVE,
    PERMISSION_PROCUREMENT_QUOTATION_MANAGE,
    PERMISSION_PROCUREMENT_ORDER_MANAGE,
    PERMISSION_PROCUREMENT_ORDER_APPROVE,
    PERMISSION_PROCUREMENT_RECEIVE,
    PERMISSION_PROCUREMENT_RETURN,
)
FISCAL_PERMISSIONS = (
    PERMISSION_FISCAL_DOCUMENT_READ,
    PERMISSION_FISCAL_DOCUMENT_CAPTURE,
    PERMISSION_FISCAL_DOCUMENT_MATCH,
    PERMISSION_FISCAL_DOCUMENT_CHECK,
    PERMISSION_FISCAL_DOCUMENT_CONFIRM,
    PERMISSION_FISCAL_PRICE_READ,
    PERMISSION_FISCAL_INTEGRATION_MANAGE,
)

PRODUCTION_PERMISSIONS = (
    PERMISSION_PRODUCTION_PLAN_READ,
    PERMISSION_PRODUCTION_PLAN_MANAGE,
    PERMISSION_PRODUCTION_ORDER_READ,
    PERMISSION_PRODUCTION_ORDER_MANAGE,
    PERMISSION_PRODUCTION_ORDER_RELEASE,
    PERMISSION_PRODUCTION_ORDER_CANCEL,
    PERMISSION_PRODUCTION_BATCH_MANAGE,
    PERMISSION_PRODUCTION_BOARD_READ,
)
PRODUCTION_EXECUTION_PERMISSIONS = (
    PERMISSION_PRODUCTION_WEIGHING_RECORD,
    PERMISSION_PRODUCTION_WEIGHING_VERIFY,
    PERMISSION_PRODUCTION_CONSUMPTION_RECORD,
    PERMISSION_PRODUCTION_STEP_EXECUTE,
    PERMISSION_PRODUCTION_OCCURRENCE_RECORD,
    PERMISSION_PRODUCTION_OCCURRENCE_RESOLVE,
    PERMISSION_PRODUCTION_BATCH_COMPLETE,
    PERMISSION_PRODUCTION_ORDER_COMPLETE,
    PERMISSION_PRODUCTION_ORDER_SHORT_CLOSE,
    PERMISSION_PRODUCTION_SHEET_ISSUE,
    PERMISSION_PRODUCTION_TRACEABILITY_READ,
)

EXISTING_ROLES = (
    "owner",
    "administrator",
    "technical_responsible",
    "production",
    "commercial",
    "viewer",
)
ADDED_ROLES = (
    "organization_owner",
    "organization_admin",
    "production_manager",
    "baker_operator",
    "regulatory_reviewer",
    "restricted",
)
MEMBERSHIP_ROLES = EXISTING_ROLES + ADDED_ROLES

ROLE_ALIASES = {
    "owner": "organization_owner",
    "administrator": "organization_admin",
    "production": "production_manager",
}

_READ_ME = (
    PERMISSION_IDENTITY_READ_ME,
    PERMISSION_ORGANIZATION_READ,
    PERMISSION_MEMBERSHIP_READ,
)
_REVIEW = _READ_ME + (PERMISSION_COMPLIANCE_REVIEW,)
_ROLE_MANAGE = (PERMISSION_MEMBERSHIP_ROLE_MANAGE,)
_POLICY_ADOPT = (PERMISSION_PRODUCTION_ORDER_POLICY_ADOPT,)
_PRODUCTION_ADMIN = PRODUCTION_PERMISSIONS + PRODUCTION_EXECUTION_PERMISSIONS + _POLICY_ADOPT
_PRODUCTION_READ = (
    PERMISSION_PRODUCTION_PLAN_READ,
    PERMISSION_PRODUCTION_ORDER_READ,
    PERMISSION_PRODUCTION_BOARD_READ,
)
_PRODUCTION_TECHNICAL = _PRODUCTION_READ + (PERMISSION_PRODUCTION_TRACEABILITY_READ,)
_PRODUCTION_BAKER = (
    PERMISSION_PRODUCTION_ORDER_READ,
    PERMISSION_PRODUCTION_BOARD_READ,
    PERMISSION_PRODUCTION_WEIGHING_RECORD,
    PERMISSION_PRODUCTION_WEIGHING_VERIFY,
    PERMISSION_PRODUCTION_CONSUMPTION_RECORD,
    PERMISSION_PRODUCTION_STEP_EXECUTE,
    PERMISSION_PRODUCTION_OCCURRENCE_RECORD,
    PERMISSION_PRODUCTION_TRACEABILITY_READ,
)
_INGREDIENT_ADMIN = INGREDIENT_PERMISSIONS
_INGREDIENT_READ = (PERMISSION_INGREDIENT_READ, PERMISSION_SUPPLIER_READ)
_INGREDIENT_TECHNICAL = (
    PERMISSION_INGREDIENT_READ,
    PERMISSION_INGREDIENT_CREATE,
    PERMISSION_INGREDIENT_UPDATE_DRAFT,
    PERMISSION_INGREDIENT_PUBLISH,
    PERMISSION_INGREDIENT_RETIRE,
    PERMISSION_SUPPLIER_READ,
    PERMISSION_SUPPLIER_MANAGE,
    PERMISSION_SUPPLIER_PRICE_RECORD,
)
_INGREDIENT_COMMERCIAL = (
    PERMISSION_INGREDIENT_READ,
    PERMISSION_SUPPLIER_READ,
    PERMISSION_SUPPLIER_MANAGE,
    PERMISSION_SUPPLIER_PRICE_RECORD,
)
_RECIPE_ADMIN = RECIPE_PERMISSIONS
_RECIPE_READ = (PERMISSION_RECIPE_READ, PERMISSION_RECIPE_TECHNICAL_SHEET_READ)
_RECIPE_TECHNICAL = RECIPE_PERMISSIONS
_RECIPE_REVIEW = _RECIPE_READ + (
    PERMISSION_RECIPE_REVIEW,
    PERMISSION_RECIPE_APPROVE,
    PERMISSION_RECIPE_AI_REVIEW,
)
_PRODUCT_ADMIN = PRODUCT_PERMISSIONS
_PRODUCT_READ = (PERMISSION_PRODUCT_READ,)
_PRODUCT_TECHNICAL = PRODUCT_PERMISSIONS
_LABELING_ADMIN = LABELING_PERMISSIONS
_LABELING_READ = (PERMISSION_LABELING_READ, PERMISSION_REGULATORY_SOURCE_READ)
_LABELING_REVIEW = _LABELING_READ + (
    PERMISSION_LABELING_EVALUATE,
    PERMISSION_LABELING_REVIEW,
    PERMISSION_LABELING_RENDER,
)
_COSTING_ADMIN = COSTING_PERMISSIONS
_COSTING_TECHNICAL = (
    PERMISSION_COSTING_READ,
    PERMISSION_COSTING_POLICY_MANAGE,
    PERMISSION_COSTING_ASSUMPTION_MANAGE,
    PERMISSION_COSTING_CALCULATE_PLANNED,
    PERMISSION_COSTING_CALCULATE_ACTUAL,
    PERMISSION_PRICING_SIMULATION_MANAGE,
    PERMISSION_PRICING_REVIEW,
    PERMISSION_PRICING_POLICY_MANAGE,
    PERMISSION_PRICING_AUDIT_READ,
)
_COSTING_COMMERCIAL = (
    PERMISSION_COSTING_READ,
    PERMISSION_PRICING_SIMULATION_MANAGE,
    PERMISSION_PRICING_REVIEW,
    PERMISSION_PRICING_PUBLISH,
    PERMISSION_PRICING_POLICY_MANAGE,
    PERMISSION_PRICING_AUDIT_READ,
)
_REPORTING_ALL = REPORTING_PERMISSIONS
_REPORTING_OPERATIONS = (
    PERMISSION_REPORTING_DASHBOARD_READ,
    PERMISSION_REPORTING_PRODUCTION_READ,
    PERMISSION_REPORTING_TRACEABILITY_READ,
    PERMISSION_REPORTING_DATA_QUALITY_READ,
    PERMISSION_REPORTING_SNAPSHOT_CREATE,
    PERMISSION_REPORTING_EXPORT,
    PERMISSION_REPORTING_SAVED_VIEW_MANAGE,
    PERMISSION_REPORTING_INVENTORY_READ,
)
_REPORTING_BAKER = (
    PERMISSION_REPORTING_PRODUCTION_READ,
    PERMISSION_REPORTING_TRACEABILITY_READ,
)
_REPORTING_COMMERCIAL = (
    PERMISSION_REPORTING_DASHBOARD_READ,
    PERMISSION_REPORTING_COSTING_READ,
    PERMISSION_REPORTING_PRICING_READ,
    PERMISSION_REPORTING_DATA_QUALITY_READ,
    PERMISSION_REPORTING_SNAPSHOT_CREATE,
    PERMISSION_REPORTING_EXPORT,
    PERMISSION_REPORTING_SAVED_VIEW_MANAGE,
    PERMISSION_REPORTING_INVENTORY_READ,
)
_INVENTORY_ALL = INVENTORY_PERMISSIONS
_INVENTORY_OPS = (
    PERMISSION_INVENTORY_READ,
    PERMISSION_INVENTORY_RESERVE,
    PERMISSION_INVENTORY_SEPARATE,
    PERMISSION_INVENTORY_MOVE,
    PERMISSION_INVENTORY_COUNT,
)
_INVENTORY_BAKER = (
    PERMISSION_INVENTORY_READ,
    PERMISSION_INVENTORY_SEPARATE,
)
_PROCUREMENT_ALL = PROCUREMENT_PERMISSIONS
_PROCUREMENT_COMMERCIAL = PROCUREMENT_PERMISSIONS
_PROCUREMENT_READ = (PERMISSION_PROCUREMENT_READ,)
_FISCAL_ALL = FISCAL_PERMISSIONS
_FISCAL_COMMERCIAL = (
    PERMISSION_FISCAL_DOCUMENT_READ,
    PERMISSION_FISCAL_DOCUMENT_CAPTURE,
    PERMISSION_FISCAL_DOCUMENT_MATCH,
    PERMISSION_FISCAL_DOCUMENT_CONFIRM,
    PERMISSION_FISCAL_PRICE_READ,
)
_FISCAL_OPERATIONS = (
    PERMISSION_FISCAL_DOCUMENT_READ,
    PERMISSION_FISCAL_DOCUMENT_CHECK,
)
_FISCAL_READ = (PERMISSION_FISCAL_DOCUMENT_READ,)
_REPORTING_REVIEW = (
    PERMISSION_REPORTING_COMPLIANCE_READ,
    PERMISSION_REPORTING_DATA_QUALITY_READ,
    PERMISSION_REPORTING_SNAPSHOT_CREATE,
    PERMISSION_REPORTING_EXPORT,
)
_REPORTING_VIEWER = (
    PERMISSION_REPORTING_DASHBOARD_READ,
    PERMISSION_REPORTING_PRODUCTION_READ,
    PERMISSION_REPORTING_TRACEABILITY_READ,
    PERMISSION_REPORTING_COMPLIANCE_READ,
    PERMISSION_REPORTING_DATA_QUALITY_READ,
)

ROLE_PERMISSIONS: dict[str, tuple[str, ...]] = {
    "owner": _REVIEW + _PRODUCTION_ADMIN + _ROLE_MANAGE + _INGREDIENT_ADMIN + _RECIPE_ADMIN + _PRODUCT_ADMIN + _LABELING_ADMIN + _COSTING_ADMIN + _REPORTING_ALL + _INVENTORY_ALL + _PROCUREMENT_ALL + _FISCAL_ALL,
    "organization_owner": (
        _REVIEW + _PRODUCTION_ADMIN + _ROLE_MANAGE + _INGREDIENT_ADMIN + _RECIPE_ADMIN + _PRODUCT_ADMIN + _LABELING_ADMIN + _COSTING_ADMIN + _REPORTING_ALL + _INVENTORY_ALL + _PROCUREMENT_ALL + _FISCAL_ALL
    ),
    "administrator": (
        _REVIEW + _PRODUCTION_ADMIN + _ROLE_MANAGE + _INGREDIENT_ADMIN + _RECIPE_ADMIN + _PRODUCT_ADMIN + _LABELING_ADMIN + _COSTING_ADMIN + _REPORTING_ALL + _INVENTORY_ALL + _PROCUREMENT_ALL + _FISCAL_ALL
    ),
    "organization_admin": (
        _REVIEW + _PRODUCTION_ADMIN + _ROLE_MANAGE + _INGREDIENT_ADMIN + _RECIPE_ADMIN + _PRODUCT_ADMIN + _LABELING_ADMIN + _COSTING_ADMIN + _REPORTING_ALL + _INVENTORY_ALL + _PROCUREMENT_ALL + _FISCAL_ALL
    ),
    "regulatory_reviewer": _REVIEW + _INGREDIENT_READ + _RECIPE_REVIEW + _PRODUCT_READ + _LABELING_REVIEW + (PERMISSION_COSTING_READ,) + _REPORTING_REVIEW,
    "technical_responsible": (
        _READ_ME + _PRODUCTION_TECHNICAL + _INGREDIENT_TECHNICAL + _RECIPE_TECHNICAL + _PRODUCT_TECHNICAL + _LABELING_ADMIN + _COSTING_TECHNICAL + _REPORTING_ALL + _INVENTORY_ALL + _PROCUREMENT_ALL + _FISCAL_ALL
    ),
    "production": _READ_ME + _PRODUCTION_ADMIN + _INGREDIENT_READ + _RECIPE_READ + _PRODUCT_READ + _LABELING_READ + _REPORTING_OPERATIONS + _INVENTORY_OPS + _FISCAL_OPERATIONS,
    "production_manager": _READ_ME + _PRODUCTION_ADMIN + _INGREDIENT_READ + _RECIPE_READ + _PRODUCT_READ + _LABELING_READ + _REPORTING_OPERATIONS + _INVENTORY_OPS + _FISCAL_OPERATIONS,
    "commercial": _READ_ME + _INGREDIENT_COMMERCIAL + _RECIPE_READ + _PRODUCT_READ + (PERMISSION_PRODUCT_CREATE, PERMISSION_PRODUCT_UPDATE) + _LABELING_READ + _COSTING_COMMERCIAL + _REPORTING_COMMERCIAL + (PERMISSION_INVENTORY_READ,) + _PROCUREMENT_COMMERCIAL + _FISCAL_COMMERCIAL,
    "baker_operator": _READ_ME + _PRODUCTION_BAKER + (PERMISSION_INGREDIENT_READ,) + _RECIPE_READ + _PRODUCT_READ + _LABELING_READ + _REPORTING_BAKER + _INVENTORY_BAKER + _FISCAL_READ,
    "viewer": _READ_ME + _PRODUCTION_READ + _INGREDIENT_READ + _RECIPE_READ + _PRODUCT_READ + _LABELING_READ + _REPORTING_VIEWER + (PERMISSION_INVENTORY_READ,) + _PROCUREMENT_READ + _FISCAL_READ + (PERMISSION_COSTING_READ,),
    "restricted": (),
}


class AuthorizationError(Exception):
    def __init__(self, reason: str) -> None:
        super().__init__(reason)
        self.reason = reason


@dataclass(frozen=True)
class Association:
    organization_id: UUID
    status: str
    permissions: frozenset[str]
    roles: tuple[str, ...]
    organization_display_name: str = ""
    organization_slug: str = ""


@dataclass(frozen=True)
class Principal:
    user_id: UUID
    display_name: str
    status: str
    issuer: str
    subject: str
    associations: tuple[Association, ...]
    selected: Association | None

    @property
    def permissions(self) -> frozenset[str]:
        if self.selected is None:
            granted: set[str] = set()
            for item in self.associations:
                granted.update(item.permissions)
            return frozenset(granted)
        return self.selected.permissions


def canonical_role(role: str) -> str:
    return ROLE_ALIASES.get(role, role)


def permissions_for_role(role: str) -> frozenset[str]:
    return frozenset(ROLE_PERMISSIONS.get(role, ()))


def require_permission(principal: Principal, code: str) -> None:
    if code not in principal.permissions:
        raise AuthorizationError("permissao_negada")
