"""initial domain model

Revision ID: 28420c077dcd
Revises: 0001_baseline
Create Date: 2026-09-16 11:43:29.453676
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '28420c077dcd'
down_revision: Union[str, Sequence[str], None] = '0001_baseline'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergens',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('articles',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('cover_image_ref', sa.String(length=500), nullable=True),
    sa.Column('editorial_status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_reading_minutes', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("editorial_status IN ('draft','published','archived')", name='ck_articles_editorial_status'),
    sa.CheckConstraint('estimated_reading_minutes IS NULL OR estimated_reading_minutes > 0', name='ck_articles_reading_minutes'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('bread_shapes',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=False),
    sa.Column('crust_crumb_notes', sa.Text(), nullable=False),
    sa.Column('image_ref', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('dough_types',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('short_description', sa.String(length=280), nullable=False),
    sa.Column('story', sa.Text(), nullable=True),
    sa.Column('fermentation_hours', sa.Integer(), nullable=True),
    sa.Column('image_ref', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('base_price_cents', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_price_cents IS NULL OR base_price_cents >= 0', name='ck_dough_types_base_price_cents'),
    sa.CheckConstraint('fermentation_hours IS NULL OR fermentation_hours > 0', name='ck_dough_types_fermentation_hours'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('ingredients',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=280), nullable=False),
    sa.Column('image_ref', sa.String(length=500), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('surcharge_cents', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('surcharge_cents IS NULL OR surcharge_cents >= 0', name='ck_ingredients_surcharge_cents'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('inspiration_posts',
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('caption', sa.Text(), nullable=False),
    sa.Column('image_ref', sa.String(length=500), nullable=True),
    sa.Column('credit', sa.String(length=160), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_kind', sa.String(length=20), nullable=False),
    sa.Column('editorial_status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("editorial_status IN ('draft','published','archived')", name='ck_inspiration_editorial_status'),
    sa.CheckConstraint("source_kind IN ('editorial','community')", name='ck_inspiration_source_kind'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('production_batches',
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('planned_start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('breads_available_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_deadline_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planned', 'open', 'closed', 'cancelled')", name='ck_production_batches_status'),
    sa.CheckConstraint('capacity_units > 0', name='ck_production_batches_capacity'),
    sa.CheckConstraint('order_deadline_at <= breads_available_at', name='ck_production_batches_deadline'),
    sa.CheckConstraint('planned_start_at < breads_available_at', name='ck_production_batches_start_before_available'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('dough_allergens',
    sa.Column('dough_type_id', sa.Uuid(), nullable=False),
    sa.Column('allergen_id', sa.Uuid(), nullable=False),
    sa.Column('presence', sa.String(length=20), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("presence IN ('contains', 'may_contain')", name='ck_dough_allergens_presence'),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dough_type_id'], ['dough_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dough_type_id', 'allergen_id', 'presence', name='uq_dough_allergen_presence')
    )
    op.create_table('dough_ingredient_compatibilities',
    sa.Column('dough_type_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['dough_type_id'], ['dough_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dough_type_id', 'ingredient_id', name='uq_dough_ingredient_compat')
    )
    op.create_table('dough_shape_compatibilities',
    sa.Column('dough_type_id', sa.Uuid(), nullable=False),
    sa.Column('bread_shape_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['bread_shape_id'], ['bread_shapes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dough_type_id'], ['dough_types.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dough_type_id', 'bread_shape_id', name='uq_dough_shape_compat')
    )
    op.create_table('fulfillment_slots',
    sa.Column('production_batch_id', sa.Uuid(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('modality', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("modality IN ('pickup', 'delivery')", name='ck_fulfillment_slots_modality'),
    sa.CheckConstraint('capacity_units > 0', name='ck_fulfillment_slots_capacity'),
    sa.CheckConstraint('starts_at < ends_at', name='ck_fulfillment_slots_window'),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fulfillment_slots_production_batch_id'), 'fulfillment_slots', ['production_batch_id'], unique=False)
    op.create_table('ingredient_allergens',
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('allergen_id', sa.Uuid(), nullable=False),
    sa.Column('presence', sa.String(length=20), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("presence IN ('contains', 'may_contain')", name='ck_ingredient_allergens_presence'),
    sa.ForeignKeyConstraint(['allergen_id'], ['allergens.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id', 'allergen_id', 'presence', name='uq_ingredient_allergen_presence')
    )
    op.create_table('pairing_tips',
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('paired_ingredient_id', sa.Uuid(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('paired_ingredient_id IS NULL OR ingredient_id < paired_ingredient_id', name='ck_pairing_tips_canonical_order'),
    sa.CheckConstraint('paired_ingredient_id IS NULL OR ingredient_id <> paired_ingredient_id', name='ck_pairing_tips_not_self'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['paired_ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_pairing_tips_pair', 'pairing_tips', ['ingredient_id', 'paired_ingredient_id'], unique=True, postgresql_where=sa.text('paired_ingredient_id IS NOT NULL'))
    op.create_index('uq_pairing_tips_single', 'pairing_tips', ['ingredient_id'], unique=True, postgresql_where=sa.text('paired_ingredient_id IS NULL'))
    op.create_table('production_batch_dough_limits',
    sa.Column('production_batch_id', sa.Uuid(), nullable=False),
    sa.Column('dough_type_id', sa.Uuid(), nullable=False),
    sa.Column('capacity_units', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('capacity_units > 0', name='ck_batch_dough_limit_capacity'),
    sa.ForeignKeyConstraint(['dough_type_id'], ['dough_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_batch_id', 'dough_type_id', name='uq_batch_dough_limit')
    )
    op.create_table('orders',
    sa.Column('public_reference', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('fulfillment_modality', sa.String(length=20), nullable=True),
    sa.Column('fulfillment_slot_id', sa.Uuid(), nullable=True),
    sa.Column('production_batch_id', sa.Uuid(), nullable=True),
    sa.Column('identity_subject_id', sa.Uuid(), nullable=True),
    sa.Column('customer_name', sa.String(length=160), nullable=True),
    sa.Column('customer_email', sa.String(length=254), nullable=True),
    sa.Column('customer_phone', sa.String(length=40), nullable=True),
    sa.Column('delivery_street', sa.String(length=160), nullable=True),
    sa.Column('delivery_number', sa.String(length=20), nullable=True),
    sa.Column('delivery_complement', sa.String(length=80), nullable=True),
    sa.Column('delivery_district', sa.String(length=80), nullable=True),
    sa.Column('delivery_city', sa.String(length=80), nullable=True),
    sa.Column('delivery_state', sa.String(length=2), nullable=True),
    sa.Column('delivery_postal_code', sa.String(length=12), nullable=True),
    sa.Column('customer_note', sa.String(length=2000), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=True),
    sa.Column('delivery_fee_cents', sa.Integer(), nullable=True),
    sa.Column('discount_cents', sa.Integer(), nullable=True),
    sa.Column('total_cents', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('production_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=280), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'BRL'", name='ck_orders_currency'),
    sa.CheckConstraint("fulfillment_modality IS NULL OR fulfillment_modality IN ('pickup','delivery')", name='ck_orders_modality'),
    sa.CheckConstraint("status IN ('draft','confirmed','in_production','ready','completed','cancelled')", name='ck_orders_status'),
    sa.CheckConstraint('char_length(customer_note) <= 2000', name='ck_orders_customer_note'),
    sa.CheckConstraint('delivery_fee_cents IS NULL OR delivery_fee_cents >= 0', name='ck_orders_delivery_fee'),
    sa.CheckConstraint('discount_cents IS NULL OR discount_cents >= 0', name='ck_orders_discount'),
    sa.CheckConstraint('subtotal_cents IS NULL OR subtotal_cents >= 0', name='ck_orders_subtotal'),
    sa.CheckConstraint('total_cents IS NULL OR total_cents >= 0', name='ck_orders_total'),
    sa.ForeignKeyConstraint(['fulfillment_slot_id'], ['fulfillment_slots.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_batch_id'], ['production_batches.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_reference')
    )
    op.create_index('ix_orders_batch_status', 'orders', ['production_batch_id', 'status'], unique=False)
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_slot_status', 'orders', ['fulfillment_slot_id', 'status'], unique=False)
    op.create_index('ix_orders_status_confirmed_at', 'orders', ['status', 'confirmed_at'], unique=False)
    op.create_table('order_internal_notes',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('author_ref', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_internal_notes_order_id'), 'order_internal_notes', ['order_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('dough_type_id', sa.Uuid(), nullable=False),
    sa.Column('bread_shape_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('dough_name_snapshot', sa.String(length=120), nullable=True),
    sa.Column('shape_name_snapshot', sa.String(length=120), nullable=True),
    sa.Column('unit_price_cents', sa.Integer(), nullable=True),
    sa.Column('line_total_cents', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('line_total_cents IS NULL OR line_total_cents >= 0', name='ck_order_items_line_total'),
    sa.CheckConstraint('quantity > 0', name='ck_order_items_quantity'),
    sa.CheckConstraint('unit_price_cents IS NULL OR unit_price_cents >= 0', name='ck_order_items_unit_price'),
    sa.ForeignKeyConstraint(['bread_shape_id'], ['bread_shapes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dough_type_id'], ['dough_types.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('from_status', sa.String(length=20), nullable=True),
    sa.Column('to_status', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=280), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("from_status IS NULL OR from_status IN ('draft','confirmed','in_production','ready','completed','cancelled')", name='ck_order_status_history_from'),
    sa.CheckConstraint("to_status IN ('draft','confirmed','in_production','ready','completed','cancelled')", name='ck_order_status_history_to'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_order_status_history_order_created', 'order_status_history', ['order_id', 'created_at'], unique=False)
    op.create_table('payment_records',
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_reference', sa.String(length=120), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=True),
    sa.Column('expected_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('financial_status', sa.String(length=32), nullable=False),
    sa.Column('external_status_raw', sa.String(length=80), nullable=True),
    sa.Column('amount_paid_cents', sa.Integer(), nullable=True),
    sa.Column('amount_refunded_cents', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("currency = 'BRL'", name='ck_payment_records_currency'),
    sa.CheckConstraint("financial_status IN ('pending','paid','failed','cancelled','partially_refunded','refunded','unknown')", name='ck_payment_records_status'),
    sa.CheckConstraint("provider = 'actionhub'", name='ck_payment_records_provider'),
    sa.CheckConstraint('amount_paid_cents IS NULL OR amount_paid_cents >= 0', name='ck_payment_records_paid'),
    sa.CheckConstraint('amount_paid_cents IS NULL OR amount_refunded_cents IS NULL OR amount_refunded_cents <= amount_paid_cents', name='ck_payment_records_refund_lte_paid'),
    sa.CheckConstraint('amount_refunded_cents IS NULL OR amount_refunded_cents >= 0', name='ck_payment_records_refunded'),
    sa.CheckConstraint('expected_cents >= 0', name='ck_payment_records_expected'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payment_records_order', 'payment_records', ['order_id'], unique=False)
    op.create_index('uq_payment_records_external_ref', 'payment_records', ['provider', 'external_reference'], unique=True, postgresql_where='external_reference IS NOT NULL')
    op.create_index('uq_payment_records_idempotency', 'payment_records', ['provider', 'idempotency_key'], unique=True, postgresql_where='idempotency_key IS NOT NULL')
    op.create_table('order_item_ingredients',
    sa.Column('order_item_id', sa.Uuid(), nullable=False),
    sa.Column('ingredient_id', sa.Uuid(), nullable=False),
    sa.Column('name_snapshot', sa.String(length=120), nullable=True),
    sa.Column('surcharge_cents', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('surcharge_cents IS NULL OR surcharge_cents >= 0', name='ck_order_item_ingredients_surcharge'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_item_id', 'ingredient_id', name='uq_order_item_ingredient')
    )
    op.create_table('payment_integration_events',
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_event_id', sa.String(length=160), nullable=False),
    sa.Column('payment_record_id', sa.Uuid(), nullable=True),
    sa.Column('external_type', sa.String(length=80), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('provider_occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('process_status', sa.String(length=20), nullable=False),
    sa.Column('sanitized_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint("process_status IN ('received','ignored','applied','failed')", name='ck_payment_events_process_status'),
    sa.CheckConstraint("provider = 'actionhub'", name='ck_payment_events_provider'),
    sa.ForeignKeyConstraint(['payment_record_id'], ['payment_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_payment_events_external_id', 'payment_integration_events', ['provider', 'external_event_id'], unique=True)
    op.execute(
        """
        CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
        BEGIN
            NEW.updated_at = now();
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for table in (
        "allergens",
        "articles",
        "bread_shapes",
        "dough_types",
        "ingredients",
        "inspiration_posts",
        "production_batches",
        "fulfillment_slots",
        "pairing_tips",
        "orders",
        "order_items",
        "payment_records",
    ):
        op.execute(
            f"CREATE TRIGGER trg_{table}_updated_at "
            f"BEFORE UPDATE ON {table} "
            f"FOR EACH ROW EXECUTE FUNCTION set_updated_at();"
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP FUNCTION IF EXISTS set_updated_at() CASCADE")
    op.drop_index('uq_payment_events_external_id', table_name='payment_integration_events')
    op.drop_table('payment_integration_events')
    op.drop_table('order_item_ingredients')
    op.drop_index('uq_payment_records_idempotency', table_name='payment_records', postgresql_where='idempotency_key IS NOT NULL')
    op.drop_index('uq_payment_records_external_ref', table_name='payment_records', postgresql_where='external_reference IS NOT NULL')
    op.drop_index('ix_payment_records_order', table_name='payment_records')
    op.drop_table('payment_records')
    op.drop_index('ix_order_status_history_order_created', table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_items_order_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_order_internal_notes_order_id'), table_name='order_internal_notes')
    op.drop_table('order_internal_notes')
    op.drop_index('ix_orders_status_confirmed_at', table_name='orders')
    op.drop_index('ix_orders_slot_status', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.drop_index('ix_orders_batch_status', table_name='orders')
    op.drop_table('orders')
    op.drop_table('production_batch_dough_limits')
    op.drop_index('uq_pairing_tips_single', table_name='pairing_tips', postgresql_where=sa.text('paired_ingredient_id IS NULL'))
    op.drop_index('uq_pairing_tips_pair', table_name='pairing_tips', postgresql_where=sa.text('paired_ingredient_id IS NOT NULL'))
    op.drop_table('pairing_tips')
    op.drop_table('ingredient_allergens')
    op.drop_index(op.f('ix_fulfillment_slots_production_batch_id'), table_name='fulfillment_slots')
    op.drop_table('fulfillment_slots')
    op.drop_table('dough_shape_compatibilities')
    op.drop_table('dough_ingredient_compatibilities')
    op.drop_table('dough_allergens')
    op.drop_table('production_batches')
    op.drop_table('inspiration_posts')
    op.drop_table('ingredients')
    op.drop_table('dough_types')
    op.drop_table('bread_shapes')
    op.drop_table('articles')
    op.drop_table('allergens')
    # ### end Alembic commands ###
