package br.com.segsense.inbound.http.error;

public final class ApiErrorCodes {

  public static final String AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED";
  public static final String ACCESS_DENIED = "ACCESS_DENIED";
  public static final String NOT_FOUND = "NOT_FOUND";
  public static final String INTERNAL_ERROR = "INTERNAL_ERROR";
  public static final String VALIDATION_ERROR = "VALIDATION_ERROR";
  public static final String CONCURRENT_MODIFICATION = "CONCURRENT_MODIFICATION";
  public static final String INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION";
  public static final String PUBLISHER_KEY_CONFLICT = "PUBLISHER_KEY_CONFLICT";
  public static final String CHANNEL_KEY_CONFLICT = "CHANNEL_KEY_CONFLICT";
  public static final String ENVIRONMENT_KEY_CONFLICT = "ENVIRONMENT_KEY_CONFLICT";
  public static final String OPPORTUNITY_KEY_CONFLICT = "OPPORTUNITY_KEY_CONFLICT";
  public static final String STALE_OPPORTUNITY_REVISION = "STALE_OPPORTUNITY_REVISION";
  public static final String INVALID_PARENT_STATE = "INVALID_PARENT_STATE";
  public static final String NO_CONTENT_CHANGE = "NO_CONTENT_CHANGE";
  public static final String INVALID_GOVERNANCE_TRANSITION = "INVALID_GOVERNANCE_TRANSITION";
  public static final String REVISION_NOT_CURRENT = "REVISION_NOT_CURRENT";
  public static final String SUBMISSION_ALREADY_OPEN = "SUBMISSION_ALREADY_OPEN";
  public static final String SEGREGATION_OF_DUTIES_VIOLATION = "SEGREGATION_OF_DUTIES_VIOLATION";
  public static final String JUSTIFICATION_REQUIRED = "JUSTIFICATION_REQUIRED";
  public static final String NOT_EFFECTIVELY_PUBLISHABLE = "NOT_EFFECTIVELY_PUBLISHABLE";
  public static final String PUBLICATION_WINDOW_NOT_OPEN = "PUBLICATION_WINDOW_NOT_OPEN";
  public static final String PUBLICATION_NOT_EXPIRED = "PUBLICATION_NOT_EXPIRED";
  public static final String OPPORTUNITY_NOT_PUBLISHED = "OPPORTUNITY_NOT_PUBLISHED";
  public static final String APPROVED_REVISION_MISMATCH = "APPROVED_REVISION_MISMATCH";
  public static final String LINK_PLACEMENT_CONFLICT = "LINK_PLACEMENT_CONFLICT";
  public static final String LINK_EXPIRY_INVALID = "LINK_EXPIRY_INVALID";
  public static final String INVALID_PUBLISHER_CONTEXT = "INVALID_PUBLISHER_CONTEXT";
  public static final String REQUIRED_PUBLISHER_CONTEXT_MISSING =
      "REQUIRED_PUBLISHER_CONTEXT_MISSING";
  public static final String CONTEXT_LINK_NOT_FOUND = "CONTEXT_LINK_NOT_FOUND";
  public static final String CONTEXT_LINK_REVOKED = "CONTEXT_LINK_REVOKED";
  public static final String CONTEXT_LINK_EXPIRED = "CONTEXT_LINK_EXPIRED";
  public static final String CONTEXT_LINK_UNAVAILABLE = "CONTEXT_LINK_UNAVAILABLE";
  public static final String CONTEXT_LINK_TEMPORARILY_UNAVAILABLE =
      "CONTEXT_LINK_TEMPORARILY_UNAVAILABLE";
  public static final String CONSENT_NOTICE_NOT_FOUND = "CONSENT_NOTICE_NOT_FOUND";
  public static final String CONSENT_NOTICE_NOT_APPROVED = "CONSENT_NOTICE_NOT_APPROVED";
  public static final String CONSENT_NOTICE_OBSOLETE = "CONSENT_NOTICE_OBSOLETE";
  public static final String CONSENT_NOTICE_CONFLICT = "CONSENT_NOTICE_CONFLICT";
  public static final String CONTEXT_INSTANCE_NOT_FOUND = "CONTEXT_INSTANCE_NOT_FOUND";
  public static final String CONTEXT_INSTANCE_EXPIRED = "CONTEXT_INSTANCE_EXPIRED";
  public static final String CONTEXT_INSTANCE_UNAUTHORIZED = "CONTEXT_INSTANCE_UNAUTHORIZED";
  public static final String INVALID_COLLECTED_VALUE = "INVALID_COLLECTED_VALUE";
  public static final String CONTINUITY_UNAVAILABLE = "CONTINUITY_UNAVAILABLE";
  public static final String INSTANCE_CREDENTIAL_REQUIRED = "INSTANCE_CREDENTIAL_REQUIRED";
  public static final String INSTANCE_CREDENTIAL_NOT_REPLAYABLE = "INSTANCE_CREDENTIAL_NOT_REPLAYABLE";
  public static final String IDEMPOTENCY_KEY_REQUIRED = "IDEMPOTENCY_KEY_REQUIRED";
  public static final String IDEMPOTENCY_KEY_INVALID = "IDEMPOTENCY_KEY_INVALID";
  public static final String DEMONSTRATION_KEY_CONFLICT = "DEMONSTRATION_KEY_CONFLICT";
  public static final String DEMONSTRATION_NOT_PUBLISHED = "DEMONSTRATION_NOT_PUBLISHED";

  private ApiErrorCodes() {}
}
