"""CI helper: fail if committed openapi.json drifts from app.openapi().

Exit 0 = in sync; exit 1 = drift or invalid contract.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

os.environ.setdefault(
    "DATABASE_URL_ADMIN",
    "postgresql+psycopg://admin:password123@localhost:5433/qmind",
)
os.environ.setdefault(
    "DATABASE_URL_APP",
    "postgresql+psycopg://qmind_app:qmind_app_dev@localhost:5433/qmind",
)
os.environ.setdefault("AUTH_MODE", "dev")
os.environ.setdefault("ENVIRONMENT", "local")
os.environ.setdefault("STORAGE_BACKEND", "memory")

from app.main import app  # noqa: E402
from app.openapi_contract import dump_openapi_json  # noqa: E402

COMMITTED = ROOT / "openapi" / "openapi.json"


def main() -> int:
    if not COMMITTED.is_file():
        print(f"MISSING {COMMITTED}", file=sys.stderr)
        return 1
    app.openapi_schema = None
    generated = dump_openapi_json(app)
    committed = COMMITTED.read_text(encoding="utf-8")
    if generated != committed:
        print("OpenAPI drift detected. Run: python scripts/export_openapi.py", file=sys.stderr)
        print(f"committed bytes={len(committed)} generated bytes={len(generated)}", file=sys.stderr)
        return 1
    print(f"OpenAPI in sync: {COMMITTED}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
