import type {
  BoardCard,
  Catalog,
  Envelope,
  ExecutionView,
  MaterialsView,
  Me,
  Order,
  Page,
  Plan,
  PlanDetail,
  SheetIssue,
  StepsView,
  Traceability,
  WeighingsView,
} from "./types";

export const ORG_A = "11111111-1111-1111-1111-111111111111";
export const ORG_B = "22222222-2222-2222-2222-222222222222";
export const ORDER_ID = "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa";
export const PLAN_ID = "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb";
export const ISSUE_ID = "cccccccc-cccc-cccc-cccc-cccccccccccc";

export const meFixture: Me = {
  user_id: "dddddddd-dddd-dddd-dddd-dddddddddddd",
  display_name: "Ana Padeiro",
  status: "active",
  selected_organization_id: ORG_A,
  associations: [
    {
      organization_id: ORG_A,
      display_name: "Padaria Central",
      slug: "padaria-central",
      roles: ["production_manager", "viewer"],
      status: "active",
      permissions: [
        "identity.read_me",
        "organization.read",
        "membership.read",
        "production.board.read",
        "production.plan.read",
        "production.order.read",
        "production.traceability.read",
        "ingredient.read",
        "ingredient.create",
        "ingredient.update_draft",
        "ingredient.publish",
        "supplier.read",
        "supplier.manage",
        "supplier.price.record",
        "recipe.read",
        "recipe.create",
        "recipe.update_draft",
        "recipe.version.create",
        "recipe.scale",
        "recipe.trial.manage",
        "recipe.review",
        "recipe.approve",
        "recipe.publish",
        "recipe.retire",
        "recipe.reference.manage",
        "recipe.technical_sheet.read",
        "recipe.ai.propose",
        "recipe.ai.review",
        "recipe.ai.materialize",
        "labeling.read",
        "labeling.dossier.create",
        "labeling.evaluate",
        "labeling.candidate.edit",
        "labeling.review",
        "labeling.render",
        "labeling.invalidate",
        "regulatory.source.read",
      ],
    },
    {
      organization_id: ORG_B,
      display_name: "Atelier Norte",
      slug: "atelier-norte",
      roles: ["viewer"],
      status: "active",
      permissions: [
        "identity.read_me",
        "organization.read",
        "membership.read",
        "production.board.read",
        "production.plan.read",
        "production.order.read",
        "ingredient.read",
        "supplier.read",
        "recipe.read",
        "recipe.technical_sheet.read",
      ],
    },
  ],
  roles: ["production_manager", "viewer"],
  permissions: [
    "identity.read_me",
    "organization.read",
    "membership.read",
    "production.board.read",
    "production.plan.read",
    "production.order.read",
    "production.traceability.read",
    "ingredient.read",
    "ingredient.create",
    "ingredient.update_draft",
    "ingredient.publish",
    "supplier.read",
    "supplier.manage",
    "supplier.price.record",
    "recipe.read",
    "recipe.create",
    "recipe.update_draft",
    "recipe.version.create",
    "recipe.scale",
    "recipe.trial.manage",
    "recipe.review",
    "recipe.approve",
    "recipe.publish",
    "recipe.retire",
    "recipe.reference.manage",
    "recipe.technical_sheet.read",
    "recipe.ai.propose",
    "recipe.ai.review",
    "recipe.ai.materialize",
    "labeling.read",
    "labeling.dossier.create",
    "labeling.evaluate",
    "labeling.candidate.edit",
    "labeling.review",
    "labeling.render",
    "labeling.invalidate",
    "regulatory.source.read",
  ],
};

export const RECIPE_ID = "99999999-9999-9999-9999-999999999999";
export const RECIPE_VERSION_ID = "88888888-8888-8888-8888-888888888888";
export const PROPOSAL_ID = "77777777-7777-7777-7777-777777777777";
export const DOSSIER_ID = "55555555-5555-5555-5555-555555555555";

export const labelingDossierFixture = {
  id: DOSSIER_ID,
  status: "evaluated",
  formulation_id: RECIPE_ID,
  formulation_version_id: RECIPE_VERSION_ID,
  row_version: 2,
  disclaimer: "Proposta técnica para revisão. Não é declaração de conformidade.",
  certified: false,
  conforme_anvisa: false,
  profile: {
    completeness: "complete",
    jurisdiction: "BR",
    packed_food: true,
    physical_state: "solid",
    regulatory_category_code: "pao",
    category_confirmed: true,
  },
  versions: [
    { id: "v1", version_number: 1, status: "evaluated", content_hash: "aaa" },
    { id: "v2", version_number: 2, status: "evaluated", content_hash: "bbb" },
  ],
  current: {
    version: { id: "v2", version_number: 2, status: "evaluated", content_hash: "bbb" },
    assessment: {
      status: "evaluated",
      proposal_summary: "Proposta técnica para revisão humana. Não é declaração de conformidade.",
    },
    findings: [
      {
        rule_code: "fop_added_sugars",
        result: "fail",
        fact: "limite da lupa",
        expected_value: ">= 15",
        found_value: "16",
        source_code: "in-75-2020",
        source_locator: "Anexo XV IN 75",
        explanation: "Ausência de nutriente não presume ausência de lupa.",
        action_needed: true,
      },
    ],
    nutrition: {
      portion_g: "50.000000",
      household_measure: "1 unidade",
      footnotes: ["Valores declarados são projeção regulatória, não certificado."],
      lines: [
        {
          nutrient_code: "energy_kcal",
          technical_per_100g: "280",
          declared_per_100g: "280",
          declared_per_serving: "140",
          daily_value_percent: "14",
          completeness: "complete",
          presented: "280",
        },
        {
          nutrient_code: "added_sugars",
          technical_per_100g: null,
          declared_per_100g: null,
          declared_per_serving: null,
          daily_value_percent: null,
          completeness: "insufficient_evidence",
          presented: null,
        },
      ],
    },
    front_of_pack: {
      added_sugars_result: "insufficient_evidence",
      saturated_fat_result: "below",
      sodium_result: "below",
      magnifier_required: null,
      nutrients_high: [],
      compared: { thresholds: { added_sugars: "15", saturated_fat: "6", sodium: "600" } },
      disclaimer: "Representação candidata da lupa. Não é arte-final certificada.",
    },
    ingredients: [{ sequence: 1, display_name: "Farinha de trigo", compound: false, components: [], gap: null }],
    warnings: [
      {
        code: "gluten_unknown",
        statement: "Declaração de glúten pendente. Ausência na fórmula não prova ausência.",
        result: "insufficient_evidence",
      },
    ],
    mandatory: [
      { code: "lote", label: "Lote", value: null, status: "pending", claim: false },
      { code: "lista_ingredientes", label: "Lista de ingredientes", value: "lista gerada", status: "filled", claim: false },
    ],
    candidate: {
      watermark: "Proposta técnica para revisão",
      payload_sha256: "bbb",
      payload: { title: "Pão francês", disclaimer: "Candidato para conferência." },
    },
    reviews: [],
  },
};

export const proposalFixture = {
  id: PROPOSAL_ID,
  intent: "create_recipe" as const,
  title: "Pão de teste assistivo",
  objective_summary: "Criar pão com farinha de trigo",
  status: "draft",
  status_label: "aguardando revisão",
  assisted_by_ai: true,
  base_formulation_version_id: null,
  materialized_formulation_version_id: null,
  warnings: ["Sugestão assistiva da Panne; não é formulação oficial, aprovada ou publicada."],
  missing_data: [],
  row_version: 1,
  items: [
    {
      id: "pi1",
      sequence: 1,
      ingredient_version_id: "ffffffff-ffff-ffff-ffff-ffffffffffff",
      proposed_ingredient_name: "Farinha",
      resolution_status: "resolved",
      net_quantity_g: "100",
      rationale: "Sugestão a partir da evidência.",
    },
  ],
  steps: [{ sequence: 1, title: "Misturar", instructions: "Misturar os ingredientes sugeridos." }],
  citations: [{ id: "c1", claim_path: "items[1].rationale" }],
  changes: [
    {
      change_key: "added:ffffffff-ffff-ffff-ffff-ffffffffffff",
      change_kind: "added" as const,
      path: "items[1]",
      before_value: null,
      after_value: { name: "Farinha", net_quantity_g: "100" },
      decision: "pending" as const,
    },
  ],
  materialized: null,
  guided_input: { objective: "Criar pão com farinha de trigo" },
};

export const boardFixture: BoardCard[] = [
  {
    order: {
      id: ORDER_ID,
      public_code: "OP-2026-0001",
      status: "in_progress",
      priority: 1,
      row_version: 4,
    },
    batches: [
      {
        id: "batch-1",
        production_order_id: ORDER_ID,
        sequence: 1,
        operational_code: "B1",
        target_mode: "mass",
        target_quantity: "12000",
        status: "in_progress",
        row_version: 2,
        planned_start_at: "2026-08-22T11:00:00+00:00",
        planned_end_at: "2026-08-22T14:00:00+00:00",
      },
    ],
    product: { id: "prod-1", code: "PAO-TRAD", display_name: "Pão tradicional" },
    quantity: "12000",
    target_mode: "mass",
    planned_start_at: "2026-08-22T11:00:00+00:00",
    planned_end_at: "2026-08-22T14:00:00+00:00",
    operational_date: "2026-08-22",
    shift: "morning",
    current_step: "Fermentação",
    dependencies: [],
    blocked: false,
    open_occurrences: 1,
    delayed: true,
    next_action: "complete_step",
    has_execution_facts: true,
  },
];

export const plansFixture: Page<Plan> = {
  items: [
    {
      id: PLAN_ID,
      public_code: "PL-2026-0008",
      establishment_id: "est-1",
      operational_date: "2026-08-22",
      shift: "morning",
      status: "scheduled",
      notes: null,
      row_version: 1,
      created_at: "2026-08-21T10:00:00+00:00",
      updated_at: "2026-08-21T10:00:00+00:00",
      scheduled_at: "2026-08-21T12:00:00+00:00",
    },
  ],
  next_cursor: null,
};

export const planDetailFixture: Envelope<PlanDetail> = {
  data: {
    ...plansFixture.items[0],
    items: [
      {
        id: "item-1",
        technical_product_id: "prod-1",
        target_mode: "mass",
        target_quantity: "12000",
        unit_weight_g: null,
        priority: 1,
        sort_order: 1,
        notes: null,
      },
    ],
  },
  row_version: 1,
};

export const ordersFixture: Page<Order> = {
  items: [
    {
      id: ORDER_ID,
      public_code: "OP-2026-0001",
      establishment_id: "est-1",
      plan_id: PLAN_ID,
      technical_product_id: "prod-1",
      target_mode: "mass",
      target_quantity: "12000",
      priority: 1,
      status: "in_progress",
      planned_start_at: "2026-08-22T11:00:00+00:00",
      planned_end_at: "2026-08-22T14:00:00+00:00",
      row_version: 4,
      materials_hash: "abc123",
      steps_hash: "def456",
      snapshot_hash: "ghi789",
    },
  ],
  next_cursor: null,
};

export const materialsFixture: Envelope<MaterialsView> = {
  data: {
    planned: [{ id: "mat-1", name: "Farinha de trigo", gross: "7000", unit: "g" }],
    actual: [
      {
        id: "bmat-1",
        planned_gross: "7000",
        weighed_canonical: "6998",
        consumption: { use: "6990", waste: "8" },
      },
    ],
  },
};

export const stepsFixture: Envelope<StepsView> = {
  data: {
    planned: [{ id: "step-1", title: "Fermentação", sequence: 1 }],
    actual: [{ id: "run-1", status: "in_progress" }],
  },
};

export const weighingsFixture: Envelope<WeighingsView> = {
  data: {
    entries: [
      {
        id: "w-1",
        entered_quantity: "7",
        entered_unit: "kg",
        canonical_quantity: "7000",
        canonical_unit: "g",
        conversion_factor: "1000",
        conversion_source: "unit_catalog",
        conversion_version: "1",
      },
    ],
    verifications: [{ id: "v-1", entry_id: "w-1", decision: "accepted" }],
  },
};

export const sheetFixture: Envelope<SheetIssue> = {
  data: {
    id: ISSUE_ID,
    issue_number: 2,
    purpose: "operational",
    order_status_at_issue: "in_progress",
    previous_issue_id: "prev-issue",
    payload_sha256: "fff111",
    canonical_payload: {
      schema_version: "2",
      establishment: { id: "est-1", code: "E1", display_name: "Padaria Central" },
      organization: { id: ORG_A, slug: "padaria-central", display_name: "Padaria Central" },
      issuer: { user_id: meFixture.user_id, display_name: "Ana Padeiro", issued_at: "2026-08-23T12:00:00+00:00" },
      order: {
        id: ORDER_ID,
        public_code: "OP-2026-0001",
        status: "in_progress",
        target_mode: "mass",
        target_quantity: "12000",
        materials_hash: "abc123",
        steps_hash: "def456",
        snapshot_hash: "ghi789",
        policy_hash: "pol999",
      },
      policy: { algorithm_code: "weighing.v1", algorithm_version: "1" },
      materials: [{ sequence: 1, name: "Farinha de trigo", unit: "g", gross: "7000", net: "7000" }],
      steps: [{ sequence: 1, title: "Fermentação", instructions: "Manter 24 °C por 60 min" }],
      batches: [{ sequence: 1, operational_code: "B1", target: "12000", status: "in_progress" }],
    },
  },
};

export const catalogFixture: Envelope<Catalog> = {
  data: {
    mass_units: [
      { id: "unit-g", code: "g", name: "grama", symbol: "g", dimension: "mass" },
      { id: "unit-kg", code: "kg", name: "quilograma", symbol: "kg", dimension: "mass" },
    ],
    yield_types: [
      "pre_bake_mass",
      "post_bake_mass",
      "good_units",
      "rejected_units",
      "leftover",
      "scrap",
    ],
    occurrence_categories: ["quality", "material", "time"],
    occurrence_severities: ["low", "medium", "high", "critical"],
    consumption_types: ["consume", "return", "waste", "correction"],
    verification_decisions: ["accepted", "rejected"],
    sheet_purposes: ["operational", "contingency"],
    weighing_policies: ["required"],
    verification_policies: ["second_person"],
    order_statuses: ["in_progress", "completed", "short_closed"],
    batch_statuses: ["in_progress"],
    step_statuses: ["pending", "in_progress", "completed"],
  },
};

export const operatorMeFixture: Me = {
  ...meFixture,
  associations: meFixture.associations.map((item, index) =>
    index === 0
      ? {
          ...item,
          roles: ["baker_operator"],
          permissions: [
            ...item.permissions,
            "production.weighing.record",
            "production.weighing.verify",
            "production.consumption.record",
            "production.step.execute",
            "production.occurrence.record",
            "production.occurrence.resolve",
            "production.order.complete",
            "production.order.short_close",
            "production.sheet.issue",
          ],
        }
      : item,
  ),
  permissions: [
    ...meFixture.permissions,
    "production.weighing.record",
    "production.weighing.verify",
    "production.consumption.record",
    "production.step.execute",
    "production.occurrence.record",
    "production.occurrence.resolve",
    "production.order.complete",
    "production.order.short_close",
    "production.sheet.issue",
  ],
};

export const executionFixture: Envelope<ExecutionView> = {
  data: {
    viewer: {
      user_id: meFixture.user_id,
      display_name: "Ana Padeiro",
      permissions: operatorMeFixture.permissions,
    },
    order: ordersFixture.items[0],
    product: { id: "prod-1", code: "PAO-TRAD", display_name: "Pão tradicional" },
    establishment: { id: "est-1", code: "E1", display_name: "Padaria Central" },
    policy: {
      verification_policy: "second_person",
      require_manual_lot: false,
      completion_tolerance: "5",
    },
    batches: [
      {
        ...boardFixture[0].batches[0],
        materials: [
          {
            id: "bmat-1",
            batch_id: "batch-1",
            name: "Farinha de trigo",
            measurement_unit_id: "unit-g",
            unit: "g",
            planned_gross: "7000",
            weighed_canonical: "6998",
            weigh_state: "awaiting_verification",
            consumption: { consume: "0", return: "0", waste: "0", net: "0" },
          },
        ],
        sessions: [{ id: "sess-1", status: "open", row_version: 1, opened_by_user_id: meFixture.user_id }],
        weighings: [
          {
            id: "w-1",
            session_id: "sess-1",
            batch_material_id: "bmat-1",
            entry_type: "record",
            measurement_unit_id: "unit-kg",
            operator_user_id: meFixture.user_id,
            operator_name: "Ana Padeiro",
            lot_code: "L-88",
            justification: null,
            planned_quantity: "7000",
            absolute_difference: "2",
            percent_difference: "0.03",
            within_tolerance: false,
            verification: null,
            entered_quantity: "7",
            entered_unit: "kg",
            canonical_quantity: "7000",
            canonical_unit: "g",
            conversion_factor: "1000",
            conversion_source: "unit_catalog",
            conversion_version: "1",
          },
        ],
        steps: [
          {
            order_step_id: "step-1",
            batch_id: "batch-1",
            title: "Fermentação",
            instructions: "Manter 24 °C",
            sequence: 1,
            duration_seconds: 3600,
            temperature_value: "24",
            temperature_unit: "C",
            execution_id: "run-1",
            status: "in_progress",
            row_version: 2,
            operator_user_id: meFixture.user_id,
            operator_name: "Ana Padeiro",
            started_at: "2026-08-23T12:00:00.000Z",
            ended_at: null,
            measured_duration_seconds: null,
            measured_temperature: null,
            notes: null,
          },
          {
            order_step_id: "step-2",
            batch_id: "batch-1",
            title: "Fornada",
            instructions: "Assar até dourar",
            sequence: 2,
            duration_seconds: 1200,
            temperature_value: "220",
            temperature_unit: "C",
            execution_id: null,
            status: "pending",
            row_version: null,
            operator_user_id: null,
            operator_name: null,
            started_at: null,
            ended_at: null,
            measured_duration_seconds: null,
            measured_temperature: null,
            notes: null,
          },
        ],
        yields: [{ id: "y-1", type: "pre_bake_mass", quantity: "11800", unit: "g", measurement_unit_id: "unit-g", notes: null }],
        yield_projection: {
          final_mass: "11800",
          sellable_units: null,
          rejected_units: null,
          leftover: null,
          scrap: null,
          loss_absolute: null,
          loss_percent: null,
          target_deviation: "-200",
          completeness: "complete",
          within_tolerance: true,
        },
      },
    ],
    occurrences: [
      {
        id: "o-1",
        category: "quality",
        severity: "high",
        status: "open",
        description: "Crosta irregular",
        is_blocking: true,
        batch_id: "batch-1",
        order_step_id: "step-1",
      },
    ],
    dependencies: [],
    sheets: [{ id: ISSUE_ID, issue_number: 2, payload_sha256: "fff111", purpose: "operational", previous_issue_id: "prev-issue" }],
    blocked: true,
    open_session: true,
    next_action: "complete_step",
    readiness: {
      weighing: { ok: false, reason: "pesagem incompleta" },
      verifications: { ok: false, reason: "aguardando conferência por outro usuário" },
      steps: { ok: false, reason: "etapas incompletas" },
      consumptions: { ok: false, reason: "consumo mínimo ausente" },
      yields: { ok: true, reason: null },
      dependencies: { ok: true, reason: null },
      blocking_occurrences: { ok: false, reason: "ocorrência bloqueante aberta" },
      permissions: {
        complete: true,
        short_close: true,
        weighing_record: true,
        weighing_verify: true,
        consumption: true,
        step: true,
        occurrence_record: true,
        occurrence_resolve: true,
        batch_complete: true,
        sheet: true,
      },
    },
    updated_at: "2026-08-23T12:10:00.000Z",
  },
};

export const cancelledSheetFixture: Envelope<SheetIssue> = {
  data: {
    ...sheetFixture.data,
    order_status_at_issue: "cancelled",
    previous_issue_id: "prev-issue",
  },
};

export const traceFixture: Envelope<Traceability> = {
  data: {
    order: {
      id: ORDER_ID,
      public_code: "OP-2026-0001",
      status: "in_progress",
      formulation_version_id: "form-1",
      scale_calculation_id: "scale-1",
      materials_hash: "abc123",
      steps_hash: "def456",
      snapshot_hash: "ghi789",
      policy_hash: "pol999",
    },
    batches: [{ id: "batch-1", operational_code: "B1", status: "in_progress" }],
    planned_materials: [{ id: "mat-1", name: "Farinha de trigo", gross: "7000", unit: "g" }],
    planned_steps: [{ id: "step-1", title: "Fermentação" }],
    actual_materials: [
      {
        batch_material_id: "bmat-1",
        planned_gross: "7000",
        weighed_canonical: "6998",
        consumption: { use: "6990" },
      },
    ],
    weighings: [
      {
        id: "w-1",
        lot_code: "L-88",
        operator_user_id: "op-1",
        entered_quantity: "7",
        entered_unit: "kg",
        canonical_quantity: "7000",
        canonical_unit: "g",
        conversion_factor: "1000",
        conversion_source: "unit_catalog",
        conversion_version: "1",
      },
    ],
    verifications: [
      { id: "v-1", entry_id: "w-1", decision: "accepted", verifier_user_id: "op-2" },
    ],
    consumptions: [
      {
        id: "c-1",
        type: "use",
        entered_quantity: "6990",
        entered_unit: "g",
        canonical_quantity: "6990",
        canonical_unit: "g",
        conversion_factor: "1",
        conversion_source: "unit_catalog",
        conversion_version: "1",
      },
    ],
    step_runs: [{ id: "run-1", status: "in_progress", operator_user_id: "op-1" }],
    yields: [{ id: "y-1", type: "actual", quantity: "11800" }],
    occurrences: [{ id: "o-1", category: "delay", status: "open" }],
    dependencies: [],
    overrides: [],
    sheet_issues: [{ id: ISSUE_ID, issue_number: 2, payload_sha256: "fff111" }],
    events: [
      {
        id: "e-1",
        type: "order.released",
        command: "release_order",
        occurred_at: "2026-08-22T10:00:00+00:00",
      },
    ],
  },
};
