"""Constantes do domínio Produto (CURSOR-028-C)."""

STATUS_ACTIVE = "active"
STATUS_INACTIVE = "inactive"
PRODUCT_STATUSES = frozenset({STATUS_ACTIVE, STATUS_INACTIVE})

PURPOSE_FINAL = "final"
PURPOSE_INTERMEDIATE = "intermediate"
PRODUCT_PURPOSES = frozenset({PURPOSE_FINAL, PURPOSE_INTERMEDIATE})

SUPPLY_PRODUCED = "produced"
SUPPLY_PURCHASED = "purchased"
SUPPLY_MIXED = "mixed"
SUPPLY_COMBO = "combo"
PRODUCT_SUPPLY_MODES = frozenset({SUPPLY_PRODUCED, SUPPLY_PURCHASED, SUPPLY_MIXED, SUPPLY_COMBO})
SUPPLY_MODES_OPERATIONAL = frozenset({SUPPLY_PRODUCED, SUPPLY_PURCHASED})

FAMILY_STATUSES = frozenset({STATUS_ACTIVE, STATUS_INACTIVE})
