/**
 * Catálogo Gestão Técnica (grupo "Técnica") — códigos, fórmulas mathjs e parâmetros.
 * Fonte: planilha institucional de indicadores SPACE / IAPS.
 */
const GESTAO_TECNICA_CATALOGO = [
  {
    cod_indicador: "S001",
    nome_indicador: "Carga Cognitiva Individual",
    nome_grupo: "Técnica",
    dimensao: "Satisfação",
    nivel_avaliacao: "Individual",
    formula_normalizada: "((mli - 1) / 4) * 100",
    parametros_configuraveis: { escala_likert_min: 1, escala_likert_max: 5 },
  },
  {
    cod_indicador: "S002",
    nome_indicador: "eNPS do Processo",
    nome_grupo: "Técnica",
    dimensao: "Satisfação",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(prom / (prom + detrat)) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "P001",
    nome_indicador: "Business Value per Sprint",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Individual",
    formula_normalizada: "((ir + sr + rs + eo + rc) / (5 * sc)) * 100",
    parametros_configuraveis: { escala_likert: 5 },
  },
  {
    cod_indicador: "P002",
    nome_indicador: "Product Market Fit",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(ac / ua) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "P003",
    nome_indicador: "Velocidade de Desbloqueio",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Individual",
    formula_normalizada: "(tr / bt) * 100",
    parametros_configuraveis: { limite_horas: 4 },
  },
  {
    cod_indicador: "P004",
    nome_indicador: "Predictability",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(pe / pp) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "P005",
    nome_indicador: "SLA Compliance (Internal)",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Individual",
    formula_normalizada: "(cmpp / zmpt) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "P006",
    nome_indicador: "Business Impact ROI",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(bve / coe) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "A001",
    nome_indicador: "Backlog Health",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Individual",
    formula_normalizada: "(ca / bp) * 100",
    parametros_configuraveis: { n_sprints: 3 },
  },
  {
    cod_indicador: "A002",
    nome_indicador: "Feature Delivery Rate",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(fd / fp) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "A003",
    nome_indicador: "Cerimonias Atendidas",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Individual",
    formula_normalizada: "(pa / ts) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "A004",
    nome_indicador: "Cycle Time Variance",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(dv / mi) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "A005",
    nome_indicador: "Resource Allocation Balance",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Individual",
    formula_normalizada: "1 - abs(spr - spi)",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "A006",
    nome_indicador: "Strategic Milestone Progress",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(mt / mp) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "C001",
    nome_indicador: "SLA Compliance (Prazos Técnicos)",
    nome_grupo: "Técnica",
    dimensao: "Comunicação",
    nivel_avaliacao: "Individual",
    formula_normalizada: "(it / tq) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "C002",
    nome_indicador: "Cross-team Alignment",
    nome_grupo: "Técnica",
    dimensao: "Comunicação",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(dr / i3us) * 100",
    parametros_configuraveis: { janela_sprints: 3 },
  },
  {
    cod_indicador: "C003",
    nome_indicador: "Team Health Check",
    nome_grupo: "Técnica",
    dimensao: "Comunicação",
    nivel_avaliacao: "Individual",
    formula_normalizada: "((gm3s - 1) / 4) * 100",
    parametros_configuraveis: { escala_likert_min: 1, escala_likert_max: 5 },
  },
  {
    cod_indicador: "C004",
    nome_indicador: "Stakeholder Satisfaction",
    nome_grupo: "Técnica",
    dimensao: "Comunicação",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "((m3Gs - 1) / 4) * 100",
    parametros_configuraveis: { escala_likert_min: 1, escala_likert_max: 5 },
  },
  {
    cod_indicador: "C005",
    nome_indicador: "Strategic Stakeholder Trust Score",
    nome_grupo: "Técnica",
    dimensao: "Comunicação",
    nivel_avaliacao: "Individual",
    formula_normalizada: "((m3GEs - 1) / 4) * 100",
    parametros_configuraveis: { escala_likert_min: 1, escala_likert_max: 5 },
  },
  {
    cod_indicador: "E001",
    nome_indicador: "Requirement Lead Time",
    nome_grupo: "Técnica",
    dimensao: "Eficiência",
    nivel_avaliacao: "Individual",
    formula_normalizada: "(1 - (mwi / mWE)) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "E002",
    nome_indicador: "Value Stream Efficiency",
    nome_grupo: "Técnica",
    dimensao: "Eficiência",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(ta / lt) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "E003",
    nome_indicador: "Meeting Load",
    nome_grupo: "Técnica",
    dimensao: "Eficiência",
    nivel_avaliacao: "Individual",
    formula_normalizada: "(hr / fte) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "E004",
    nome_indicador: "Time to Recover (MTTR)",
    nome_grupo: "Técnica",
    dimensao: "Eficiência",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(ir / it) * 100",
    parametros_configuraveis: { limite_horas: 2 },
  },
];

/**
 * Planilha Técnica (execução Dev/QA/Arquitetura) — grupo "Técnica".
 * Complementa a planilha Gestão Técnica; em conflito de código, esta prevalece no upsert.
 */
const TECNICA_CATALOGO = [
  {
    cod_indicador: "S001",
    nome_indicador: "Carga Cognitiva Individual",
    nome_grupo: "Técnica",
    dimensao: "Satisfação",
    nivel_avaliacao: "Individual",
    formula_normalizada: "((ml - 1) / 4) * 100",
    parametros_configuraveis: { escala_likert_min: 1, escala_likert_max: 5 },
  },
  {
    cod_indicador: "S002",
    nome_indicador: "eNPS do Processo",
    nome_grupo: "Técnica",
    dimensao: "Satisfação",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(prom / (prom + detrat)) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "P007",
    nome_indicador: "Taxa de Retrabalho",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Individual",
    formula_normalizada: "1 - (ir / ie)",
    parametros_configuraveis: { janela_sprints: 3 },
    subpapeis_aplicaveis: ["Dev", "Tester"],
  },
  {
    cod_indicador: "P008",
    nome_indicador: "Change Failure Rate",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "1 - (df / dr)",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "P009",
    nome_indicador: "Aderência Arquitetural",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Individual",
    formula_normalizada: "1 - (carc / pr)",
    parametros_configuraveis: { janela_sprints: 3 },
  },
  {
    cod_indicador: "P010",
    nome_indicador: "Stability Index",
    nome_grupo: "Técnica",
    dimensao: "Performance",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "(mtbf * ip) / tt",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "A007",
    nome_indicador: "Throughput de PRs",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Individual",
    formula_normalizada: "pra / mvt",
    parametros_configuraveis: { janela_sprints: 3 },
  },
  {
    cod_indicador: "A008",
    nome_indicador: "Deployment Frequency",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "dprod / dup",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "A009",
    nome_indicador: "Test Coverage",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Individual",
    formula_normalizada: "sta / sdp",
    parametros_configuraveis: { janela_sprints: 3 },
  },
  {
    cod_indicador: "A010",
    nome_indicador: "Defect Detection Efficiency (DDE)",
    nome_grupo: "Técnica",
    dimensao: "Atividade",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "btes / (btes + bprod)",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "C006",
    nome_indicador: "Review Response Time",
    nome_grupo: "Técnica",
    dimensao: "Comunicação",
    nivel_avaliacao: "Individual",
    formula_normalizada: "trev / mter",
    parametros_configuraveis: { janela_sprints: 3 },
  },
  {
    cod_indicador: "C007",
    nome_indicador: "Knowledge Spread (Bus Factor)",
    nome_grupo: "Técnica",
    dimensao: "Comunicação",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "comcod / pcrit",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "C008",
    nome_indicador: "Documentação Técnica",
    nome_grupo: "Técnica",
    dimensao: "Comunicação",
    nivel_avaliacao: "Individual",
    formula_normalizada: "wdr / ics",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "E005",
    nome_indicador: "Focus Time (Deep Work)",
    nome_grupo: "Técnica",
    dimensao: "Eficiência",
    nivel_avaliacao: "Individual",
    formula_normalizada: "((ttj - trs) / 2) / (bet / bfl)",
    parametros_configuraveis: { bloco_flow_horas: 2 },
  },
  {
    cod_indicador: "E006",
    nome_indicador: "Flow Efficiency",
    nome_grupo: "Técnica",
    dimensao: "Eficiência",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "tec / ctt",
    parametros_configuraveis: { janela_sprints: 3 },
  },
  {
    cod_indicador: "E007",
    nome_indicador: "Time to Sandbox",
    nome_grupo: "Técnica",
    dimensao: "Eficiência",
    nivel_avaliacao: "Individual",
    formula_normalizada: "1 - (rttdev / 8)",
    parametros_configuraveis: { limite_horas: 8 },
  },
  {
    cod_indicador: "E008",
    nome_indicador: "Cycle Time",
    nome_grupo: "Técnica",
    dimensao: "Eficiência",
    nivel_avaliacao: "Equipe",
    formula_normalizada: "1 - (dpcy / mcy)",
    parametros_configuraveis: { janela_sprints: 3 },
  },
];

const CATALOGO_TECNICA_COMPLETO = [...GESTAO_TECNICA_CATALOGO, ...TECNICA_CATALOGO];

/** Indicadores de outros grupos (Gerência Técnica / Gestão Geral). */
const FORMULAS_INDICADORES_LEGADO = [
  {
    cod_indicador: "P007",
    nome_grupo: "Gerência Técnica",
    formula_normalizada: "1 - (ir / ie)",
    parametros_configuraveis: { janela_sprints: 3 },
  },
  {
    cod_indicador: "P003",
    nome_grupo: "Gerência Técnica",
    formula_normalizada: "(tr / bt) * 100",
    parametros_configuraveis: { limite_horas: 4 },
  },
  {
    cod_indicador: "P004",
    nome_grupo: "Gerência Técnica",
    formula_normalizada: "(pe / pp) * 100",
    parametros_configuraveis: {},
  },
  {
    cod_indicador: "P001",
    nome_grupo: "Gestão Geral",
    formula_normalizada: "((ir + sr + rs + eo + rc) / (5 * sc)) * 100",
    parametros_configuraveis: { escala_likert: 5 },
  },
  {
    cod_indicador: "P005",
    nome_grupo: "Gestão Geral",
    formula_normalizada: "(cmpp / zmpt) * 100",
    parametros_configuraveis: {},
  },
];

const FORMULAS_INDICADORES_PADRAO = [
  ...CATALOGO_TECNICA_COMPLETO.map((item) => ({
    cod_indicador: item.cod_indicador,
    nome_grupo: item.nome_grupo,
    formula_normalizada: item.formula_normalizada,
    parametros_configuraveis: item.parametros_configuraveis,
  })),
  ...FORMULAS_INDICADORES_LEGADO,
];

module.exports = {
  GESTAO_TECNICA_CATALOGO,
  TECNICA_CATALOGO,
  CATALOGO_TECNICA_COMPLETO,
  FORMULAS_INDICADORES_LEGADO,
  FORMULAS_INDICADORES_PADRAO,
};
