export type GlossaryEntry = {
  code: string;
  title: string;
  short: string;
  detail: string;
  example: string;
  related: string[];
  routes: string[];
  version: 1;
};

export const GLOSSARY: GlossaryEntry[] = [
  {
    code: "ingrediente",
    title: "Ingrediente",
    short: "Identidade de material da organização.",
    detail: "O item estocável aponta para o ingrediente. Versão publicada é imutável.",
    example: "Farinha de trigo tipo 1, versão 3 publicada.",
    related: ["versao", "composicao", "lote"],
    routes: ["/componentes/ingredientes"],
    version: 1,
  },
  {
    code: "versao",
    title: "Versão",
    short: "Recorte imutável após publicação.",
    detail: "Mudança material exige nova versão. Publicada não se reescreve.",
    example: "Versão 2 em rascunho, versão 1 publicada.",
    related: ["ingrediente", "formulação"],
    routes: ["/componentes/ingredientes"],
    version: 1,
  },
  {
    code: "quantidade_bruta",
    title: "Quantidade bruta e líquida",
    short: "Bruta inclui correção; líquida é o uso efetivo.",
    detail: "O fator de correção converte líquida em bruta. Sem float.",
    example: "7000 g líquidas com fator 1,03 → 7210 g brutas.",
    related: ["fator_correcao", "consumo"],
    routes: ["/receitas"],
    version: 1,
  },
  {
    code: "fator_correcao",
    title: "Fator de correção",
    short: "Multiplicador entre líquida e bruta.",
    detail: "Ausência do fator permanece explícita. Não se inventa umidade.",
    example: "Fator 1,00 quando não há perda de processamento.",
    related: ["quantidade_bruta"],
    routes: ["/receitas"],
    version: 1,
  },
  {
    code: "composicao",
    title: "Composição e preparação",
    short: "Ingrediente pode ser composto ou preparado.",
    detail: "Preparação como ingrediente não vira receita automaticamente.",
    example: "Prefermento usado como componente de outra ficha.",
    related: ["ingrediente", "receita"],
    routes: ["/componentes/ingredientes"],
    version: 1,
  },
  {
    code: "referencia",
    title: "Referência",
    short: "Fonte citada da formulação ou da norma.",
    detail: "Não improvisar texto regulatório. Apontar o acervo existente.",
    example: "Fonte técnica da versão publicada, sem HTML livre.",
    related: ["receita", "nutricao"],
    routes: ["/conformidade/fontes"],
    version: 1,
  },
  {
    code: "formulacao",
    title: "Formulação",
    short: "Laboratório técnico da composição.",
    detail: "Base da receita. Escala e percentual do padeiro derivam dela.",
    example: "Formulação 70% hidratação.",
    related: ["receita", "percentual_padeiro"],
    routes: ["/receitas"],
    version: 1,
  },
  {
    code: "produto",
    title: "Produto",
    short: "O que a casa vende, estoca ou produz.",
    detail:
      "Existe por si, com ou sem receita. Produzido sem receita vigente não gera ordem de produção.",
    example: "Pão tradicional produzido na casa; refrigerante comprado pronto.",
    related: ["receita", "ordem"],
    routes: ["/produtos"],
    version: 1,
  },
  {
    code: "receita",
    title: "Receita",
    short: "Ficha técnica versionada para produção.",
    detail: "Não substitui o plano nem o custo. Referência aponta fonte.",
    example: "Pão tradicional, versão 4.",
    related: ["formulacao", "plano"],
    routes: ["/receitas"],
    version: 1,
  },
  {
    code: "percentual_padeiro",
    title: "Percentual do padeiro",
    short: "Farinha = 100%.",
    detail: "Os demais componentes são frações da farinha de referência.",
    example: "Água 65% sobre a farinha.",
    related: ["formulacao", "escala"],
    routes: ["/receitas"],
    version: 1,
  },
  {
    code: "escala",
    title: "Escala",
    short: "Redimensiona a formulação para um alvo.",
    detail: "Mantém proporções. Não altera a versão publicada.",
    example: "Escalar para 12 kg de massa.",
    related: ["formulacao", "ordem"],
    routes: ["/receitas"],
    version: 1,
  },
  {
    code: "plano",
    title: "Plano",
    short: "Intenção de produzir em data e turno.",
    detail: "Gera ordens. Sem estoque automático.",
    example: "PL-2026-0008, manhã na Padaria Central.",
    related: ["ordem", "turno"],
    routes: ["/planejamento"],
    version: 1,
  },
  {
    code: "ordem",
    title: "Ordem",
    short: "Unidade executável do plano.",
    detail: "Tem estado, prioridade e próxima ação. Custos ficam fora do quadro.",
    example: "OP-2026-0001 em pesagem.",
    related: ["batelada", "pesagem"],
    routes: ["/producao", "/ordens"],
    version: 1,
  },
  {
    code: "batelada",
    title: "Batelada",
    short: "Fatia operacional da ordem.",
    detail: "Pode ter código próprio e etapa corrente.",
    example: "B1 da OP-2026-0001.",
    related: ["ordem", "etapa"],
    routes: ["/producao"],
    version: 1,
  },
  {
    code: "pesagem",
    title: "Pesagem",
    short: "Registro operacional de quantidade.",
    detail: "Não é movimento de estoque. Pode exigir segunda conferência.",
    example: "6998 g canônicas contra 7000 g planejadas.",
    related: ["consumo", "ordem"],
    routes: ["/producao/ordens/:orderId/executar"],
    version: 1,
  },
  {
    code: "consumo",
    title: "Consumo",
    short: "Fato soberano da execução.",
    detail: "O estoque apenas posta referência. Não apaga o fato operacional.",
    example: "Consumo 6990 g, desperdício 8 g.",
    related: ["desperdicio", "lote"],
    routes: ["/producao/ordens/:orderId/executar"],
    version: 1,
  },
  {
    code: "etapa",
    title: "Etapa",
    short: "Passo do processo da ordem.",
    detail: "Tem estado e instrução. Bloqueio pode vir de ocorrência.",
    example: "Fermentação em execução.",
    related: ["ocorrencia", "ordem"],
    routes: ["/producao"],
    version: 1,
  },
  {
    code: "ocorrencia",
    title: "Ocorrência",
    short: "Evento que exige atenção humana.",
    detail: "Não deve ser ocultada para “bater” o turno.",
    example: "Qualidade: massa fria demais.",
    related: ["etapa", "bloqueio"],
    routes: ["/producao"],
    version: 1,
  },
  {
    code: "rendimento",
    title: "Rendimento, perda, desperdício, sobra e retrabalho",
    short: "Resultados mensurados, sem eufemismo.",
    detail: "Perda e desperdício permanecem visíveis. Retrabalho é fato, não prêmio.",
    example: "Sobra 400 g; desperdício 8 g.",
    related: ["consumo", "custo_realizado"],
    routes: ["/gestao/relatorios/componentes"],
    version: 1,
  },
  {
    code: "nutricao",
    title: "Nutrição técnica",
    short: "Cálculo sobre versões publicadas.",
    detail: "Não é declaração comercial. Fontes regulatórias apontam o acervo existente.",
    example: "Proteína valorada na versão publicada.",
    related: ["dossie", "rotulo"],
    routes: ["/conformidade"],
    version: 1,
  },
  {
    code: "dossie",
    title: "Dossiê e evidência",
    short: "Pacote de revisão humana.",
    detail: "Não certifica conformidade sozinho.",
    example: "Dossiê do pão tradicional com achados abertos.",
    related: ["rotulo", "nutricao"],
    routes: ["/conformidade/dossies"],
    version: 1,
  },
  {
    code: "rotulo",
    title: "Candidato de rótulo",
    short: "Proposta para revisão, não selo.",
    detail: "Aprovação humana. Sem aparência de certificado.",
    example: "Rótulo candidato v2 em revisão.",
    related: ["dossie"],
    routes: ["/conformidade/rotulos"],
    version: 1,
  },
  {
    code: "custo_previsto",
    title: "Custo previsto, padrão e realizado",
    short: "Três recortes soberanos do 021.",
    detail: "Estoque não calcula custo médio nem FIFO.",
    example: "Previsto da formulação; realizado do consumo.",
    related: ["markup", "margem"],
    routes: ["/gestao/custos"],
    version: 1,
  },
  {
    code: "markup",
    title: "Markup, margem bruta e contribuição",
    short: "Formação de preço assistida.",
    detail: "Simulação não publica preço.",
    example: "Markup 2,4; margem bruta estimada.",
    related: ["custo_previsto"],
    routes: ["/gestao/custos/simulacoes"],
    version: 1,
  },
  {
    code: "lote",
    title: "Lote e saldos",
    short: "Físico, reservado, disponível e em trânsito.",
    detail: "Saldo é projeção do histórico de movimentos. Reserva não move o físico.",
    example: "800 g disponíveis, 200 g reservadas.",
    related: ["inventario", "recebimento"],
    routes: ["/componentes/estoque", "/componentes/lotes"],
    version: 1,
  },
  {
    code: "inventario",
    title: "Inventário físico",
    short: "Contagem com corte e ajuste auditável.",
    detail: "Reabertura proibida. Correção é novo ciclo.",
    example: "Sessão do almoxarifado com divergência −10 g.",
    related: ["lote"],
    routes: ["/gestao/inventarios"],
    version: 1,
  },
  {
    code: "compra",
    title: "Requisição, cotação, pedido e recebimento",
    short: "Compras humanas, internas.",
    detail: "Pedido emitido não é enviado ao fornecedor. Sem compra automática.",
    example: "Requisição aprovada → pedido interno → recebimento parcial.",
    related: ["lote"],
    routes: ["/gestao/compras/necessidades"],
    version: 1,
  },
  {
    code: "cobertura",
    title: "Cobertura, ausência, zero conhecido, snapshot e drill-down",
    short: "Ausência não é zero.",
    detail: "Relatórios do 022. Snapshot congela a projeção.",
    example: "Indicador indisponível por falta de ponto de reposição.",
    related: ["custo_previsto", "lote"],
    routes: ["/gestao/relatorios"],
    version: 1,
  },
];
