import { FALLBACK_GUIDE } from "./fallback";

export type RouteGuide = {
  id: string;
  pattern: string;
  domain: string;
  section: string;
  title: string;
  goal: string;
  entity: string;
  permissions: string[];
  actions: string[];
  pending: string;
  blocks: string;
  next: string;
  related: string[];
  destinations: Array<{ to: string; label: string; permission?: string }>;
  version: 1;
};

export const ROUTE_GUIDES: RouteGuide[] = [
  { id: "login", pattern: "/entrar", domain: "acesso", section: "entrada", title: "Entrar", goal: "Autenticar sem depender do conteúdo editorial.", entity: "sessão", permissions: [], actions: ["Entrar"], pending: "Emissor configurado em produção.", blocks: "Provedor falso bloqueado em produção.", next: "Entrar com o provedor da organização.", related: [], destinations: [], version: 1 },
  { id: "callback", pattern: "/callback", domain: "acesso", section: "retorno", title: "Retorno da autenticação", goal: "Concluir o código de autorização.", entity: "sessão", permissions: [], actions: [], pending: "", blocks: "Código inválido ou sessão expirada.", next: "Aguardar o redirecionamento.", related: [], destinations: [], version: 1 },
  { id: "org", pattern: "/organizacao", domain: "acesso", section: "contexto", title: "Escolher organização", goal: "Definir o contexto autorizado.", entity: "associação", permissions: [], actions: ["Selecionar"], pending: "Mais de uma associação ativa.", blocks: "Nenhuma associação.", next: "Escolher a organização do turno.", related: [], destinations: [{ to: "/inicio", label: "Início" }], version: 1 },
  { id: "inicio", pattern: "/inicio", domain: "inicio", section: "hub", title: "Início", goal: "Escolher o domínio do trabalho.", entity: "atalhos", permissions: [], actions: ["Abrir um domínio"], pending: "", blocks: "", next: "Ir ao quadro ou ao cadastro necessário.", related: ["ordem"], destinations: [{ to: "/producao", label: "Quadro", permission: "production.board.read" }], version: 1 },
  { id: "ingredientes", pattern: "/componentes/ingredientes", domain: "componentes", section: "ingredientes", title: "Ingredientes", goal: "Pesquisar e versionar ingredientes.", entity: "ingrediente", permissions: ["ingredient.read"], actions: ["Pesquisar", "Abrir"], pending: "Versões incompletas.", blocks: "Sem permissão de criação.", next: "Abrir um ingrediente ou criar rascunho.", related: ["ingrediente", "versao"], destinations: [{ to: "/componentes/ingredientes/novo", label: "Novo", permission: "ingredient.create" }], version: 1 },
  { id: "ingrediente-novo", pattern: "/componentes/ingredientes/novo", domain: "componentes", section: "ingredientes", title: "Novo ingrediente", goal: "Criar rascunho sem publicar sozinho.", entity: "ingrediente", permissions: ["ingredient.create"], actions: ["Salvar rascunho"], pending: "Composição e unidade.", blocks: "Publicação exige aprovação.", next: "Completar identidade e composição.", related: ["ingrediente"], destinations: [{ to: "/componentes/ingredientes", label: "Lista" }], version: 1 },
  { id: "ingrediente", pattern: "/componentes/ingredientes/:ingredientId", domain: "componentes", section: "ingredientes", title: "Ingrediente", goal: "Revisar versões e publicar com trilha.", entity: "ingrediente", permissions: ["ingredient.read"], actions: ["Revisar", "Publicar se autorizado"], pending: "Lacunas da versão.", blocks: "Versão publicada imutável.", next: "Corrigir lacunas ou abrir nova versão.", related: ["versao", "composicao"], destinations: [{ to: "/componentes/ingredientes", label: "Lista" }], version: 1 },
  { id: "estoque", pattern: "/componentes/estoque", domain: "estoque", section: "visao", title: "Estoque", goal: "Ver físico, reservado, disponível e trânsito.", entity: "saldo", permissions: ["inventory.read"], actions: ["Abrir posição"], pending: "Itens sem ponto de reposição.", blocks: "Sem política publicada.", next: "Abrir posição ou validades.", related: ["lote"], destinations: [{ to: "/componentes/estoque/posicao", label: "Posição" }], version: 1 },
  { id: "posicao", pattern: "/componentes/estoque/posicao", domain: "estoque", section: "posicao", title: "Posição", goal: "Ler saldo por item, local e lote.", entity: "saldo", permissions: ["inventory.read"], actions: ["Filtrar"], pending: "409 exige recarregar.", blocks: "Saldo insuficiente em saída.", next: "Investigar lote ou reserva.", related: ["lote"], destinations: [{ to: "/componentes/lotes", label: "Lotes" }], version: 1 },
  { id: "reservas", pattern: "/componentes/estoque/reservas", domain: "estoque", section: "reservas", title: "Reservas", goal: "Ver necessidade versus alocação.", entity: "reserva", permissions: ["inventory.read"], actions: ["Ler"], pending: "Ordens históricas sem adoção.", blocks: "Reserva não move físico.", next: "Adotar ordem antiga se autorizado.", related: ["ordem", "lote"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "movimentos", pattern: "/componentes/estoque/movimentacoes", domain: "estoque", section: "ledger", title: "Movimentações", goal: "Ler o ledger append-only.", entity: "movimento", permissions: ["inventory.read"], actions: ["Ler"], pending: "", blocks: "Sem edição histórica.", next: "Abrir rastreabilidade do movimento.", related: ["lote"], destinations: [{ to: "/rastreabilidade", label: "Rastreabilidade" }], version: 1 },
  { id: "separacao", pattern: "/componentes/estoque/separacao", domain: "estoque", section: "pick", title: "Separação", goal: "Confirmar lotes sugeridos por FEFO.", entity: "separação", permissions: ["inventory.separate"], actions: ["Confirmar pick"], pending: "Lote obrigatório ausente.", blocks: "FEFO é sugestão.", next: "Confirmar quantidades humanas.", related: ["lote", "consumo"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "lotes", pattern: "/componentes/lotes", domain: "estoque", section: "validade", title: "Lotes e validade", goal: "Revisar validade e bloqueio.", entity: "lote", permissions: ["inventory.read"], actions: ["Filtrar"], pending: "Lotes sem validade.", blocks: "Vencido exige justificativa.", next: "Revisar bloqueados.", related: ["lote"], destinations: [{ to: "/componentes/estoque", label: "Estoque" }], version: 1 },
  { id: "fornecedores", pattern: "/componentes/fornecedores", domain: "componentes", section: "fornecedores", title: "Fornecedores", goal: "Ler cadastro e itens.", entity: "fornecedor", permissions: ["supplier.read"], actions: ["Pesquisar"], pending: "Preço desatualizado.", blocks: "Preço observado não atualiza sozinho.", next: "Abrir item do fornecedor.", related: ["compra"], destinations: [{ to: "/gestao/compras/cotacoes", label: "Cotações" }], version: 1 },
  { id: "catalogos", pattern: "/componentes/catalogos", domain: "componentes", section: "fontes", title: "Fontes técnicas", goal: "Consultar unidades, nutrientes e alergênicos.", entity: "catálogo", permissions: ["ingredient.read"], actions: ["Ler"], pending: "", blocks: "", next: "Usar o código na ficha.", related: ["ingrediente"], destinations: [{ to: "/componentes/ingredientes", label: "Ingredientes" }], version: 1 },
  { id: "receitas", pattern: "/receitas", domain: "receitas", section: "lista", title: "Receitas", goal: "Pesquisar fichas técnicas.", entity: "receita", permissions: ["recipe.read"], actions: ["Pesquisar"], pending: "Versões em rascunho.", blocks: "", next: "Abrir uma receita ou o assistente.", related: ["receita"], destinations: [{ to: "/receitas/assistente", label: "Assistente" }], version: 1 },
  { id: "receita-ai", pattern: "/receitas/assistente", domain: "receitas", section: "ia", title: "Assistente de receitas", goal: "Propor criação ou adaptação.", entity: "proposta", permissions: ["recipe.read"], actions: ["Criar", "Adaptar"], pending: "Revisão humana.", blocks: "IA não publica.", next: "Escolher criar ou adaptar.", related: ["receita"], destinations: [{ to: "/receitas/assistente/criar", label: "Criar", permission: "recipe.ai.propose" }], version: 1 },
  { id: "receita-ai-criar", pattern: "/receitas/assistente/criar", domain: "receitas", section: "ia", title: "Criar com assistência", goal: "Coletar objetivo e restrições.", entity: "proposta", permissions: ["recipe.ai.propose"], actions: ["Avançar"], pending: "Objetivo.", blocks: "Sem chat livre.", next: "Completar o roteiro.", related: ["receita"], destinations: [{ to: "/receitas/assistente", label: "Hub" }], version: 1 },
  { id: "receita-ai-adaptar", pattern: "/receitas/assistente/adaptar", domain: "receitas", section: "ia", title: "Adaptar com assistência", goal: "Partir de uma receita existente.", entity: "proposta", permissions: ["recipe.ai.propose"], actions: ["Avançar"], pending: "Receita base.", blocks: "Sem publicação automática.", next: "Informar a adaptação.", related: ["receita"], destinations: [{ to: "/receitas/assistente", label: "Hub" }], version: 1 },
  { id: "receita-ai-hist", pattern: "/receitas/assistente/historico", domain: "receitas", section: "ia", title: "Histórico de propostas", goal: "Rever decisões humanas.", entity: "proposta", permissions: ["recipe.read"], actions: ["Abrir"], pending: "Propostas em revisão.", blocks: "", next: "Abrir uma proposta.", related: ["receita"], destinations: [{ to: "/receitas/assistente", label: "Hub" }], version: 1 },
  { id: "receita-ai-detalhe", pattern: "/receitas/assistente/:proposalId", domain: "receitas", section: "ia", title: "Proposta", goal: "Comparar, citar e decidir.", entity: "proposta", permissions: ["recipe.read"], actions: ["Aceitar", "Rejeitar"], pending: "Itens sem decisão.", blocks: "Materialização vira rascunho.", next: "Decidir cada mudança.", related: ["receita"], destinations: [{ to: "/receitas", label: "Receitas" }], version: 1 },
  { id: "receita-nova", pattern: "/receitas/novo", domain: "receitas", section: "editor", title: "Nova receita", goal: "Criar rascunho atômico.", entity: "receita", permissions: ["recipe.create"], actions: ["Salvar"], pending: "Componentes.", blocks: "", next: "Informar código e nome.", related: ["receita"], destinations: [{ to: "/receitas", label: "Lista" }], version: 1 },
  { id: "receita", pattern: "/receitas/:recipeId", domain: "receitas", section: "editor", title: "Receita", goal: "Editar componentes e processo.", entity: "receita", permissions: ["recipe.read"], actions: ["Salvar rascunho"], pending: "Percentuais.", blocks: "Publicada imutável.", next: "Completar o atelier.", related: ["percentual_padeiro"], destinations: [{ to: "/receitas", label: "Lista" }], version: 1 },
  { id: "ficha-receita", pattern: "/receitas/:recipeId/versoes/:versionId/ficha", domain: "receitas", section: "ficha", title: "Ficha da receita", goal: "Ler o snapshot técnico.", entity: "versão", permissions: ["recipe.technical_sheet.read"], actions: ["Imprimir"], pending: "", blocks: "", next: "Voltar à receita.", related: ["receita"], destinations: [{ to: "/receitas", label: "Receitas" }], version: 1 },
  { id: "quadro", pattern: "/producao", domain: "producao", section: "quadro", title: "Quadro de produção", goal: "Conduzir o turno sem custos.", entity: "ordem", permissions: ["production.board.read"], actions: ["Definir contexto", "Filtrar", "Abrir ordem"], pending: "Contexto do turno.", blocks: "Sem acesso ao estabelecimento.", next: "Definir contexto ou executar a próxima ação.", related: ["ordem", "etapa"], destinations: [{ to: "/planejamento", label: "Planejamento" }], version: 1 },
  { id: "planos", pattern: "/planejamento", domain: "producao", section: "planos", title: "Planejamento", goal: "Ler e abrir planos.", entity: "plano", permissions: ["production.plan.read"], actions: ["Abrir"], pending: "Planos em rascunho.", blocks: "", next: "Abrir um plano do turno.", related: ["plano"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "plano", pattern: "/planejamento/:planId", domain: "producao", section: "planos", title: "Plano", goal: "Rever itens e gerar ordens.", entity: "plano", permissions: ["production.plan.read"], actions: ["Ler"], pending: "Itens sem produto.", blocks: "", next: "Ir às ordens geradas.", related: ["plano", "ordem"], destinations: [{ to: "/ordens", label: "Ordens" }], version: 1 },
  { id: "ordens", pattern: "/ordens", domain: "producao", section: "ordens", title: "Ordens", goal: "Listar ordens da organização.", entity: "ordem", permissions: ["production.order.read"], actions: ["Abrir"], pending: "", blocks: "", next: "Abrir a ordem do turno.", related: ["ordem"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "ordem", pattern: "/ordens/:orderId", domain: "producao", section: "ordens", title: "Ordem", goal: "Separar planejado e realizado.", entity: "ordem", permissions: ["production.order.read"], actions: ["Executar"], pending: "Materiais.", blocks: "", next: "Abrir a execução se autorizado.", related: ["ordem", "consumo"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "executar", pattern: "/producao/ordens/:orderId/executar", domain: "producao", section: "execucao", title: "Execução", goal: "Pesar, consumir e concluir.", entity: "execução", permissions: ["production.order.read"], actions: ["Registrar"], pending: "Conferência.", blocks: "Comando pendente.", next: "Seguir a próxima ação da ordem.", related: ["pesagem", "consumo"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "ficha-ordem", pattern: "/ordens/:orderId/fichas/:issueId", domain: "producao", section: "ficha", title: "Ficha impressa", goal: "Emitir a ficha do chão.", entity: "emissão", permissions: ["production.order.read"], actions: ["Imprimir"], pending: "", blocks: "Ordem cancelada.", next: "Imprimir sem chrome.", related: ["ordem"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "rastreio", pattern: "/rastreabilidade", domain: "producao", section: "rastreio", title: "Rastreabilidade", goal: "Buscar a linha do tempo.", entity: "evento", permissions: ["production.traceability.read"], actions: ["Buscar"], pending: "", blocks: "", next: "Abrir uma ordem.", related: ["ordem"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "rastreio-ordem", pattern: "/rastreabilidade/:orderId", domain: "producao", section: "rastreio", title: "Linha do tempo", goal: "Ler correlação e hashes.", entity: "evento", permissions: ["production.traceability.read"], actions: ["Ler"], pending: "", blocks: "Sem permissão.", next: "Seguir um nó.", related: ["ordem"], destinations: [{ to: "/ordens", label: "Ordens" }], version: 1 },
  { id: "conformidade", pattern: "/conformidade", domain: "conformidade", section: "visao", title: "Conformidade", goal: "Revisar dossiês sem selo automático.", entity: "dossiê", permissions: ["labeling.read"], actions: ["Abrir"], pending: "Avaliações abertas.", blocks: "Sem certificar sozinho.", next: "Abrir um dossiê.", related: ["dossie"], destinations: [{ to: "/conformidade/dossies", label: "Dossiês" }], version: 1 },
  { id: "dossies", pattern: "/conformidade/dossies", domain: "conformidade", section: "dossies", title: "Dossiês", goal: "Listar pacotes de revisão.", entity: "dossiê", permissions: ["labeling.read"], actions: ["Abrir"], pending: "", blocks: "", next: "Criar ou abrir.", related: ["dossie"], destinations: [{ to: "/conformidade/dossies/novo", label: "Novo", permission: "labeling.dossier.create" }], version: 1 },
  { id: "dossie-novo", pattern: "/conformidade/dossies/novo", domain: "conformidade", section: "dossies", title: "Novo dossiê", goal: "Abrir revisão humana.", entity: "dossiê", permissions: ["labeling.dossier.create"], actions: ["Criar"], pending: "Produto.", blocks: "", next: "Informar o recorte.", related: ["dossie"], destinations: [{ to: "/conformidade/dossies", label: "Lista" }], version: 1 },
  { id: "dossie", pattern: "/conformidade/dossies/:dossierId", domain: "conformidade", section: "dossies", title: "Dossiê", goal: "Ler achados e advertências.", entity: "dossiê", permissions: ["labeling.read"], actions: ["Revisar"], pending: "Achados.", blocks: "Não é certificado.", next: "Registrar revisão.", related: ["dossie", "rotulo"], destinations: [{ to: "/conformidade/rotulos", label: "Rótulos" }], version: 1 },
  { id: "dossie-print", pattern: "/conformidade/dossies/:dossierId/imprimir", domain: "conformidade", section: "dossies", title: "Impressão do dossiê", goal: "Imprimir sem chrome.", entity: "dossiê", permissions: ["labeling.render"], actions: ["Imprimir"], pending: "", blocks: "", next: "Imprimir.", related: ["dossie"], destinations: [{ to: "/conformidade/dossies", label: "Lista" }], version: 1 },
  { id: "avaliacoes", pattern: "/conformidade/avaliacoes", domain: "conformidade", section: "avaliacoes", title: "Avaliações", goal: "Acompanhar revisões.", entity: "avaliação", permissions: ["labeling.read"], actions: ["Ler"], pending: "Pendências.", blocks: "", next: "Abrir o dossiê ligado.", related: ["dossie"], destinations: [{ to: "/conformidade/dossies", label: "Dossiês" }], version: 1 },
  { id: "rotulos", pattern: "/conformidade/rotulos", domain: "conformidade", section: "rotulos", title: "Rótulos candidatos", goal: "Revisar candidatos.", entity: "rótulo", permissions: ["labeling.read"], actions: ["Revisar"], pending: "Textos.", blocks: "Sem selo automático.", next: "Comparar versões.", related: ["rotulo"], destinations: [{ to: "/conformidade", label: "Visão" }], version: 1 },
  { id: "fontes", pattern: "/conformidade/fontes", domain: "conformidade", section: "fontes", title: "Fontes e normas", goal: "Apontar o acervo existente.", entity: "fonte", permissions: ["regulatory.source.read"], actions: ["Ler"], pending: "", blocks: "Não improvisar norma.", next: "Citar a fonte no dossiê.", related: ["nutricao"], destinations: [{ to: "/conformidade", label: "Visão" }], version: 1 },
  { id: "custos", pattern: "/gestao/custos", domain: "gestao", section: "custos", title: "Custos e preços", goal: "Ler recortes soberanos.", entity: "cálculo", permissions: ["costing.read"], actions: ["Abrir"], pending: "Política.", blocks: "Estoque não valora.", next: "Abrir previstos ou simulação.", related: ["custo_previsto"], destinations: [{ to: "/gestao/custos/politicas", label: "Políticas" }], version: 1 },
  { id: "politicas-custo", pattern: "/gestao/custos/politicas", domain: "gestao", section: "custos", title: "Políticas de custeio", goal: "Ler versões publicadas.", entity: "política", permissions: ["costing.read"], actions: ["Ler"], pending: "", blocks: "Publicada imutável.", next: "Usar a política vigente.", related: ["custo_previsto"], destinations: [{ to: "/gestao/custos", label: "Visão" }], version: 1 },
  { id: "previstos", pattern: "/gestao/custos/previstos", domain: "gestao", section: "custos", title: "Custos previstos", goal: "Ler cálculos planejados.", entity: "cálculo", permissions: ["costing.read"], actions: ["Abrir"], pending: "Lacunas.", blocks: "", next: "Abrir um cálculo.", related: ["custo_previsto"], destinations: [{ to: "/gestao/custos", label: "Visão" }], version: 1 },
  { id: "realizados", pattern: "/gestao/custos/realizados", domain: "gestao", section: "custos", title: "Custos realizados", goal: "Ler cálculos da execução.", entity: "cálculo", permissions: ["costing.read"], actions: ["Abrir"], pending: "Consumos.", blocks: "", next: "Reconciliar com a ordem.", related: ["custo_previsto", "consumo"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "calculo", pattern: "/gestao/custos/calculos/:calcId", domain: "gestao", section: "custos", title: "Cálculo", goal: "Ler composição e lacunas.", entity: "cálculo", permissions: ["costing.read"], actions: ["Ler"], pending: "Cobertura.", blocks: "", next: "Simular preço se autorizado.", related: ["markup"], destinations: [{ to: "/gestao/custos/simulacoes", label: "Simulações" }], version: 1 },
  { id: "simulacoes", pattern: "/gestao/custos/simulacoes", domain: "gestao", section: "precos", title: "Simulações", goal: "Simular markup sem publicar.", entity: "simulação", permissions: ["pricing.simulation.manage"], actions: ["Simular"], pending: "Canal.", blocks: "Não publica preço.", next: "Comparar canais.", related: ["markup"], destinations: [{ to: "/gestao/custos/precos", label: "Preços" }], version: 1 },
  { id: "precos", pattern: "/gestao/custos/precos", domain: "gestao", section: "precos", title: "Preços praticados", goal: "Revisar preços humanos.", entity: "preço", permissions: ["pricing.review"], actions: ["Revisar"], pending: "", blocks: "", next: "Registrar revisão.", related: ["markup"], destinations: [{ to: "/gestao/custos", label: "Visão" }], version: 1 },
  { id: "necessidades", pattern: "/gestao/compras/necessidades", domain: "compras", section: "reposicao", title: "Necessidades", goal: "Ler sugestão determinística.", entity: "sugestão", permissions: ["procurement.read"], actions: ["Criar requisição"], pending: "Lacunas de ponto e embalagem.", blocks: "Sem compra automática.", next: "Revisar cobertura e abrir requisição.", related: ["compra"], destinations: [{ to: "/gestao/compras/requisicoes", label: "Requisições" }], version: 1 },
  { id: "requisicoes", pattern: "/gestao/compras/requisicoes", domain: "compras", section: "req", title: "Requisições", goal: "Acompanhar aprovação humana.", entity: "requisição", permissions: ["procurement.read"], actions: ["Ler"], pending: "Rascunhos.", blocks: "Padeiro não cria.", next: "Enviar para aprovação.", related: ["compra"], destinations: [{ to: "/gestao/compras/cotacoes", label: "Cotações" }], version: 1 },
  { id: "cotacoes", pattern: "/gestao/compras/cotacoes", domain: "compras", section: "cotacao", title: "Cotações", goal: "Comparar sem escolher sozinho.", entity: "cotação", permissions: ["procurement.read"], actions: ["Comparar"], pending: "Validade da proposta.", blocks: "Escolha automática proibida.", next: "Registrar outra cotação.", related: ["compra"], destinations: [{ to: "/gestao/compras/pedidos", label: "Pedidos" }], version: 1 },
  { id: "pedidos", pattern: "/gestao/compras/pedidos", domain: "compras", section: "pedido", title: "Pedidos", goal: "Ler pedidos internos.", entity: "pedido", permissions: ["procurement.read"], actions: ["Ler"], pending: "Emissão humana.", blocks: "Sem envio externo.", next: "Receber se emitido.", related: ["compra"], destinations: [{ to: "/gestao/compras/recebimentos", label: "Recebimentos" }], version: 1 },
  { id: "recebimentos", pattern: "/gestao/compras/recebimentos", domain: "compras", section: "recebimento", title: "Recebimentos", goal: "Conferir e criar lote.", entity: "recebimento", permissions: ["procurement.receive"], actions: ["Receber"], pending: "Divergência.", blocks: "Preço observado é comando à parte.", next: "Informar lote e validade.", related: ["lote", "compra"], destinations: [{ to: "/componentes/lotes", label: "Lotes" }], version: 1 },
  { id: "devolucoes", pattern: "/gestao/compras/devolucoes", domain: "compras", section: "devolucao", title: "Devoluções", goal: "Registrar saída ao fornecedor.", entity: "devolução", permissions: ["procurement.return"], actions: ["Devolver"], pending: "Motivo.", blocks: "Sem crédito financeiro.", next: "Vincular ao lote.", related: ["compra", "lote"], destinations: [{ to: "/gestao/compras/recebimentos", label: "Recebimentos" }], version: 1 },
  { id: "inventarios", pattern: "/gestao/inventarios", domain: "estoque", section: "contagem", title: "Inventários", goal: "Contar e fechar com auditoria.", entity: "sessão", permissions: ["inventory.count"], actions: ["Contar"], pending: "Divergências.", blocks: "Reabertura proibida.", next: "Revisar e aprovar se autorizado.", related: ["inventario"], destinations: [{ to: "/componentes/estoque", label: "Estoque" }], version: 1 },
  { id: "relatorios", pattern: "/gestao/relatorios", domain: "relatorios", section: "hub", title: "Relatórios e painéis", goal: "Escolher um recorte com cobertura.", entity: "relatório", permissions: [], actions: ["Abrir"], pending: "Permissão do recorte.", blocks: "Ausência ≠ zero.", next: "Abrir a visão autorizada.", related: ["cobertura"], destinations: [{ to: "/gestao/relatorios/executivo", label: "Executivo", permission: "reporting.dashboard.read" }], version: 1 },
  { id: "rel-exec", pattern: "/gestao/relatorios/executivo", domain: "relatorios", section: "executivo", title: "Visão executiva", goal: "Ler indicadores com cobertura.", entity: "relatório", permissions: ["reporting.dashboard.read"], actions: ["Filtrar"], pending: "Período.", blocks: "", next: "Abrir drill-down.", related: ["cobertura"], destinations: [{ to: "/gestao/relatorios/salvos", label: "Salvos" }], version: 1 },
  { id: "rel-prod", pattern: "/gestao/relatorios/producao", domain: "relatorios", section: "producao", title: "Relatório de produção", goal: "Ler volume e estados.", entity: "relatório", permissions: ["reporting.production.read"], actions: ["Filtrar"], pending: "", blocks: "", next: "Abrir uma ordem.", related: ["ordem"], destinations: [{ to: "/producao", label: "Quadro" }], version: 1 },
  { id: "rel-comp", pattern: "/gestao/relatorios/componentes", domain: "relatorios", section: "perdas", title: "Componentes e perdas", goal: "Ler consumo e rendimento.", entity: "relatório", permissions: ["reporting.production.read"], actions: ["Filtrar"], pending: "Cobertura de rendimento.", blocks: "", next: "Investigar desperdício.", related: ["rendimento"], destinations: [{ to: "/componentes/estoque", label: "Estoque" }], version: 1 },
  { id: "rel-custo", pattern: "/gestao/relatorios/custos", domain: "relatorios", section: "custos", title: "Relatório de custos", goal: "Ler custos e preços autorizados.", entity: "relatório", permissions: ["reporting.costing.read"], actions: ["Filtrar"], pending: "", blocks: "Sem valor contábil de estoque.", next: "Abrir um cálculo.", related: ["custo_previsto"], destinations: [{ to: "/gestao/custos", label: "Custos" }], version: 1 },
  { id: "rel-conf", pattern: "/gestao/relatorios/conformidade", domain: "relatorios", section: "conf", title: "Relatório de conformidade", goal: "Ler cobertura de dossiês.", entity: "relatório", permissions: ["reporting.compliance.read"], actions: ["Filtrar"], pending: "", blocks: "Não certifica.", next: "Abrir um dossiê.", related: ["dossie"], destinations: [{ to: "/conformidade", label: "Conformidade" }], version: 1 },
  { id: "rel-rast", pattern: "/gestao/relatorios/rastreabilidade", domain: "relatorios", section: "rast", title: "Relatório de rastreabilidade", goal: "Ler cobertura de eventos.", entity: "relatório", permissions: ["reporting.traceability.read"], actions: ["Filtrar"], pending: "", blocks: "", next: "Abrir uma linha do tempo.", related: ["ordem"], destinations: [{ to: "/rastreabilidade", label: "Rastreabilidade" }], version: 1 },
  { id: "rel-est", pattern: "/gestao/relatorios/estoque", domain: "relatorios", section: "estoque", title: "Relatório de estoque", goal: "Ler posição e necessidades.", entity: "relatório", permissions: ["reporting.inventory.read"], actions: ["Filtrar"], pending: "Ponto de reposição.", blocks: "Sem valor contábil.", next: "Abrir um item.", related: ["lote", "cobertura"], destinations: [{ to: "/componentes/estoque", label: "Estoque" }], version: 1 },
  { id: "rel-qual", pattern: "/gestao/relatorios/qualidade", domain: "relatorios", section: "qualidade", title: "Qualidade dos dados", goal: "Ler pendências coletivas.", entity: "relatório", permissions: ["reporting.data_quality.read"], actions: ["Filtrar"], pending: "Lacunas.", blocks: "Sem ranking individual.", next: "Abrir o domínio da lacuna.", related: ["cobertura"], destinations: [{ to: "/inicio", label: "Início" }], version: 1 },
  { id: "rel-salvos", pattern: "/gestao/relatorios/salvos", domain: "relatorios", section: "salvos", title: "Relatórios salvos", goal: "Reabrir visões.", entity: "visão", permissions: ["reporting.saved_view.manage"], actions: ["Abrir"], pending: "", blocks: "", next: "Abrir uma visão.", related: ["cobertura"], destinations: [{ to: "/gestao/relatorios", label: "Hub" }], version: 1 },
  { id: "snapshot", pattern: "/gestao/relatorios/snapshots/:snapshotId", domain: "relatorios", section: "snapshot", title: "Snapshot", goal: "Ler projeção congelada.", entity: "snapshot", permissions: ["reporting.snapshot.create"], actions: ["Ler"], pending: "", blocks: "", next: "Comparar com o vivo.", related: ["cobertura"], destinations: [{ to: "/gestao/relatorios", label: "Hub" }], version: 1 },
];

export function matchGuide(pathname: string): RouteGuide | undefined {
  const exact = ROUTE_GUIDES.find((row) => row.pattern === pathname);
  if (exact) return exact;
  const scored = ROUTE_GUIDES.map((row) => {
    const parts = row.pattern.split("/").filter(Boolean);
    const got = pathname.split("/").filter(Boolean);
    if (parts.length !== got.length) return { row, score: -1 };
    let score = 0;
    for (let i = 0; i < parts.length; i += 1) {
      if (parts[i].startsWith(":")) score += 1;
      else if (parts[i] === got[i]) score += 3;
      else return { row, score: -1 };
    }
    return { row, score };
  })
    .filter((item) => item.score >= 0)
    .sort((a, b) => b.score - a.score);
  return scored[0]?.row;
}

export function resolveGuide(pathname: string): { guide: RouteGuide; specific: boolean } {
  const found = matchGuide(pathname);
  if (found) return { guide: found, specific: true };
  return { guide: FALLBACK_GUIDE, specific: false };
}
